---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: azure-iot-operations-aio-selfsigned-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: azure-iot-operations-aio-selfsigned-root
  namespace: cert-manager
spec:
  isCA: true
  secretName: azure-iot-operations-aio-ca-certificate
  commonName: Azure IoT Operations Quickstart Root CA - Not for Production
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: azure-iot-operations-aio-selfsigned-root
  privateKey:
    rotationPolicy: Never
    algorithm: RSA
    encoding: PKCS1
    size: 2048
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: azure-iot-operations-aio-certificate-issuer
spec:
  ca:
    secretName: azure-iot-operations-aio-ca-certificate
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: azure-iot-operations-aio-ca-trust-bundle
spec:
  sources:
    - secret:
        name: azure-iot-operations-aio-ca-certificate
        key: tls.crt
  target:
    configMap:
      key: ca.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: azure-iot-operations

# Setup default Broker/Listener
---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: Broker
metadata:
  name: default
  namespace: azure-iot-operations
spec:
  generateResourceLimits:
    cpu: disabled
  cardinality:
    backendChain:
      partitions: 1
      redundancyFactor: 2
    frontend:
      replicas: 1
---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerListener
metadata:
  name: default
  namespace: azure-iot-operations
spec:
  brokerRef: default
  serviceName: aio-broker
  serviceType: clusterIp
  ports:
    - port: 18883
      authenticationRef: default
      tls:
        mode: automatic
        certManagerCertificateSpec:
          issuerRef:
            kind: ClusterIssuer
            group: cert-manager.io
            name: azure-iot-operations-aio-certificate-issuer
---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerAuthentication
metadata:
  name: default
  namespace: azure-iot-operations
spec:
  authenticationMethods:
    - method: serviceAccountToken
      serviceAccountTokenSettings:
        audiences: 
          - aio-internal


# Setup external listener (LoadBalancer)
---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerListener
metadata:
  name: default-external
  namespace: azure-iot-operations
spec:
  brokerRef: default
  serviceName: aio-broker-external
  serviceType: loadBalancer
  ports:
    - port: 31883
    - port: 38883
      authenticationRef: default-x509
      tls:
        mode: automatic
        certManagerCertificateSpec:
          issuerRef:
            kind: ClusterIssuer
            group: cert-manager.io
            name: azure-iot-operations-aio-certificate-issuer
          san:
            dns:
              - aio-broker
              - localhost
            ip:
              - 127.0.0.1
    - port: 38884
      authenticationRef: default
      tls:
        mode: automatic
        certManagerCertificateSpec:
          issuerRef:
            kind: ClusterIssuer
            group: cert-manager.io
            name: azure-iot-operations-aio-certificate-issuer
          san:
            dns:
              - aio-broker
              - localhost
            ip:
              - 127.0.0.1
---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerAuthentication
metadata:
  name: default-x509
  namespace: azure-iot-operations
spec:
  authenticationMethods:
    - method: X509
      x509Settings:
        trustedClientCaCert: client-ca-trust-bundle
