---
apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: Broker
metadata:
  name: default
  namespace: azure-iot-operations
spec:
  generateResourceLimits:
    cpu: disabled
  cardinality:
    backendChain:
      partitions: 1
      redundancyFactor: 2
    frontend:
      replicas: 1
