# Self signed external CA Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: aio-broker-external-ca
spec:
  selfSigned: {}
---
# Create a CA issuer for external connections that never rotates
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aio-broker-external-ca
  namespace: azure-iot-operations
spec:
  isCA: true
  secretName: aio-broker-external-ca
  commonName: aio-broker-external-ca
  issuerRef:
    kind: ClusterIssuer
    name: aio-broker-external-ca
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never
    algorithm: ECDSA
    size: 256
---
# Issuer to generate the leaf certificates for external connections
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: aio-broker-external
  namespace: azure-iot-operations
spec:
  ca:
    secretName: aio-broker-external-ca
---
# Generate trust bundle for internal connections
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: aio-ca-trust-bundle-test-only
spec:
  sources:
    - secret:
        name: aio-broker-internal-ca
        key: ca.crt
  target:
    configMap:
      key: ca.crt
