// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package rawmodel

import (
	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type RawModelClient struct {
	protocol.Listeners
	*TelemetryReceiver
}

const (
	TelemetryTopic = "test/RawModel/{senderId}/telemetry"
)

func NewRawModelClient(
	app *protocol.Application,
	client protocol.MqttClient,
	telemetryHandler protocol.TelemetryHandler[[]byte],
	opts ...protocol.Option,
) (*RawModelClient, error) {
	var err error

	clientOpts := []protocol.Option{
		protocol.WithTopicTokenNamespace("ex:"),
		protocol.WithTopicTokens{
		},
	}

	var receiverOpts protocol.TelemetryReceiverOptions
	receiverOpts.ApplyOptions(opts, clientOpts...)

	rawModelClient := &RawModelClient{}

	rawModelClient.TelemetryReceiver, err = NewTelemetryReceiver(
		app,
		client,
		TelemetryTopic,
		telemetryHandler,
		&receiverOpts,
	)
	if err != nil {
		rawModelClient.Close()
		return nil, err
	}
	rawModelClient.Listeners = append(rawModelClient.Listeners, rawModelClient.TelemetryReceiver)

	return rawModelClient, nil
}
