/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AkriObservabilityServiceMetricsApis.AkriObservabilityServiceMetricsApis
{
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public enum MetricScope
    {
        [EnumMember(Value = @"customer")]
        Customer = 0,
        [EnumMember(Value = @"internal")]
        Internal = 1,
        [EnumMember(Value = @"regular")]
        Regular = 2,
    }
}
