// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.11.0.0; DO NOT EDIT. */

namespace CloudEvents
{
    public class EmptyJson
    {
    }
}
