/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

use std::time::Duration;

use azure_iot_operations_mqtt::interface::ManagedClient;
use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;
use azure_iot_operations_protocol::common::hybrid_logical_clock::HybridLogicalClock;
use azure_iot_operations_protocol::rpc::command_invoker::{
    CommandInvoker, CommandInvokerOptionsBuilder, CommandRequest, CommandRequestBuilder,
    CommandRequestBuilderError, CommandResponse,
};

use super::increment_response_payload::IncrementResponsePayload;
use super::MODEL_ID;
use super::REQUEST_TOPIC_PATTERN;
use crate::common_types::common_options::CommonOptions;
use crate::common_types::empty_json::EmptyJson;

pub type IncrementRequest = CommandRequest<EmptyJson>;
pub type IncrementResponse = CommandResponse<IncrementResponsePayload>;
pub type IncrementRequestBuilderError = CommandRequestBuilderError;

#[derive(Default)]
pub struct IncrementRequestBuilder {
    inner_builder: CommandRequestBuilder<EmptyJson>,
    set_executor_id: bool,
}

impl IncrementRequestBuilder {
    pub fn custom_user_data(&mut self, custom_user_data: Vec<(String, String)>) -> &mut Self {
        self.inner_builder.custom_user_data(custom_user_data);
        self
    }

    pub fn fencing_token(&mut self, fencing_token: Option<HybridLogicalClock>) -> &mut Self {
        self.inner_builder.fencing_token(fencing_token);
        self
    }

    pub fn timeout(&mut self, timeout: Duration) -> &mut Self {
        self.inner_builder.timeout(timeout);
        self
    }

    pub fn executor_id(&mut self, executor_id: String) -> &mut Self {
        self.inner_builder.executor_id(executor_id);
        self.set_executor_id = true;
        self
    }

    pub fn build(&mut self) -> Result<IncrementRequest, IncrementRequestBuilderError> {
        if !self.set_executor_id {
            return Err(IncrementRequestBuilderError::UninitializedField(
                "executor_id",
            ));
        }

        self.inner_builder.payload(&EmptyJson {}).unwrap();

        self.inner_builder.build()
    }
}

pub struct IncrementCommandInvoker<C>(CommandInvoker<EmptyJson, IncrementResponsePayload, C>)
where
    C: ManagedClient + Clone + Send + Sync + 'static,
    C::PubReceiver: Send + Sync + 'static;

impl<C> IncrementCommandInvoker<C>
where
    C: ManagedClient + Clone + Send + Sync + 'static,
    C::PubReceiver: Send + Sync + 'static,
{
    pub fn new(client: C, options: &CommonOptions) -> Self {
        let mut invoker_options_builder = CommandInvokerOptionsBuilder::default();
        if let Some(topic_namespace) = &options.topic_namespace {
            invoker_options_builder.topic_namespace(topic_namespace.clone());
        }
        let invoker_options = invoker_options_builder
            .model_id(MODEL_ID.to_string())
            .request_topic_pattern(REQUEST_TOPIC_PATTERN)
            .command_name("increment")
            .custom_topic_token_map(options.custom_topic_token_map.clone())
            .build()
            .expect("DTDL schema generated invalid arguments");
        Self(
            CommandInvoker::new(client, invoker_options)
                .expect("DTDL schema generated invalid arguments"),
        )
    }

    pub async fn invoke(
        &self,
        request: IncrementRequest,
    ) -> Result<IncrementResponse, AIOProtocolError> {
        self.0.invoke(request).await
    }
}
