name: "Deploy AIO"
description: "Deploy AIO for pipelines"
inputs:
  server:
    description: Server executable
    required: true
  server-id:
    description: Server mqtt client id
    required: true
runs:
  using: composite
  steps:
    - name: Server
      run: ${{ inputs.server }}
      env: 
        AIO_MQTT_CLIENT_ID: ${{ inputs.server-id }}

    - name: Clients
      run: AIO_MQTT_CLIENT_ID=dotnet-client $DOTNET_CLIENT
      env:
        COUNTER_SERVER_ID: dotnet-server
