apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplereadcloudevents
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplereadcloudevents
  template:
    metadata:
      labels:
        app: samplereadcloudevents
    spec:
      containers:
      - name: samplereadcloudevents
        image: <local-registry>/samplereadcloudevents:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: ca
          mountPath: /certs/ca.crt
          subPath: ca.crt
        - name: mqtt-client-token
          mountPath: /var/run/secrets/tokens
        env:
        - name: ConnectionStrings__Mq
          value: "HostName=aio-broker;ClientId=SampleReadCloudEvents;CaFile=/certs/ca.crt;SatAuthFile=/var/run/secrets/tokens/mqtt-client-token;CleanStart=false;ConnectionTimeout=PT5S"
        - name: mqttDiag
          value: "false"
      volumes:
      - name: ca
        configMap:
          name: aio-ca-trust-bundle-test-only
          items:
            - key: ca.crt 
              path: ca.crt
      - name: mqtt-client-token
        projected:
          sources:
          - serviceAccountToken:
              path: mqtt-client-token
              audience: aio-internal
