/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.SchemaRegistryGenerated
{
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "1.0.0.0")]
    public static class SchemaRegistryErrorTarget
    {
        /// <summary>Indicates the error is related to the schema type.</summary>
        public const string SchemaTypeProperty = "SchemaType";

        /// <summary>Indicates the error is related to the schema format.</summary>
        public const string FormatProperty = "Format";

        /// <summary>Indicates the error is related to the schema version.</summary>
        public const string VersionProperty = "Version";

        /// <summary>Indicates the error is related to the schema name.</summary>
        public const string NameProperty = "Name";

        /// <summary>Indicates the error is related to schema tags.</summary>
        public const string TagsProperty = "Tags";

        /// <summary>Indicates the error is related to the schema description.</summary>
        public const string DescriptionProperty = "Description";

        /// <summary>Indicates the error is related to the schema display name.</summary>
        public const string DisplayNameProperty = "DisplayName";

        /// <summary>Indicates the error is related to the schema content.</summary>
        public const string SchemaContentProperty = "SchemaContent";

        /// <summary>Indicates the error is related to the schema ARM resource.</summary>
        public const string SchemaArmResource = "SchemaArmResource";

        /// <summary>Indicates the error is related to the schema version ARM resource.</summary>
        public const string SchemaVersionArmResource = "SchemaVersionArmResource";

        /// <summary>Indicates the error is related to the schema registry ARM resource.</summary>
        public const string SchemaRegistryArmResource = "SchemaRegistryResource";
    }
}
