/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using TestThing;

namespace TestThing.Counter
{
    /// <summary>
    /// Data values of Events.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "1.0.0.0")]
    public partial class EventCollection
    {
        /// <summary>
        /// The current value of the counter.
        /// </summary>
        [JsonPropertyName("CounterValue")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? CounterValue { get; set; } = default;

    }
}
