/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

#nullable enable

using System;
using System.Collections.Generic;
using Azure.Iot.Operations.Protocol;
using Azure.Iot.Operations.Protocol.Telemetry;
using Azure.Iot.Operations.Protocol.Models;
using TestThing;

namespace TestThing.Counter
{
    public static partial class Counter
    {
        /// <summary>
        /// Specializes the <c>TelemetryReceiver</c> class for type <c>EventCollection</c>.
        /// </summary>
        [TelemetryTopic("telemetry/telemetry-samples/counterValue")]
        public class EventCollectionReceiver : TelemetryReceiver<EventCollection>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="EventCollectionReceiver"/> class.
            /// </summary>
            public EventCollectionReceiver(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, new Utf8JsonSerializer())
            {
            }
        }
    }
}
