/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

#nullable enable

using System;
using System.Collections.Generic;
using Azure.Iot.Operations.Protocol;
using Azure.Iot.Operations.Protocol.RPC;
using Azure.Iot.Operations.Protocol.Models;
using TestThing;

namespace TestThing.Counter
{
    public static partial class Counter
    {
        /// <summary>
        /// Specializes the <c>CommandInvoker</c> class for Command 'reset'.
        /// </summary>
        [CommandTopic("rpc/command-samples/{executorId}/reset")]
        public class ResetActionInvoker : CommandInvoker<EmptyJson, EmptyJson>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="ResetActionInvoker"/> class.
            /// </summary>
            public ResetActionInvoker(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "reset", new Utf8JsonSerializer())
            {
                this.ResponseTopicPrefix = "clients/{invokerClientId}"; // default value, can be overwritten by user code

                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["invokerClientId"] = mqttClient.ClientId;
                }
            }
        }
    }
}
