apiVersion: akri.microsoft.com/v1beta1
kind: ConnectorConfig
metadata:
  name: sql-connector-app-config
  namespace: azure-iot-operations
spec:
  replicas: 3
  assetEndpointProfileType: sql-qualityanalyzer
  image: dockeroliva/sqlqualityanalyzerconnectorapp:v11
  brokerTargetAddress: aio-broker.azure-iot-operations.svc.cluster.local:18883 # expected format: {hostname}:{port}
  brokerTls:
    mode: Enabled
    caTrustBundle: azure-iot-operations-aio-ca-trust-bundle
  brokerAuthentication:
    mode: ServiceAccountToken
    satAudience: aio-internal
