apiVersion: namespaces.deviceregistry.microsoft.com/v1
kind: Asset
metadata:
  name: my-rest-thermostat-asset
  namespace: azure-iot-operations
spec:
  # attributes: # This part of the spec is currently broken in the operator. Re-enable later
  #   assetId: my-rest-thermostat-asset
  #   assetType: thermostat
  datasets:
    - name: thermostat_status
      dataSource: /thermostat
      destinations:
        - configuration:
            topic: mqtt/machine/status
          target: Mqtt
    - name: oven_status
      dataSource: /oven
      destinations:
        - configuration:
            key: oventemp
          target: BrokerStateStore
  defaultDatasetsConfiguration: |-
   {
      "samplingInterval": 4000,
   }
  managementGroups:
    - name: temperature_controls
      actions:
        - name: setTemp
          targetUri: /setTemperature
          topic: thermostat/temperature/set
          actionType: Write
        - name: readHumidity
          targetUri: /readHumidity
          topic: thermostat/humidity/read
          actionType: Read
  deviceRef:
    deviceName: my-thermostat
    endpointName: my-rest-endpoint
  version: 1