dirs:
  - .
useGitIgnore: true
excludedFiles:
  - SECURITY.md # Ignore this as the aka links see to keep breaking
ignorePatterns:
  # There are some dummy links, ignore these
  - pattern: "^http://link_to_"
