apiVersion: v1
kind: Service
metadata:
  name: mqttx-web
spec:
  type: LoadBalancer
  externalIPs:
    - 172.18.0.2
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: mqttx-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttx-web
  namespace: azure-iot-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttx-web
  template:
    metadata:
      labels:
        app: mqttx-web
    spec:
      containers:
        - name: mqttx-web
          image: docker.io/emqx/mqttx-web:latest
          ports:
            - containerPort: 80
          # command: ["sh", "-c"]
          # args:
          # - |
