apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Device
metadata:
  name: rest-sensor
  namespace: azure-iot-operations
spec:
  attributes:
    deviceId: rest-sensor
    deviceType: weather-sensor
  enabled: true
  endpoints:
    inbound:
      rest-sensor-endpoint:
        address: http://rest-server-service.azure-iot-operations.svc.cluster.local:80 # Address of the REST server service
        # additionalConfiguration: |-
        #   {
        #     "tlsEnabled": false
        #   }
        authentication:
          # method: Anonymous
          method: UsernamePassword
          usernamePasswordCredentials:
            usernameSecretName: rest-server-auth-credentials/username
            passwordSecretName: rest-server-auth-credentials/password
        endpointType: rest
        version: "0.0.1"
  version: 1
