/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

mod metric;
mod metric_scope;
mod metric_type;
mod telemetry_collection;
mod telemetry_collection_serialization;
mod telemetry_sender;

pub use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;

pub use super::common_types::common_options::{CommandOptions, TelemetryOptions};

pub const MODEL_ID: &str = "dtmi:jsonTest:AkriObservabilityServiceMetricsApis;1";
pub const TELEMETRY_TOPIC_PATTERN: &str = "akri/connector/resources/telemetry/{ex:connectorClientId}/metrics";

pub mod service {
    pub use super::metric::*;
    pub use super::metric_scope::*;
    pub use super::metric_type::*;
    pub use super::telemetry_collection::*;
    pub use super::telemetry_sender::*;
}
