apiVersion: akri.microsoft.com/v1beta1
kind: ConnectorConfig
metadata:
  name: http-connector-app-config
  namespace: azure-iot-operations
spec:
  replicas: 1
  assetEndpointProfileType: http-dss
  image: httpserverconnectorapp:latest
  mqTargetAddress: aio-broker.azure-iot-operations.svc.cluster.local:18883  # kubectl get services => type = clusterIP => (<name>.<namespace>.svc.cluster.local)
  mqTls:
    enabled: true
    caTrustBundle: azure-iot-operations-aio-ca-trust-bundle
  mqAuthentication:
    audience: aio-internal