/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#![allow(missing_docs)]
#![allow(unused_imports)]
#![allow(dead_code)]
#![allow(clippy::result_large_err)]
pub mod command_complex_schemas;
pub mod common_types;
pub mod shared_schemas;
pub mod telemetry_complex_schemas;
