// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Dtdl2Wot
{
    using System.Collections.Generic;
    using System.Linq;
    using DTDLParser;
    using DTDLParser.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class CommandAffordance : CommandAffordanceBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("    \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Name));
            this.Write("\": {\r\n");
 if (this.dtCommand.Description.Any()) { 
            this.Write("      \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Description.First().Value));
            this.Write("\",\r\n");
 } 
 if (this.dtCommand.Request != null) { 
 if (this.usesTypes) { 
            this.Write("      \"input\": {\r\n");
 if (this.isRequestTransparent) { 
 if (this.dtCommand.Request.Description.Any()) { 
            this.Write("        \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Request.Description.First().Value));
            this.Write("\",\r\n");
 } else if (this.dtCommand.Request.Schema.Description.Any()) { 
            this.Write("        \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Request.Schema.Description.First().Value));
            this.Write("\",\r\n");
 } 
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingDescriber.GetTypeAndAddenda(this.dtCommand.Request.Schema, 8)));
            this.Write("\r\n");
 } else { 
 if (this.dtCommand.Request.Description.Any()) { 
            this.Write("        \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Request.Description.First().Value));
            this.Write("\",\r\n");
 } 
            this.Write("        \"type\": \"object\",\r\n");
 if (!this.dtCommand.Request.Nullable) { 
            this.Write("        \"required\": [ \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Request.Name));
            this.Write("\" ],\r\n");
 } 
            this.Write("        \"properties\": {\r\n          \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Request.Name));
            this.Write("\": {\r\n");
 if (!this.dtCommand.Request.Schema.Id.AbsoluteUri.StartsWith("dtmi:dtdl:instance:Schema:") && this.dtCommand.Request.Schema.Description.Any()) { 
            this.Write("            \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Request.Schema.Description.First().Value));
            this.Write("\",\r\n");
 } 
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingDescriber.GetTypeAndAddenda(this.dtCommand.Request.Schema, 12)));
            this.Write("\r\n          }\r\n        }\r\n");
 } 
            this.Write("      },\r\n");
 } else { 
            this.Write("      \"input\": {\r\n        \"type\": \"null\"\r\n      },\r\n");
 } 
 } 
 if (this.dtCommand.Response != null) { 
 if (this.usesTypes) { 
            this.Write("      \"output\": {\r\n");
 if (this.isResponseTransparent) { 
 if (this.dtCommand.Response.Description.Any()) { 
            this.Write("        \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Response.Description.First().Value));
            this.Write("\",\r\n");
 } else if (this.dtCommand.Response.Schema.Description.Any()) { 
            this.Write("        \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Response.Schema.Description.First().Value));
            this.Write("\",\r\n");
 } 
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingDescriber.GetTypeAndAddenda(this.dtCommand.Response.Schema, 8)));
            this.Write("\r\n");
 } else { 
 if (this.dtCommand.Response.Description.Any()) { 
            this.Write("        \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.dtCommand.Response.Description.First().Value));
            this.Write("\",\r\n");
 } 
            this.Write("        \"type\": \"object\",\r\n");
 if (!this.dtCommand.Response.Nullable) { 
            this.Write("        \"required\": [ \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.responseName));
            this.Write("\" ],\r\n");
 } 
            this.Write("        \"properties\": {\r\n          \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.responseName));
            this.Write("\": {\r\n");
 if (this.responseDescription?.Any() ?? false) { 
            this.Write("            \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.responseDescription.First().Value));
            this.Write("\",\r\n");
 } else if (!this.responseSchema.Id.AbsoluteUri.StartsWith("dtmi:dtdl:instance:Schema:") && this.responseSchema.Description.Any()) { 
            this.Write("            \"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.responseSchema.Description.First().Value));
            this.Write("\",\r\n");
 } 
            this.Write(this.ToStringHelper.ToStringWithCulture(this.thingDescriber.GetTypeAndAddenda(this.responseSchema, 12)));
            this.Write("\r\n          }\r\n        }\r\n");
 } 
            this.Write("      },\r\n");
 } else { 
            this.Write("      \"output\": {\r\n        \"type\": \"null\"\r\n      },\r\n");
 } 
 } 
 if (this.isCommandIdempotent) { 
            this.Write("      \"idempotent\": true,\r\n");
 } 
 if (this.isCommandCacheable) { 
            this.Write("      \"safe\": true,\r\n");
 } 
            this.Write("      \"forms\": [\r\n        {\r\n          \"contentType\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.contentType));
            this.Write("\",\r\n");
 if (this.isResponseSchemaResult) { 
 if (this.errorSchemaName != null) { 
            this.Write("          \"additionalResponses\": [\r\n            {\r\n              \"success\": false" +
                    ",\r\n              \"schema\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.errorSchemaName));
            this.Write("\"\r\n            }\r\n          ],\r\n");
 } 
 if (this.infoSchemaName != null) { 
            this.Write("          \"dtv:headerInfo\": [\r\n            {\r\n              \"contentType\": \"appli" +
                    "cation/json\",\r\n              \"schema\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.infoSchemaName));
            this.Write("\"\r\n            }\r\n          ],\r\n");
 } 
 if (this.codeEnumeration.Count > 0) { 
            this.Write("          \"dtv:headerCode\": [\r\n");
 int ix = 1; foreach (KeyValuePair<string, string> kvp in this.codeEnumeration) { 
            this.Write("            \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            this.Write("\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(ix < this.codeEnumeration.Count ? "," : ""));
            this.Write("\r\n");
 ix++; } 
            this.Write("          ],\r\n");
 } 
 } 
 if (this.serviceGroupId != null) { 
            this.Write("          \"dtv:serviceGroupId\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.serviceGroupId));
            this.Write("\",\r\n");
 } 
            this.Write("          \"dtv:topic\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.commandTopic ?? ""));
            this.Write("\",\r\n          \"op\": \"invokeaction\"\r\n        }\r\n      ]\r\n    }");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class CommandAffordanceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
