/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */
#![allow(non_camel_case_types)]

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Enum_Proximity {
    #[serde(rename = "near")]
    Near,
    #[serde(rename = "far")]
    Far,
}
