apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: Broker
metadata:
  name: broker
  namespace: azure-iot-operations
spec:
  generateResourceLimits:
    cpu: disabled
  cardinality:
    backendChain:
      partitions: 1
      redundancyFactor: 2
    frontend:
      replicas: 1
---
# A listener for local cluster applications to connect with SAT auth
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: listener
  namespace: azure-iot-operations
spec:
  brokerRef: broker
  serviceName: aio-mq-dmqtt-frontend
  serviceType: clusterIp
  ports:
    - port: 8883
      authenticationRef: sat-auth
      tls:
        mode: automatic
        certManagerCertificateSpec:
          issuerRef:
            kind: Issuer
            name: aio-mq-broker-internal-issuer
          san:
            dns:
              - aio-mq-dmqtt-frontend
---
# A listener for off-cluster applications to connect with x509 auth
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: listener-external
  namespace: azure-iot-operations
spec:
  brokerRef: broker
  serviceName: aio-mq-dmqtt-frontend-external
  serviceType: loadBalancer
  ports:
    - port: 31883
    - port: 38883
      authenticationRef: x509-auth
      tls:
        mode: automatic
        certManagerCertificateSpec:
          issuerRef:
            kind: Issuer
            name: aio-mq-broker-external
          san:
            dns:
              - aio-mq-dmqtt-frontend
              - localhost
            ip:
              - 127.0.0.1
---
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerAuthentication
metadata:
  name: sat-auth
  namespace: azure-iot-operations
spec:
  authenticationMethods:
    - method: serviceAccountToken
      serviceAccountTokenSettings:
        audiences: [aio-mq]
---
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerAuthentication
metadata:
  name: x509-auth
  namespace: azure-iot-operations
spec:
  authenticationMethods:
    - method: x509Certificate
      x509Settings:
        trustedClientCaCert: client-ca-trust-bundle
