name: 'Deploy AIO'
description: 'Deploy AIO for pipelines'
inputs:
  wait-for-broker:
    description: 'Wait for the MQTT broker to start before returning'
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Create k3s cluster
      run: tools/deployment/initialize-cluster.sh
      shell: bash

    - name: Install AIO
      uses: azure/iot-operations-sdks-action@main

    - name: Configure AIO
      run: tools/deployment/deploy-aio.sh
      shell: bash

    - name: Wait for Mqtt Broker
      if: ${{ inputs.wait-for-broker == 'true'}}
      run: kubectl wait --for=create pod/aio-broker-frontend-0 --timeout=60s
      shell: bash
