apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smb-connector-leader-election
  labels:
    app: smb-connector
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
