[package]
name = "input_client"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono = { workspace = true, features = ["serde", "clock"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "sync", "time"] }
env_logger.workspace = true
log.workspace = true
azure_iot_operations_mqtt = { path = "../../../azure_iot_operations_mqtt" }
azure_iot_operations_protocol = { path = "../../../azure_iot_operations_protocol" }
azure_iot_operations_services = { path = "../../../azure_iot_operations_services", features=["state_store"] }

[lints]
workspace = true
