/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

/// Indicates the error is related to the schema type.
pub const SCHEMA_TYPE_PROPERTY: &str = "SchemaType";

/// Indicates the error is related to the schema format.
pub const FORMAT_PROPERTY: &str = "Format";

/// Indicates the error is related to the schema version.
pub const VERSION_PROPERTY: &str = "Version";

/// Indicates the error is related to the schema name.
pub const NAME_PROPERTY: &str = "Name";

/// Indicates the error is related to schema tags.
pub const TAGS_PROPERTY: &str = "Tags";

/// Indicates the error is related to the schema description.
pub const DESCRIPTION_PROPERTY: &str = "Description";

/// Indicates the error is related to the schema display name.
pub const DISPLAY_NAME_PROPERTY: &str = "DisplayName";

/// Indicates the error is related to the schema content.
pub const SCHEMA_CONTENT_PROPERTY: &str = "SchemaContent";

/// Indicates the error is related to the schema ARM resource.
pub const SCHEMA_ARM_RESOURCE: &str = "SchemaArmResource";

/// Indicates the error is related to the schema version ARM resource.
pub const SCHEMA_VERSION_ARM_RESOURCE: &str = "SchemaVersionArmResource";

/// Indicates the error is related to the schema registry ARM resource.
pub const SCHEMA_REGISTRY_ARM_RESOURCE: &str = "SchemaRegistryResource";
