/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

/// The request is invalid or malformed.
pub const BAD_REQUEST: i32 = 400;

/// The target resource was not found.
pub const NOT_FOUND: i32 = 404;

/// An internal server error occurred.
pub const INTERNAL_ERROR: i32 = 500;
