apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Asset
metadata:
  name: my-rest-thermostat-asset1
  namespace: azure-iot-operations
spec:
  #attributes: # This part of the spec is currently broken in the operator. Re-enable later
    #assetId: my-rest-thermostat-asset1
    #assetType: rest-thermostat-asset
  datasets:
    - name: thermostat_status
      dataPoints:
        - dataSource: /api/thermostat/current
          name: currentTemperature
          dataPointConfiguration: |-
           {
              "HttpRequestMethod": "GET",
           }
        - dataSource: /api/thermostat/desired
          name: desiredTemperature
          dataPointConfiguration: |-
           {
              "HttpRequestMethod": "GET",
           }
      dataSource: /thermostat
      destinations:
        - configuration:
            topic: /mqtt/machine/asset1/status
          target: Mqtt
        - configuration:
            key: RestThermostatKey
          target: BrokerStateStore
  deviceRef:
    deviceName: my-rest-thermostat-device-name
    endpointName: my-rest-thermostat-endpoint-name
  version: 1