apiVersion: v1
kind: Secret
metadata:
  name: rest-server-auth-credentials
type: Opaque
data:
  username: c29tZS11c2VybmFtZQ== # "some-username"
  password: c29tZS1wYXNzd29yZA== # "some-password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server-deployment
  labels:
    app: rest-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server-deployment
  template:
    metadata:
      labels:
        app: rest-server-deployment
    spec:
      containers:
      - name: rest-test-server
        image: mcr.microsoft.com/azureiotoperations/rest-test-server:0.4.0
        ports:
        - containerPort: 8080
          name: http-anon
          protocol: TCP
        - containerPort: 8081
          name: http-basic
          protocol: TCP
        - containerPort: 8443
          name: https-anon
          protocol: TCP
        - containerPort: 8444
          name: https-basic
          protocol: TCP
        - containerPort: 8445
          name: https-mtls
          protocol: TCP
        env:
        - name: TLS_CERT_PATH
          value: /secrets/server/server.crt
        - name: TLS_KEY_PATH
          value: /secrets/server/server.key
        - name: TLS_CA_PATH
          value: /secrets/ca/ca.crt
        - name: TLS_INTERMEDIATE_PATH
          value: /secrets/intermediate/intermediate.crt
        - name: AUTH_USERNAME_PATH
          value: /secrets/auth/username
        - name: AUTH_PASSWORD_PATH
          value: /secrets/auth/password
        volumeMounts:
        - name: root-ca-cert
          mountPath: /secrets/ca
          readOnly: true
        - name: intermediate-cert
          mountPath: /secrets/intermediate
          readOnly: true
        - name: server-cert-and-key
          mountPath: /secrets/server
          readOnly: true
        - name: auth-secret
          mountPath: /secrets/auth
          readOnly: true
      volumes:
        - name: root-ca-cert
          secret:
            secretName: rest-test-server-root-ca
            items:
            - key: tls.crt
              path: ca.crt
        - name: intermediate-cert
          secret:
            secretName: rest-test-server-intermediate-cert
            items:
            - key: tls.crt
              path: intermediate.crt
        - name: server-cert-and-key
          secret:
            secretName: rest-test-server-application-cert
            items:
            - key: tls.crt
              path: server.crt
            - key: tls.key
              path: server.key
        - name: auth-secret
          secret:
            secretName: rest-test-server-auth-creds
            items:
            - key: usernameKey
              path: username
            - key: passwordKey
              path: password
      serviceAccountName: rest-test-server-service-account
---
apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
  labels:
    app: rest-server-deployment
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: rest-server-deployment
