apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Device
metadata:
  name: my-thermostat
  namespace: azure-iot-operations
spec:
  attributes:
    deviceId: my-thermostat
    deviceType: thermostat
  enabled: true
  endpoints:
    inbound:
      my-rest-endpoint:
        additionalConfiguration: ''
        address: http://rest-server-service.azure-iot-operations.svc.cluster.local:80
        authentication:
          method: UsernamePassword
          usernamePasswordCredentials:
            usernameSecretName: rest-server-auth-creds/username
            passwordSecretName: rest-server-auth-creds/password
        endpointType: rest-thermostat
  uuid: 1234-5678-9012-3456
  version: 2