apiVersion: v1
kind: Secret
metadata:
  name: rest-server-auth-credentials
type: Opaque
data:
  username: c29tZS11c2VybmFtZQ== # "some-username"
  password: c29tZS1wYXNzd29yZA== # "some-password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server-deployment
  labels:
    app: rest-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server-deployment
  template:
    metadata:
      labels:
        app: rest-server-deployment
    spec:
      containers:
        - name: rest-server-deployment
          image: ${SERVER_IMAGE_NAME}
          ports:
          - containerPort: 8080
            name: http-anon
            protocol: TCP
          - containerPort: 8081
            name: http-basic
            protocol: TCP
          - containerPort: 8443
            name: https-anon
            protocol: TCP
          - containerPort: 8444
            name: https-basic
            protocol: TCP
          - containerPort: 8445
            name: https-mtls
            protocol: TCP
          env:
            - name: SERVICE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rest-server-auth-credentials
                  key: username
            - name: SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rest-server-auth-credentials
                  key: password
            - name: TLS_CERT_PATH
              value: /secrets/server/server.crt
            - name: TLS_KEY_PATH
              value: /secrets/server/server.key
            - name: TLS_CA_PATH
              value: /secrets/ca/ca.crt
            - name: TLS_INTERMEDIATE_PATH
              value: /secrets/intermediate/intermediate.crt
            - name: AUTH_USERNAME_PATH
              value: /secrets/auth/username
            - name: AUTH_PASSWORD_PATH
              value: /secrets/auth/password
          volumeMounts:
          - name: root-ca-cert
            mountPath: /secrets/ca
            readOnly: true
          - name: intermediate-cert
            mountPath: /secrets/intermediate
            readOnly: true
          - name: server-cert-and-key
            mountPath: /secrets/server
            readOnly: true
          - name: auth-secret
            mountPath: /secrets/auth
            readOnly: true
      volumes:
        - name: root-ca-cert
          secret:
            secretName: rest-server-root-ca
            items:
            - key: tls.crt
              path: ca.crt
        - name: intermediate-cert
          secret:
            secretName: rest-server-intermediate-cert
            items:
            - key: tls.crt
              path: intermediate.crt
        - name: server-cert-and-key
          secret:
            secretName: rest-server-application-cert
            items:
            - key: tls.crt
              path: server.crt
            - key: tls.key
              path: server.key
        - name: auth-secret
          secret:
            secretName: rest-server-auth-credentials
            items:
            - key: username
              path: username
            - key: password
              path: password
---
apiVersion: v1
kind: Service
metadata:
  name: rest-server-service
  labels:
    app: rest-server-deployment
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: http-anon
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-basic
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: https-anon
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: https-basic
      port: 8444
      targetPort: 8444
      protocol: TCP
    - name: https-mtls
      port: 8445
      targetPort: 8445
      protocol: TCP
  selector:
    app: rest-server-deployment
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rest-server-self-signed-issuer
  labels:
    app: rest-server-deployment
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rest-server-root-ca
  labels:
    app: rest-server-deployment
spec:
  secretName: rest-server-root-ca
  duration: 8760h # 1 year
  renewBefore: 720h # 30d
  issuerRef:
    name: rest-server-self-signed-issuer
    kind: Issuer
  commonName: "Rest Server Root CA"
  usages:
    - digital signature
    - key encipherment
    - cert sign
    - crl sign
  privateKey:
    encoding: PKCS8
    algorithm: ECDSA
    size: 521
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rest-server-root-ca-issuer
  labels:
    app: rest-server-deployment
spec:
  ca:
    secretName: rest-server-root-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rest-server-intermediate-cert
  labels:
    app: rest-server-deployment
spec:
  secretName: rest-server-intermediate-cert
  duration: 4380h # 6 months
  renewBefore: 360h # 15d
  issuerRef:
    name: rest-server-root-ca-issuer
    kind: Issuer
  commonName: "Rest Server Intermediate CA"
  usages:
    - digital signature
    - key encipherment
    - cert sign
    - crl sign
  privateKey:
    encoding: PKCS8
    algorithm: ECDSA
    size: 521
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rest-server-intermediate-issuer
  labels:
    app: rest-server-deployment
spec:
  ca:
    secretName: rest-server-intermediate-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rest-server-application-cert
  labels:
    app: rest-server-deployment
spec:
  secretName: rest-server-application-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: rest-server-intermediate-issuer
    kind: Issuer
  commonName: RestServer
  dnsNames:
    - rest-server-service
    - rest-server-service.azure-iot-operations.svc.cluster.local
    - rest-server-service.azure-iot-operations
  uris:
    - urn:RestServer:rest-server-service
  usages:
    - digital signature
    - key encipherment
    - data encipherment
    - server auth
    - client auth
  privateKey:
    encoding: PKCS8
    algorithm: ECDSA
    size: 521
  encodeUsagesInRequest: true
  isCA: false
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rest-server-client-cert
  labels:
    app: rest-server-deployment
spec:
  secretName: rest-server-client-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: rest-server-intermediate-issuer
    kind: Issuer
  commonName: "Rest Server Client"
  dnsNames:
    - client
    - rest-client
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    encoding: PKCS8
    algorithm: ECDSA
    size: 521
  isCA: false
