apiVersion: namespaces.deviceregistry.microsoft.com/v1
kind: Asset
metadata:
  name: my-rest-thermostat-asset2
  namespace: azure-iot-operations
spec:
  uuid: 223e4567-e89b-12d3-a456-426614174222
  attributes:
    assetId: my-rest-thermostat-asset2
    assetType: rest-thermostat-asset
  datasets:
    - name: weather-sensor-dataset
      dataSource: /api/sensor/env # The relative HTTP server path to GET data from
      destinations:
        - configuration:
            key: RestThermostatKey # The key to save this sampled information to in the broker state store
          target: BrokerStateStore
  deviceRef:
    deviceName: my-rest-thermostat-device-name
    endpointName: my-rest-thermostat-endpoint-name
  version: 1