// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package rawmodel

import (
	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type RawModelService struct {
	protocol.Listeners
	*TelemetrySender
}

const (
	TelemetryTopic = "test/RawModel/{senderId}/telemetry"
)

func NewRawModelService(
	app *protocol.Application,
	client protocol.MqttClient,
	opts ...protocol.Option,
) (*RawModelService, error) {
	var err error

	serverOpts := []protocol.Option{
		protocol.WithTopicTokenNamespace("ex:"),
		protocol.WithTopicTokens{
			"senderId":   client.ID(),
		},
	}

	var senderOpts protocol.TelemetrySenderOptions
	senderOpts.ApplyOptions(opts, serverOpts...)

	rawModelService := &RawModelService{}

	rawModelService.TelemetrySender, err = NewTelemetrySender(
		app,
		client,
		TelemetryTopic,
		&senderOpts,
	)
	if err != nil {
		rawModelService.Close()
		return nil, err
	}

	return rawModelService, nil
}
