/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */
#![allow(non_snake_case)]

mod enum_proximity;
mod object_schedule;
mod telemetry_collection;
mod telemetry_collection_receiver;
mod telemetry_collection_sender;
mod telemetry_collection_serialization;

pub use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;

pub use super::common_types::common_options::{CommandOptions, TelemetryOptions};

pub const MODEL_ID: &str = "dtmi:codegen:communicationTest:jsonModel;1";
pub const TELEMETRY_TOPIC_PATTERN: &str = "test/JsonModel/{senderId}/telemetry";

pub mod client {
    pub use super::enum_proximity::*;
    pub use super::object_schedule::*;
    pub use super::telemetry_collection::*;
    pub use super::telemetry_collection_receiver::*;
}

pub mod service {
    pub use super::enum_proximity::*;
    pub use super::object_schedule::*;
    pub use super::telemetry_collection::*;
    pub use super::telemetry_collection_sender::*;
}
