/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum AssetDataPointObservabilityModeSchema {
    #[serde(rename = "Counter")]
    Counter,
    #[serde(rename = "Gauge")]
    Gauge,
    #[serde(rename = "Histogram")]
    Histogram,
    #[serde(rename = "Log")]
    Log,
    #[serde(rename = "None")]
    None,
}
