/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::datasets_schema_schema_element_schema::DatasetsSchemaSchemaElementSchema;
use super::error::Error;
use super::events_schema_schema_element_schema::EventsSchemaSchemaElementSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct AssetStatus {
    /// The 'datasetsSchema' Field.
    #[serde(rename = "datasetsSchema")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub datasets_schema: Option<Vec<DatasetsSchemaSchemaElementSchema>>,

    /// The 'errors' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub errors: Option<Vec<Error>>,

    /// The 'eventsSchema' Field.
    #[serde(rename = "eventsSchema")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub events_schema: Option<Vec<EventsSchemaSchemaElementSchema>>,

    /// The 'version' Field.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub version: Option<i32>,
}
