// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package jsonmodel

import (
	"github.com/Azure/iot-operations-sdks/go/protocol/iso"
)

type ScheduleSchema struct {
	Course *string `json:"course,omitempty"`
	Credit *iso.Duration `json:"credit,omitempty"`
}
