apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-service-deployment
  labels:
    app: tcp-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-service-deployment
  template:
    metadata:
      labels:
        app: tcp-service-deployment
    spec:
      containers:
      - name: tcp-service-deployment
        image: sampletcpserviceapp:latest
        imagePullPolicy: Never # This forces docker to use the locally built image
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-service
  labels:
    app: tcp-service-deployment
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tcp-service-deployment
