// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_codegen_communicationTest_jsonModel__1

import (
	"github.com/Azure/iot-operations-sdks/go/protocol/iso"
)

type Object_Schedule struct {
	Course *string `json:"course,omitempty"`
	Credit *iso.Duration `json:"credit,omitempty"`
}
