/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace SemanticDataServer.FirstModel
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using SemanticDataServer;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class ArmPositionSchema
    {
        /// <summary>
        /// The 'x' Field.
        /// </summary>
        [JsonPropertyName("x")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public double X { get; set; } = default!;

        /// <summary>
        /// The 'y' Field.
        /// </summary>
        [JsonPropertyName("y")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public double Y { get; set; } = default!;

    }
}
