/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace SemanticDataServer.FirstModel
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using SemanticDataServer;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class StatusTelemetry
    {
        /// <summary>
        /// The 'Status' Telemetry.
        /// </summary>
        [JsonPropertyName("Status")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public StatusSchema Status { get; set; } = default!;

    }
}
