// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_codegen_communicationTest_jsonModel__1

import (
	"github.com/Azure/iot-operations-sdks/go/protocol"
)

type JsonModelClient struct {
	protocol.Listeners
	*TelemetryCollectionReceiver
}

const (
	TelemetryTopic = "test/JsonModel/{senderId}/telemetry"
)

func NewJsonModelClient(
	client protocol.MqttClient,
	telemetryHandler protocol.TelemetryHandler[TelemetryCollection],
	opts ...protocol.Option,
) (*JsonModelClient, error) {
	var err error

	clientOpts := []protocol.Option{
		protocol.WithTopicTokenNamespace("ex:"),
		protocol.WithTopicTokens{
		},
	}

	var receiverOpts protocol.TelemetryReceiverOptions
	receiverOpts.ApplyOptions(opts, clientOpts...)

	jsonModelClient := &JsonModelClient{}

	jsonModelClient.TelemetryCollectionReceiver, err = NewTelemetryCollectionReceiver(
		client,
		TelemetryTopic,
		telemetryHandler,
		&receiverOpts,
	)
	if err != nil {
		jsonModelClient.Close()
		return nil, err
	}
	jsonModelClient.Listeners = append(jsonModelClient.Listeners, jsonModelClient.TelemetryCollectionReceiver)

	return jsonModelClient, nil
}
