/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */

#nullable enable

namespace AvroComm.dtmi_codegen_communicationTest_avroModel__1
{
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.6.0.0")]
    public enum Enum_Proximity
    {
        near,
        far,
    }
}
