/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */

#nullable enable

namespace AvroComm.dtmi_codegen_communicationTest_avroModel__1
{
    using System;
    using System.Collections.Generic;
    using Avro;
    using Avro.Specific;
    using AvroComm;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.6.0.0")]
    public class TelemetryCollectionBase
    {
        public virtual Schema Schema { get => Schema.Parse(@"{""namespace"":""AvroComm.dtmi_codegen_communicationTest_avroModel__1"",""name"":""TelemetryCollection"",""type"":""record"",""fields"":[]}"); }
    }

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.6.0.0")]
    public partial class TelemetryCollection : TelemetryCollectionBase, ISpecificRecord
    {
        public List<double>? Lengths { get; set; } = default;

        public Enum_Proximity? Proximity { get; set; } = default;

        public Object_Schedule? Schedule { get; set; } = default;

        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.Lengths!;
                case 1: return this.Proximity!;
                case 2: return this.Schedule!;
                default: throw new Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }

        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.Lengths = (List<double>?)fieldValue; break;
                case 1: this.Proximity = (Enum_Proximity?)(int?)fieldValue; break;
                case 2: this.Schedule = (Object_Schedule?)fieldValue; break;
                default: throw new Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }
    }
}
