// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_example_Complex__1

type GetTemperaturesRequestPayload struct {
	Request Object_GetTemperatures_Request `json:"request"`
}
