// Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT.
package dtmi_example_Complex__1

type Object_GetTemperatures_Response_ElementSchema struct {
	City *string `json:"city,omitempty"`
	Result *Enum_Test_Result__1 `json:"result,omitempty"`
	Temperature *float64 `json:"temperature,omitempty"`
}
