/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */
#![allow(non_camel_case_types)]
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::object_get_temperatures_request::Object_GetTemperatures_Request;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct GetTemperaturesRequestPayload {
    /// The Command request argument.
    pub request: Object_GetTemperatures_Request,
}
