/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace SemanticDataClient.FirstModel
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.Telemetry;
    using Azure.Iot.Operations.Protocol.Models;
    using SemanticDataClient;

    public static partial class FirstModel
    {
        /// <summary>
        /// Specializes the <c>TelemetryReceiver</c> class for type <c>ArmPositionTelemetry</c>.
        /// </summary>
        public class ArmPositionTelemetryReceiver : TelemetryReceiver<ArmPositionTelemetry>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="ArmPositionTelemetryReceiver"/> class.
            /// </summary>
            public ArmPositionTelemetryReceiver(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, new Utf8JsonSerializer())
            {
                TopicTokenMap["modelId"] = "dtmi:SemanticDataModel:FirstModel;1";
                TopicTokenMap["telemetryName"] = "ArmPosition";
            }
        }
    }
}
