/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace SemanticDataClient.FirstModel
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using SemanticDataClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class ArmPositionTelemetry : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'ArmPosition' Telemetry.
        /// </summary>
        [JsonPropertyName("ArmPosition")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public ArmPositionSchema ArmPosition { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (ArmPosition is null)
            {
                throw new ArgumentNullException("ArmPosition field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (ArmPosition is null)
            {
                throw new ArgumentNullException("ArmPosition field cannot be null");
            }
        }
    }
}
