/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace SemanticDataClient.FirstModel
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using SemanticDataClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class ModeTelemetry : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'Mode' Telemetry.
        /// </summary>
        [JsonPropertyName("Mode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Mode { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Mode is null)
            {
                throw new ArgumentNullException("Mode field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Mode is null)
            {
                throw new ArgumentNullException("Mode field cannot be null");
            }
        }
    }
}
