apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Asset
metadata:
  name: my-tcp-thermostat-asset
  namespace: azure-iot-operations
spec:
  attributes:
    assetId: my-tcp-thermostat-asset
    assetType: thermostat
    eventGroups:
      - name: my-event-group  
        events:
          - name: thermostat_status_changed
            destinations:
              - configuration:
                  topic: /mqtt/machine/status/change_event
                target: Mqtt
            dataSource: "80"
  defaultDatasetsConfiguration: '{}'
  deviceRef:
    deviceName: my-tcp-thermostat
    endpointName: my_tcp_endpoint
  version: 1