apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Asset
metadata:
  name: my-tcp-thermostat-asset
  namespace: azure-iot-operations
spec:
  #attributes: # This part of the spec is currently broken in the operator. Re-enable later
  #  assetId: my-tcp-thermostat-asset
  #  assetType: thermostat
  events:
    - name: thermostat_status_changed
      dataPoints:
        - dataSource: /api/thermostat/current
          name: currentTemperature
          dataPointConfiguration: ''
      destinations:
        - configuration:
            topic: /mqtt/machine/status/change_event
          target: Mqtt
      eventNotifier: todo
  defaultDatasetsConfiguration: ''
  deviceRef:
    deviceName: my-tcp-thermostat
    endpointName: my-tcp-endpoint
  version: 1