apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Asset
metadata:
  name: my-tcp-thermostat-asset
  namespace: azure-iot-operations
spec:
  attributes:
    assetId: my-tcp-thermostat-asset
    assetType: thermostat
  events:
    - name: thermostat_status_changed
      dataPoints:
        - dataSource: /api/thermostat/current
          name: currentTemperature
          dataPointConfiguration: ''
      dataSource: /thermostat
      destinations:
        # TODO: currently unsupported by CRDs, but will add support for it soon?
        #- configuration:
        #    topic: /mqtt/machine/status/change_event
        #  target: Mqtt
        - configuration:
            key: thermostat_current_temperature
          target: BrokerStateStore
  defaultDatasetsConfiguration: ''
  deviceRef:
    deviceName: my-tcp-thermostat
    endpointName: my-tcp-endpoint
  version: 1