/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::create_or_update_discovered_asset_request_schema::CreateOrUpdateDiscoveredAssetRequestSchema;

/// The request to create or update a discovered asset.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct CreateOrUpdateDiscoveredAssetRequestPayload {
    /// The 'discoveredAssetRequest' Field.
    #[serde(rename = "discoveredAssetRequest")]
    pub discovered_asset_request: CreateOrUpdateDiscoveredAssetRequestSchema,
}
