/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::config_status_update::ConfigStatusUpdate;
use super::device_status_update_endpoint_schema::DeviceStatusUpdateEndpointSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct DeviceStatusUpdate {
    /// The configuration status of the device.
    pub config: ConfigStatusUpdate,

    /// Defines the device status for inbound/outbound endpoints.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub endpoints: Option<DeviceStatusUpdateEndpointSchema>,
}
