/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::event_runtime_health_event_schema::EventRuntimeHealthEventSchema;

/// Telemetry event emitted for reporting the runtime health of events.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct EventRuntimeHealthEventTelemetry {
    /// Telemetry event emitted for reporting the runtime health of events.
    #[serde(rename = "eventRuntimeHealthEvent")]
    pub event_runtime_health_event: EventRuntimeHealthEventSchema,
}
