/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::akri_service_error::AkriServiceError;
use super::device_status::DeviceStatus;

/// Response containing the device status or error details if the status could not be retrieved.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct GetDeviceStatusResponseSchema {
    /// The device status, containing the specific inbound endpoint status as specified by the request.
    #[serde(rename = "deviceStatus")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub device_status: Option<DeviceStatus>,

    /// Read error for the 'getDeviceStatus' Action.
    #[serde(rename = "getDeviceStatusError")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub get_device_status_error: Option<AkriServiceError>,
}
