/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

/// The MQTT QoS setting.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum Qos {
    Qos0,
    Qos1,
}
