/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use serde::{Deserialize, Serialize};

/// The current health status of the resource.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum StatusSchema {
    Available,
    Unavailable,
}
