/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::streams_schema_element_schema::StreamsSchemaElementSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct StreamRuntimeHealthEventSchema {
    /// The name of the asset containing the streams for which the runtime health is being reported.
    #[serde(rename = "assetName")]
    pub asset_name: String,

    /// Array of stream runtime health information.
    #[builder(default)]
    pub streams: Vec<StreamsSchemaElementSchema>,
}
