/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::runtime_health::RuntimeHealth;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct StreamsSchemaElementSchema {
    /// The runtime health of the specific stream.
    #[serde(rename = "runtimeHealth")]
    pub runtime_health: RuntimeHealth,

    /// The name of the stream for which the runtime health is being reported.
    #[serde(rename = "streamName")]
    pub stream_name: String,
}
