/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::stream_runtime_health_event_schema::StreamRuntimeHealthEventSchema;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct StreamRuntimeHealthEventTelemetry {
    /// Telemetry event emitted for reporting the runtime health of streams.
    #[serde(rename = "streamRuntimeHealthEvent")]
    pub stream_runtime_health_event: StreamRuntimeHealthEventSchema,
}
