name: 'Deploy AIO'
description: 'Deploy AIO for pipelines'

inputs:
  wait-for-broker:
    description: 'Wait for the MQTT broker to start before returning'
    required: false
    default: 'true'

  install-go:
    description: 'Install the Go compiler'
    required: false
    default: 'false'

  install-dotnet:
    description: 'Install the .NET compiler and runtime'
    required: false
    default: 'false'

  install-rust:
    description: 'Install the Rust compiler'
    required: false
    default: 'false'

  action-token:
    description: 'A GitHub PAT'
    required: true

runs:
  using: composite
  steps:
    - name: Create k3s cluster
      run: tools/deployment/initialize-cluster.sh -y
      shell: bash

    - name: Checkout deploy action
      uses: actions/checkout@v4
      with:
        repository: azure/iot-operations-sdks-action
        path: action-deploy
        token: ${{ inputs.action-token }}

    - name: Install AIO
      uses: ./action-deploy
      with:
        akri: 2501

    - name: Configure AIO
      run: tools/deployment/configure-aio.sh
      shell: bash

    - name: Setup .NET
      if: inputs.install-dotnet == 'true'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Setup GO
      if: inputs.install-go == 'true'
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Setup Rust
      if: inputs.install-rust == 'true'
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Wait for Mqtt Broker
      if: inputs.wait-for-broker == 'true'
      run: kubectl wait --for=create pod/aio-broker-frontend-0 --timeout=120s
      shell: bash
