### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.StateStore
  commentId: N:Azure.Iot.Operations.Services.StateStore
  id: StateStore
  parent: Azure.Iot.Operations.Services
  children:
  - Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary`1
  - Azure.Iot.Operations.Services.StateStore.IStateStoreClient
  - Azure.Iot.Operations.Services.StateStore.KeyChangeMessageReceivedEventArgs
  - Azure.Iot.Operations.Services.StateStore.KeyState
  - Azure.Iot.Operations.Services.StateStore.PassthroughSerializer
  - Azure.Iot.Operations.Services.StateStore.ServiceError
  - Azure.Iot.Operations.Services.StateStore.SetCondition
  - Azure.Iot.Operations.Services.StateStore.StateStoreClient
  - Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  - Azure.Iot.Operations.Services.StateStore.StateStoreDeleteResponse
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  - Azure.Iot.Operations.Services.StateStore.StateStoreGetResponse
  - Azure.Iot.Operations.Services.StateStore.StateStoreKey
  - Azure.Iot.Operations.Services.StateStore.StateStoreObject
  - Azure.Iot.Operations.Services.StateStore.StateStoreObserveRequestOptions
  - Azure.Iot.Operations.Services.StateStore.StateStoreOperationException
  - Azure.Iot.Operations.Services.StateStore.StateStoreResponse
  - Azure.Iot.Operations.Services.StateStore.StateStoreSetRequestOptions
  - Azure.Iot.Operations.Services.StateStore.StateStoreSetResponse
  - Azure.Iot.Operations.Services.StateStore.StateStoreValue
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Services.StateStore
  nameWithType: Azure.Iot.Operations.Services.StateStore
  fullName: Azure.Iot.Operations.Services.StateStore
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Services
references:
- uid: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary`1
  commentId: T:Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary`1
  href: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary-1.html
  name: CombinedPrefixedReadOnlyDictionary<TValue>
  nameWithType: CombinedPrefixedReadOnlyDictionary<TValue>
  fullName: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary<TValue>
  nameWithType.vb: CombinedPrefixedReadOnlyDictionary(Of TValue)
  fullName.vb: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary(Of TValue)
  name.vb: CombinedPrefixedReadOnlyDictionary(Of TValue)
  spec.csharp:
  - uid: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary`1
    name: CombinedPrefixedReadOnlyDictionary
    href: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary-1.html
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary`1
    name: CombinedPrefixedReadOnlyDictionary
    href: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: Azure.Iot.Operations.Services.StateStore.IStateStoreClient
  commentId: T:Azure.Iot.Operations.Services.StateStore.IStateStoreClient
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.IStateStoreClient.html
  name: IStateStoreClient
  nameWithType: IStateStoreClient
  fullName: Azure.Iot.Operations.Services.StateStore.IStateStoreClient
- uid: Azure.Iot.Operations.Services.StateStore.KeyChangeMessageReceivedEventArgs
  commentId: T:Azure.Iot.Operations.Services.StateStore.KeyChangeMessageReceivedEventArgs
  href: Azure.Iot.Operations.Services.StateStore.KeyChangeMessageReceivedEventArgs.html
  name: KeyChangeMessageReceivedEventArgs
  nameWithType: KeyChangeMessageReceivedEventArgs
  fullName: Azure.Iot.Operations.Services.StateStore.KeyChangeMessageReceivedEventArgs
- uid: Azure.Iot.Operations.Services.StateStore.KeyState
  commentId: T:Azure.Iot.Operations.Services.StateStore.KeyState
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.KeyState.html
  name: KeyState
  nameWithType: KeyState
  fullName: Azure.Iot.Operations.Services.StateStore.KeyState
- uid: Azure.Iot.Operations.Services.StateStore.PassthroughSerializer
  commentId: T:Azure.Iot.Operations.Services.StateStore.PassthroughSerializer
  href: Azure.Iot.Operations.Services.StateStore.PassthroughSerializer.html
  name: PassthroughSerializer
  nameWithType: PassthroughSerializer
  fullName: Azure.Iot.Operations.Services.StateStore.PassthroughSerializer
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError
  commentId: T:Azure.Iot.Operations.Services.StateStore.ServiceError
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.ServiceError.html
  name: ServiceError
  nameWithType: ServiceError
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.SetCondition
  commentId: T:Azure.Iot.Operations.Services.StateStore.SetCondition
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.SetCondition.html
  name: SetCondition
  nameWithType: SetCondition
  fullName: Azure.Iot.Operations.Services.StateStore.SetCondition
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreClient
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreClient
  href: Azure.Iot.Operations.Services.StateStore.StateStoreClient.html
  name: StateStoreClient
  nameWithType: StateStoreClient
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreClient
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.html
  name: StateStoreDeleteRequestOptions
  nameWithType: StateStoreDeleteRequestOptions
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteResponse
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteResponse
  href: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteResponse.html
  name: StateStoreDeleteResponse
  nameWithType: StateStoreDeleteResponse
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteResponse
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.html
  name: StateStoreErrorKind
  nameWithType: StateStoreErrorKind
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreGetResponse
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreGetResponse
  href: Azure.Iot.Operations.Services.StateStore.StateStoreGetResponse.html
  name: StateStoreGetResponse
  nameWithType: StateStoreGetResponse
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreGetResponse
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreKey
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreKey
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreKey.html
  name: StateStoreKey
  nameWithType: StateStoreKey
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreKey
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreObject
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreObject
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreObject.html
  name: StateStoreObject
  nameWithType: StateStoreObject
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreObject
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreObserveRequestOptions
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreObserveRequestOptions
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreObserveRequestOptions.html
  name: StateStoreObserveRequestOptions
  nameWithType: StateStoreObserveRequestOptions
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreObserveRequestOptions
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreOperationException
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreOperationException
  href: Azure.Iot.Operations.Services.StateStore.StateStoreOperationException.html
  name: StateStoreOperationException
  nameWithType: StateStoreOperationException
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreOperationException
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreResponse
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreResponse
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreResponse.html
  name: StateStoreResponse
  nameWithType: StateStoreResponse
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreResponse
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreSetRequestOptions
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreSetRequestOptions
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreSetRequestOptions.html
  name: StateStoreSetRequestOptions
  nameWithType: StateStoreSetRequestOptions
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreSetRequestOptions
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreSetResponse
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreSetResponse
  href: Azure.Iot.Operations.Services.StateStore.StateStoreSetResponse.html
  name: StateStoreSetResponse
  nameWithType: StateStoreSetResponse
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreSetResponse
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreValue
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreValue
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreValue.html
  name: StateStoreValue
  nameWithType: StateStoreValue
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreValue
- uid: Azure.Iot.Operations.Services.StateStore
  commentId: N:Azure.Iot.Operations.Services.StateStore
  href: Azure.html
  name: Azure.Iot.Operations.Services.StateStore
  nameWithType: Azure.Iot.Operations.Services.StateStore
  fullName: Azure.Iot.Operations.Services.StateStore
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
