### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  id: MqttClientSubscribeReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS0
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS1
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS2
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.ImplementationSpecificError
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.NotAuthorized
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.PacketIdentifierInUse
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.QuotaExceeded
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SharedSubscriptionsNotSupported
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SubscriptionIdentifiersNotSupported
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.TopicFilterInvalid
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.UnspecifiedError
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.WildcardSubscriptionsNotSupported
  langs:
  - csharp
  - vb
  name: MqttClientSubscribeReasonCode
  nameWithType: MqttClientSubscribeReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttClientSubscribeReasonCode
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttClientSubscribeReasonCode
    content.vb: Public Enum MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS0
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS0
  id: GrantedQoS0
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: GrantedQoS0
  nameWithType: MqttClientSubscribeReasonCode.GrantedQoS0
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS0
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GrantedQoS0
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: GrantedQoS0 = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS1
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS1
  id: GrantedQoS1
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: GrantedQoS1
  nameWithType: MqttClientSubscribeReasonCode.GrantedQoS1
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS1
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GrantedQoS1
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: GrantedQoS1 = 1
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS2
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS2
  id: GrantedQoS2
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: GrantedQoS2
  nameWithType: MqttClientSubscribeReasonCode.GrantedQoS2
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.GrantedQoS2
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GrantedQoS2
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: GrantedQoS2 = 2
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.UnspecifiedError
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.UnspecifiedError
  id: UnspecifiedError
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: UnspecifiedError
  nameWithType: MqttClientSubscribeReasonCode.UnspecifiedError
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.UnspecifiedError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnspecifiedError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: UnspecifiedError = 128
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.ImplementationSpecificError
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.ImplementationSpecificError
  id: ImplementationSpecificError
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: ImplementationSpecificError
  nameWithType: MqttClientSubscribeReasonCode.ImplementationSpecificError
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.ImplementationSpecificError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ImplementationSpecificError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: ImplementationSpecificError = 131
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.NotAuthorized
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.NotAuthorized
  id: NotAuthorized
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: NotAuthorized
  nameWithType: MqttClientSubscribeReasonCode.NotAuthorized
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.NotAuthorized
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NotAuthorized
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: NotAuthorized = 135
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.TopicFilterInvalid
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.TopicFilterInvalid
  id: TopicFilterInvalid
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: TopicFilterInvalid
  nameWithType: MqttClientSubscribeReasonCode.TopicFilterInvalid
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.TopicFilterInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TopicFilterInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 11
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: TopicFilterInvalid = 143
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.PacketIdentifierInUse
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.PacketIdentifierInUse
  id: PacketIdentifierInUse
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: PacketIdentifierInUse
  nameWithType: MqttClientSubscribeReasonCode.PacketIdentifierInUse
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.PacketIdentifierInUse
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: PacketIdentifierInUse
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 12
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: PacketIdentifierInUse = 145
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.QuotaExceeded
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.QuotaExceeded
  id: QuotaExceeded
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: QuotaExceeded
  nameWithType: MqttClientSubscribeReasonCode.QuotaExceeded
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.QuotaExceeded
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: QuotaExceeded
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 13
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: QuotaExceeded = 151
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SharedSubscriptionsNotSupported
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SharedSubscriptionsNotSupported
  id: SharedSubscriptionsNotSupported
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: SharedSubscriptionsNotSupported
  nameWithType: MqttClientSubscribeReasonCode.SharedSubscriptionsNotSupported
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SharedSubscriptionsNotSupported
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SharedSubscriptionsNotSupported
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 14
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: SharedSubscriptionsNotSupported = 158
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SubscriptionIdentifiersNotSupported
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SubscriptionIdentifiersNotSupported
  id: SubscriptionIdentifiersNotSupported
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: SubscriptionIdentifiersNotSupported
  nameWithType: MqttClientSubscribeReasonCode.SubscriptionIdentifiersNotSupported
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.SubscriptionIdentifiersNotSupported
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SubscriptionIdentifiersNotSupported
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 15
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: SubscriptionIdentifiersNotSupported = 161
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.WildcardSubscriptionsNotSupported
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.WildcardSubscriptionsNotSupported
  id: WildcardSubscriptionsNotSupported
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  langs:
  - csharp
  - vb
  name: WildcardSubscriptionsNotSupported
  nameWithType: MqttClientSubscribeReasonCode.WildcardSubscriptionsNotSupported
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.WildcardSubscriptionsNotSupported
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: WildcardSubscriptionsNotSupported
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeReasonCode.cs
    startLine: 16
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: WildcardSubscriptionsNotSupported = 162
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.html
  name: MqttClientSubscribeReasonCode
  nameWithType: MqttClientSubscribeReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
