### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  id: Protocol
  parent: Azure.Iot.Operations
  children:
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  - Azure.Iot.Operations.Protocol.AkriMqttException
  - Azure.Iot.Operations.Protocol.AkriSystemProperties
  - Azure.Iot.Operations.Protocol.CommandBehaviorAttribute
  - Azure.Iot.Operations.Protocol.CommandTopicAttribute
  - Azure.Iot.Operations.Protocol.Connection
  - Azure.Iot.Operations.Protocol.Events
  - Azure.Iot.Operations.Protocol.GuidExtensions
  - Azure.Iot.Operations.Protocol.HybridLogicalClock
  - Azure.Iot.Operations.Protocol.HybridLogicalClockException
  - Azure.Iot.Operations.Protocol.IDelayableQueueItem
  - Azure.Iot.Operations.Protocol.IMqttClient
  - Azure.Iot.Operations.Protocol.IMqttPubSubClient
  - Azure.Iot.Operations.Protocol.IPayloadSerializer
  - Azure.Iot.Operations.Protocol.IWallClock
  - Azure.Iot.Operations.Protocol.ModelIdAttribute
  - Azure.Iot.Operations.Protocol.Models
  - Azure.Iot.Operations.Protocol.PatternValidity
  - Azure.Iot.Operations.Protocol.RPC
  - Azure.Iot.Operations.Protocol.Retry
  - Azure.Iot.Operations.Protocol.ServiceGroupIdAttribute
  - Azure.Iot.Operations.Protocol.Telemetry
  - Azure.Iot.Operations.Protocol.TelemetryTopicAttribute
  - Azure.Iot.Operations.Protocol.WallClock
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Protocol
references:
- uid: Azure.Iot.Operations.Protocol.Connection
  commentId: N:Azure.Iot.Operations.Protocol.Connection
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Connection
  nameWithType: Azure.Iot.Operations.Protocol.Connection
  fullName: Azure.Iot.Operations.Protocol.Connection
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Connection
    name: Connection
    href: Azure.Iot.Operations.Protocol.Connection.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Connection
    name: Connection
    href: Azure.Iot.Operations.Protocol.Connection.html
- uid: Azure.Iot.Operations.Protocol.Events
  commentId: N:Azure.Iot.Operations.Protocol.Events
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Events
  nameWithType: Azure.Iot.Operations.Protocol.Events
  fullName: Azure.Iot.Operations.Protocol.Events
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Events
    name: Events
    href: Azure.Iot.Operations.Protocol.Events.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Events
    name: Events
    href: Azure.Iot.Operations.Protocol.Events.html
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.RPC
  commentId: N:Azure.Iot.Operations.Protocol.RPC
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.RPC
  nameWithType: Azure.Iot.Operations.Protocol.RPC
  fullName: Azure.Iot.Operations.Protocol.RPC
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.RPC
    name: RPC
    href: Azure.Iot.Operations.Protocol.RPC.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.RPC
    name: RPC
    href: Azure.Iot.Operations.Protocol.RPC.html
- uid: Azure.Iot.Operations.Protocol.Retry
  commentId: N:Azure.Iot.Operations.Protocol.Retry
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Retry
  nameWithType: Azure.Iot.Operations.Protocol.Retry
  fullName: Azure.Iot.Operations.Protocol.Retry
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Retry
    name: Retry
    href: Azure.Iot.Operations.Protocol.Retry.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Retry
    name: Retry
    href: Azure.Iot.Operations.Protocol.Retry.html
- uid: Azure.Iot.Operations.Protocol.Telemetry
  commentId: N:Azure.Iot.Operations.Protocol.Telemetry
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Telemetry
  nameWithType: Azure.Iot.Operations.Protocol.Telemetry
  fullName: Azure.Iot.Operations.Protocol.Telemetry
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Telemetry
    name: Telemetry
    href: Azure.Iot.Operations.Protocol.Telemetry.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Telemetry
    name: Telemetry
    href: Azure.Iot.Operations.Protocol.Telemetry.html
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  commentId: T:Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.html
  name: AkriMqttErrorKind
  nameWithType: AkriMqttErrorKind
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttException
  commentId: T:Azure.Iot.Operations.Protocol.AkriMqttException
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.AkriMqttException.html
  name: AkriMqttException
  nameWithType: AkriMqttException
  fullName: Azure.Iot.Operations.Protocol.AkriMqttException
- uid: Azure.Iot.Operations.Protocol.AkriSystemProperties
  commentId: T:Azure.Iot.Operations.Protocol.AkriSystemProperties
  href: Azure.Iot.Operations.Protocol.AkriSystemProperties.html
  name: AkriSystemProperties
  nameWithType: AkriSystemProperties
  fullName: Azure.Iot.Operations.Protocol.AkriSystemProperties
- uid: Azure.Iot.Operations.Protocol.CommandBehaviorAttribute
  commentId: T:Azure.Iot.Operations.Protocol.CommandBehaviorAttribute
  href: Azure.Iot.Operations.Protocol.CommandBehaviorAttribute.html
  name: CommandBehaviorAttribute
  nameWithType: CommandBehaviorAttribute
  fullName: Azure.Iot.Operations.Protocol.CommandBehaviorAttribute
- uid: Azure.Iot.Operations.Protocol.CommandTopicAttribute
  commentId: T:Azure.Iot.Operations.Protocol.CommandTopicAttribute
  href: Azure.Iot.Operations.Protocol.CommandTopicAttribute.html
  name: CommandTopicAttribute
  nameWithType: CommandTopicAttribute
  fullName: Azure.Iot.Operations.Protocol.CommandTopicAttribute
- uid: Azure.Iot.Operations.Protocol.GuidExtensions
  commentId: T:Azure.Iot.Operations.Protocol.GuidExtensions
  href: Azure.Iot.Operations.Protocol.GuidExtensions.html
  name: GuidExtensions
  nameWithType: GuidExtensions
  fullName: Azure.Iot.Operations.Protocol.GuidExtensions
- uid: Azure.Iot.Operations.Protocol.HybridLogicalClock
  commentId: T:Azure.Iot.Operations.Protocol.HybridLogicalClock
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.HybridLogicalClock.html
  name: HybridLogicalClock
  nameWithType: HybridLogicalClock
  fullName: Azure.Iot.Operations.Protocol.HybridLogicalClock
- uid: Azure.Iot.Operations.Protocol.HybridLogicalClockException
  commentId: T:Azure.Iot.Operations.Protocol.HybridLogicalClockException
  href: Azure.Iot.Operations.Protocol.HybridLogicalClockException.html
  name: HybridLogicalClockException
  nameWithType: HybridLogicalClockException
  fullName: Azure.Iot.Operations.Protocol.HybridLogicalClockException
- uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem
  commentId: T:Azure.Iot.Operations.Protocol.IDelayableQueueItem
  href: Azure.Iot.Operations.Protocol.IDelayableQueueItem.html
  name: IDelayableQueueItem
  nameWithType: IDelayableQueueItem
  fullName: Azure.Iot.Operations.Protocol.IDelayableQueueItem
- uid: Azure.Iot.Operations.Protocol.IMqttClient
  commentId: T:Azure.Iot.Operations.Protocol.IMqttClient
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.IMqttClient.html
  name: IMqttClient
  nameWithType: IMqttClient
  fullName: Azure.Iot.Operations.Protocol.IMqttClient
- uid: Azure.Iot.Operations.Protocol.IMqttPubSubClient
  commentId: T:Azure.Iot.Operations.Protocol.IMqttPubSubClient
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.IMqttPubSubClient.html
  name: IMqttPubSubClient
  nameWithType: IMqttPubSubClient
  fullName: Azure.Iot.Operations.Protocol.IMqttPubSubClient
- uid: Azure.Iot.Operations.Protocol.IPayloadSerializer
  commentId: T:Azure.Iot.Operations.Protocol.IPayloadSerializer
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.IPayloadSerializer.html
  name: IPayloadSerializer
  nameWithType: IPayloadSerializer
  fullName: Azure.Iot.Operations.Protocol.IPayloadSerializer
- uid: Azure.Iot.Operations.Protocol.IWallClock
  commentId: T:Azure.Iot.Operations.Protocol.IWallClock
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.IWallClock.html
  name: IWallClock
  nameWithType: IWallClock
  fullName: Azure.Iot.Operations.Protocol.IWallClock
- uid: Azure.Iot.Operations.Protocol.ModelIdAttribute
  commentId: T:Azure.Iot.Operations.Protocol.ModelIdAttribute
  href: Azure.Iot.Operations.Protocol.ModelIdAttribute.html
  name: ModelIdAttribute
  nameWithType: ModelIdAttribute
  fullName: Azure.Iot.Operations.Protocol.ModelIdAttribute
- uid: Azure.Iot.Operations.Protocol.PatternValidity
  commentId: T:Azure.Iot.Operations.Protocol.PatternValidity
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.PatternValidity.html
  name: PatternValidity
  nameWithType: PatternValidity
  fullName: Azure.Iot.Operations.Protocol.PatternValidity
- uid: Azure.Iot.Operations.Protocol.ServiceGroupIdAttribute
  commentId: T:Azure.Iot.Operations.Protocol.ServiceGroupIdAttribute
  href: Azure.Iot.Operations.Protocol.ServiceGroupIdAttribute.html
  name: ServiceGroupIdAttribute
  nameWithType: ServiceGroupIdAttribute
  fullName: Azure.Iot.Operations.Protocol.ServiceGroupIdAttribute
- uid: Azure.Iot.Operations.Protocol.TelemetryTopicAttribute
  commentId: T:Azure.Iot.Operations.Protocol.TelemetryTopicAttribute
  href: Azure.Iot.Operations.Protocol.TelemetryTopicAttribute.html
  name: TelemetryTopicAttribute
  nameWithType: TelemetryTopicAttribute
  fullName: Azure.Iot.Operations.Protocol.TelemetryTopicAttribute
- uid: Azure.Iot.Operations.Protocol.WallClock
  commentId: T:Azure.Iot.Operations.Protocol.WallClock
  href: Azure.Iot.Operations.Protocol.WallClock.html
  name: WallClock
  nameWithType: WallClock
  fullName: Azure.Iot.Operations.Protocol.WallClock
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
