### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  id: MqttClientPublishReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.ImplementationSpecificError
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NoMatchingSubscribers
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NotAuthorized
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PacketIdentifierInUse
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PayloadFormatInvalid
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.QuotaExceeded
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.Success
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.TopicNameInvalid
  - Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.UnspecifiedError
  langs:
  - csharp
  - vb
  name: MqttClientPublishReasonCode
  nameWithType: MqttClientPublishReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttClientPublishReasonCode
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 3
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttClientPublishReasonCode
    content.vb: Public Enum MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.Success
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.Success
  id: Success
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: Success
  nameWithType: MqttClientPublishReasonCode.Success
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.Success
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Success
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: Success = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NoMatchingSubscribers
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NoMatchingSubscribers
  id: NoMatchingSubscribers
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: NoMatchingSubscribers
  nameWithType: MqttClientPublishReasonCode.NoMatchingSubscribers
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NoMatchingSubscribers
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NoMatchingSubscribers
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: NoMatchingSubscribers = 16
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.UnspecifiedError
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.UnspecifiedError
  id: UnspecifiedError
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: UnspecifiedError
  nameWithType: MqttClientPublishReasonCode.UnspecifiedError
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.UnspecifiedError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnspecifiedError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: UnspecifiedError = 128
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.ImplementationSpecificError
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.ImplementationSpecificError
  id: ImplementationSpecificError
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: ImplementationSpecificError
  nameWithType: MqttClientPublishReasonCode.ImplementationSpecificError
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.ImplementationSpecificError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ImplementationSpecificError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: ImplementationSpecificError = 131
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NotAuthorized
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NotAuthorized
  id: NotAuthorized
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: NotAuthorized
  nameWithType: MqttClientPublishReasonCode.NotAuthorized
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.NotAuthorized
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NotAuthorized
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: NotAuthorized = 135
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.TopicNameInvalid
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.TopicNameInvalid
  id: TopicNameInvalid
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: TopicNameInvalid
  nameWithType: MqttClientPublishReasonCode.TopicNameInvalid
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.TopicNameInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TopicNameInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 11
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: TopicNameInvalid = 144
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PacketIdentifierInUse
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PacketIdentifierInUse
  id: PacketIdentifierInUse
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: PacketIdentifierInUse
  nameWithType: MqttClientPublishReasonCode.PacketIdentifierInUse
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PacketIdentifierInUse
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: PacketIdentifierInUse
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 12
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: PacketIdentifierInUse = 145
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.QuotaExceeded
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.QuotaExceeded
  id: QuotaExceeded
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: QuotaExceeded
  nameWithType: MqttClientPublishReasonCode.QuotaExceeded
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.QuotaExceeded
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: QuotaExceeded
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 13
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: QuotaExceeded = 151
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PayloadFormatInvalid
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PayloadFormatInvalid
  id: PayloadFormatInvalid
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  langs:
  - csharp
  - vb
  name: PayloadFormatInvalid
  nameWithType: MqttClientPublishReasonCode.PayloadFormatInvalid
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.PayloadFormatInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: PayloadFormatInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientPublishReasonCode.cs
    startLine: 14
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: PayloadFormatInvalid = 153
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode.html
  name: MqttClientPublishReasonCode
  nameWithType: MqttClientPublishReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
