### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  id: MqttProtocolVersion
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.Unknown
  - Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V310
  - Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V311
  - Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V500
  langs:
  - csharp
  - vb
  name: MqttProtocolVersion
  nameWithType: MqttProtocolVersion
  fullName: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttProtocolVersion
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
    startLine: 3
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttProtocolVersion
    content.vb: Public Enum MqttProtocolVersion
- uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.Unknown
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.Unknown
  id: Unknown
  parent: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: MqttProtocolVersion.Unknown
  fullName: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.Unknown
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Unknown
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: Unknown = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
- uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V310
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V310
  id: V310
  parent: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  langs:
  - csharp
  - vb
  name: V310
  nameWithType: MqttProtocolVersion.V310
  fullName: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V310
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: V310
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: V310 = 3
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
- uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V311
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V311
  id: V311
  parent: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  langs:
  - csharp
  - vb
  name: V311
  nameWithType: MqttProtocolVersion.V311
  fullName: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V311
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: V311
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: V311 = 4
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
- uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V500
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V500
  id: V500
  parent: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  langs:
  - csharp
  - vb
  name: V500
  nameWithType: MqttProtocolVersion.V500
  fullName: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.V500
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: V500
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttProtocolVersion.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: V500 = 5
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion.html
  name: MqttProtocolVersion
  nameWithType: MqttProtocolVersion
  fullName: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
