### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  id: StateStoreDeleteRequestOptions
  parent: Azure.Iot.Operations.Services.StateStore
  children:
  - Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken
  - Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  langs:
  - csharp
  - vb
  name: StateStoreDeleteRequestOptions
  nameWithType: StateStoreDeleteRequestOptions
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteRequestOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: StateStoreDeleteRequestOptions
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteRequestOptions.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  summary: The optional parameters for a Delete request.
  example: []
  syntax:
    content: public class StateStoreDeleteRequestOptions
    content.vb: Public Class StateStoreDeleteRequestOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  commentId: P:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  id: OnlyDeleteIfValueEquals
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  langs:
  - csharp
  - vb
  name: OnlyDeleteIfValueEquals
  nameWithType: StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteRequestOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: OnlyDeleteIfValueEquals
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteRequestOptions.cs
    startLine: 13
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  summary: >-
    If provided, the delete operation will only execute if the value in the State Store matches this value.

    If not provided, the delete operation will execute unconditionally.
  example: []
  syntax:
    content: public StateStoreValue? OnlyDeleteIfValueEquals { get; set; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreValue
    content.vb: Public Property OnlyDeleteIfValueEquals As StateStoreValue
  overload: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals*
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken
  commentId: P:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken
  id: FencingToken
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
  langs:
  - csharp
  - vb
  name: FencingToken
  nameWithType: StateStoreDeleteRequestOptions.FencingToken
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteRequestOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: FencingToken
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreDeleteRequestOptions.cs
    startLine: 18
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  summary: The optional fencing token to include in the request.
  example: []
  syntax:
    content: public HybridLogicalClock? FencingToken { get; set; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Protocol.HybridLogicalClock
    content.vb: Public Property FencingToken As HybridLogicalClock
  overload: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken*
references:
- uid: Azure.Iot.Operations.Services.StateStore
  commentId: N:Azure.Iot.Operations.Services.StateStore
  href: Azure.html
  name: Azure.Iot.Operations.Services.StateStore
  nameWithType: Azure.Iot.Operations.Services.StateStore
  fullName: Azure.Iot.Operations.Services.StateStore
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals*
  commentId: Overload:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  href: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.html#Azure_Iot_Operations_Services_StateStore_StateStoreDeleteRequestOptions_OnlyDeleteIfValueEquals
  name: OnlyDeleteIfValueEquals
  nameWithType: StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.OnlyDeleteIfValueEquals
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreValue
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreValue
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreValue.html
  name: StateStoreValue
  nameWithType: StateStoreValue
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreValue
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken*
  commentId: Overload:Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken
  href: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.html#Azure_Iot_Operations_Services_StateStore_StateStoreDeleteRequestOptions_FencingToken
  name: FencingToken
  nameWithType: StateStoreDeleteRequestOptions.FencingToken
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions.FencingToken
- uid: Azure.Iot.Operations.Protocol.HybridLogicalClock
  commentId: T:Azure.Iot.Operations.Protocol.HybridLogicalClock
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.HybridLogicalClock.html
  name: HybridLogicalClock
  nameWithType: HybridLogicalClock
  fullName: Azure.Iot.Operations.Protocol.HybridLogicalClock
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
