### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions
  commentId: T:Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions
  id: IMqttClientChannelOptions
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions
  langs:
  - csharp
  - vb
  name: IMqttClientChannelOptions
  nameWithType: IMqttClientChannelOptions
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientChannelOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IMqttClientChannelOptions
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientChannelOptions.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public interface IMqttClientChannelOptions
    content.vb: Public Interface IMqttClientChannelOptions
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions
  commentId: P:Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions
  id: TlsOptions
  parent: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions
  langs:
  - csharp
  - vb
  name: TlsOptions
  nameWithType: IMqttClientChannelOptions.TlsOptions
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientChannelOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TlsOptions
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientChannelOptions.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: MqttClientTlsOptions TlsOptions { get; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientTlsOptions
    content.vb: ReadOnly Property TlsOptions As MqttClientTlsOptions
  overload: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions*
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions
  href: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.html#Azure_Iot_Operations_Protocol_Models_IMqttClientChannelOptions_TlsOptions
  name: TlsOptions
  nameWithType: IMqttClientChannelOptions.TlsOptions
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions.TlsOptions
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientTlsOptions
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientTlsOptions
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttClientTlsOptions.html
  name: MqttClientTlsOptions
  nameWithType: MqttClientTlsOptions
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientTlsOptions
