### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider
  commentId: T:Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider
  id: IMqttClientCertificatesProvider
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates
  langs:
  - csharp
  - vb
  name: IMqttClientCertificatesProvider
  nameWithType: IMqttClientCertificatesProvider
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCertificatesProvider.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IMqttClientCertificatesProvider
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCertificatesProvider.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public interface IMqttClientCertificatesProvider
    content.vb: Public Interface IMqttClientCertificatesProvider
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates
  commentId: M:Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates
  id: GetCertificates
  parent: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider
  langs:
  - csharp
  - vb
  name: GetCertificates()
  nameWithType: IMqttClientCertificatesProvider.GetCertificates()
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates()
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCertificatesProvider.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GetCertificates
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCertificatesProvider.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: X509CertificateCollection GetCertificates()
    return:
      type: System.Security.Cryptography.X509Certificates.X509CertificateCollection
    content.vb: Function GetCertificates() As X509CertificateCollection
  overload: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates*
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates
  href: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.html#Azure_Iot_Operations_Protocol_Models_IMqttClientCertificatesProvider_GetCertificates
  name: GetCertificates
  nameWithType: IMqttClientCertificatesProvider.GetCertificates
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider.GetCertificates
- uid: System.Security.Cryptography.X509Certificates.X509CertificateCollection
  commentId: T:System.Security.Cryptography.X509Certificates.X509CertificateCollection
  parent: System.Security.Cryptography.X509Certificates
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.security.cryptography.x509certificates.x509certificatecollection
  name: X509CertificateCollection
  nameWithType: X509CertificateCollection
  fullName: System.Security.Cryptography.X509Certificates.X509CertificateCollection
- uid: System.Security.Cryptography.X509Certificates
  commentId: N:System.Security.Cryptography.X509Certificates
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Security.Cryptography.X509Certificates
  nameWithType: System.Security.Cryptography.X509Certificates
  fullName: System.Security.Cryptography.X509Certificates
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Security
    name: Security
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.security
  - name: .
  - uid: System.Security.Cryptography
    name: Cryptography
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.security.cryptography
  - name: .
  - uid: System.Security.Cryptography.X509Certificates
    name: X509Certificates
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.security.cryptography.x509certificates
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Security
    name: Security
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.security
  - name: .
  - uid: System.Security.Cryptography
    name: Cryptography
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.security.cryptography
  - name: .
  - uid: System.Security.Cryptography.X509Certificates
    name: X509Certificates
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.security.cryptography.x509certificates
