### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.SchemaRegistry
  commentId: N:Azure.Iot.Operations.Services.SchemaRegistry
  id: SchemaRegistry
  parent: Azure.Iot.Operations.Services
  children:
  - Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary`1
  - Azure.Iot.Operations.Services.SchemaRegistry.EmptyJson
  - Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  - Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistryClient
  - Azure.Iot.Operations.Services.SchemaRegistry.Utf8JsonSerializer
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Services.SchemaRegistry
  nameWithType: Azure.Iot.Operations.Services.SchemaRegistry
  fullName: Azure.Iot.Operations.Services.SchemaRegistry
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Services
references:
- uid: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary`1
  commentId: T:Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary`1
  href: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary-1.html
  name: CombinedPrefixedReadOnlyDictionary<TValue>
  nameWithType: CombinedPrefixedReadOnlyDictionary<TValue>
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary<TValue>
  nameWithType.vb: CombinedPrefixedReadOnlyDictionary(Of TValue)
  fullName.vb: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary(Of TValue)
  name.vb: CombinedPrefixedReadOnlyDictionary(Of TValue)
  spec.csharp:
  - uid: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary`1
    name: CombinedPrefixedReadOnlyDictionary
    href: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary-1.html
  - name: <
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary`1
    name: CombinedPrefixedReadOnlyDictionary
    href: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TValue
  - name: )
- uid: Azure.Iot.Operations.Services.SchemaRegistry.EmptyJson
  commentId: T:Azure.Iot.Operations.Services.SchemaRegistry.EmptyJson
  href: Azure.Iot.Operations.Services.SchemaRegistry.EmptyJson.html
  name: EmptyJson
  nameWithType: EmptyJson
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.EmptyJson
- uid: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  commentId: T:Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  parent: Azure.Iot.Operations.Services.SchemaRegistry
  href: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.html
  name: ISchemaRegistryClient
  nameWithType: ISchemaRegistryClient
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
- uid: Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistryClient
  commentId: T:Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistryClient
  href: Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistryClient.html
  name: SchemaRegistryClient
  nameWithType: SchemaRegistryClient
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistryClient
- uid: Azure.Iot.Operations.Services.SchemaRegistry.Utf8JsonSerializer
  commentId: T:Azure.Iot.Operations.Services.SchemaRegistry.Utf8JsonSerializer
  href: Azure.Iot.Operations.Services.SchemaRegistry.Utf8JsonSerializer.html
  name: Utf8JsonSerializer
  nameWithType: Utf8JsonSerializer
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.Utf8JsonSerializer
- uid: Azure.Iot.Operations.Services.SchemaRegistry
  commentId: N:Azure.Iot.Operations.Services.SchemaRegistry
  href: Azure.html
  name: Azure.Iot.Operations.Services.SchemaRegistry
  nameWithType: Azure.Iot.Operations.Services.SchemaRegistry
  fullName: Azure.Iot.Operations.Services.SchemaRegistry
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.SchemaRegistry
    name: SchemaRegistry
    href: Azure.Iot.Operations.Services.SchemaRegistry.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.SchemaRegistry
    name: SchemaRegistry
    href: Azure.Iot.Operations.Services.SchemaRegistry.html
