### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  id: MqttRetainHandling
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.DoNotSendOnSubscribe
  - Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribe
  - Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribeIfNewSubscriptionOnly
  langs:
  - csharp
  - vb
  name: MqttRetainHandling
  nameWithType: MqttRetainHandling
  fullName: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttRetainHandling
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttRetainHandling
    content.vb: Public Enum MqttRetainHandling
- uid: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribe
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribe
  id: SendAtSubscribe
  parent: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  langs:
  - csharp
  - vb
  name: SendAtSubscribe
  nameWithType: MqttRetainHandling.SendAtSubscribe
  fullName: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribe
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SendAtSubscribe
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: SendAtSubscribe = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
- uid: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribeIfNewSubscriptionOnly
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribeIfNewSubscriptionOnly
  id: SendAtSubscribeIfNewSubscriptionOnly
  parent: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  langs:
  - csharp
  - vb
  name: SendAtSubscribeIfNewSubscriptionOnly
  nameWithType: MqttRetainHandling.SendAtSubscribeIfNewSubscriptionOnly
  fullName: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.SendAtSubscribeIfNewSubscriptionOnly
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SendAtSubscribeIfNewSubscriptionOnly
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: SendAtSubscribeIfNewSubscriptionOnly = 1
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
- uid: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.DoNotSendOnSubscribe
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.DoNotSendOnSubscribe
  id: DoNotSendOnSubscribe
  parent: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  langs:
  - csharp
  - vb
  name: DoNotSendOnSubscribe
  nameWithType: MqttRetainHandling.DoNotSendOnSubscribe
  fullName: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.DoNotSendOnSubscribe
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: DoNotSendOnSubscribe
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttRetainHandling.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: DoNotSendOnSubscribe = 2
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling.html
  name: MqttRetainHandling
  nameWithType: MqttRetainHandling
  fullName: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
