### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.PatternValidity
  commentId: T:Azure.Iot.Operations.Protocol.PatternValidity
  id: PatternValidity
  parent: Azure.Iot.Operations.Protocol
  children:
  - Azure.Iot.Operations.Protocol.PatternValidity.InvalidPattern
  - Azure.Iot.Operations.Protocol.PatternValidity.InvalidResidentReplacement
  - Azure.Iot.Operations.Protocol.PatternValidity.InvalidToken
  - Azure.Iot.Operations.Protocol.PatternValidity.InvalidTransientReplacement
  - Azure.Iot.Operations.Protocol.PatternValidity.MissingReplacement
  - Azure.Iot.Operations.Protocol.PatternValidity.Valid
  langs:
  - csharp
  - vb
  name: PatternValidity
  nameWithType: PatternValidity
  fullName: Azure.Iot.Operations.Protocol.PatternValidity
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: PatternValidity
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: public enum PatternValidity
    content.vb: Public Enum PatternValidity
- uid: Azure.Iot.Operations.Protocol.PatternValidity.Valid
  commentId: F:Azure.Iot.Operations.Protocol.PatternValidity.Valid
  id: Valid
  parent: Azure.Iot.Operations.Protocol.PatternValidity
  langs:
  - csharp
  - vb
  name: Valid
  nameWithType: PatternValidity.Valid
  fullName: Azure.Iot.Operations.Protocol.PatternValidity.Valid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Valid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: Valid = 0
    return:
      type: Azure.Iot.Operations.Protocol.PatternValidity
- uid: Azure.Iot.Operations.Protocol.PatternValidity.InvalidPattern
  commentId: F:Azure.Iot.Operations.Protocol.PatternValidity.InvalidPattern
  id: InvalidPattern
  parent: Azure.Iot.Operations.Protocol.PatternValidity
  langs:
  - csharp
  - vb
  name: InvalidPattern
  nameWithType: PatternValidity.InvalidPattern
  fullName: Azure.Iot.Operations.Protocol.PatternValidity.InvalidPattern
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InvalidPattern
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: InvalidPattern = 1
    return:
      type: Azure.Iot.Operations.Protocol.PatternValidity
- uid: Azure.Iot.Operations.Protocol.PatternValidity.InvalidToken
  commentId: F:Azure.Iot.Operations.Protocol.PatternValidity.InvalidToken
  id: InvalidToken
  parent: Azure.Iot.Operations.Protocol.PatternValidity
  langs:
  - csharp
  - vb
  name: InvalidToken
  nameWithType: PatternValidity.InvalidToken
  fullName: Azure.Iot.Operations.Protocol.PatternValidity.InvalidToken
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InvalidToken
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: InvalidToken = 2
    return:
      type: Azure.Iot.Operations.Protocol.PatternValidity
- uid: Azure.Iot.Operations.Protocol.PatternValidity.MissingReplacement
  commentId: F:Azure.Iot.Operations.Protocol.PatternValidity.MissingReplacement
  id: MissingReplacement
  parent: Azure.Iot.Operations.Protocol.PatternValidity
  langs:
  - csharp
  - vb
  name: MissingReplacement
  nameWithType: PatternValidity.MissingReplacement
  fullName: Azure.Iot.Operations.Protocol.PatternValidity.MissingReplacement
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MissingReplacement
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: MissingReplacement = 3
    return:
      type: Azure.Iot.Operations.Protocol.PatternValidity
- uid: Azure.Iot.Operations.Protocol.PatternValidity.InvalidResidentReplacement
  commentId: F:Azure.Iot.Operations.Protocol.PatternValidity.InvalidResidentReplacement
  id: InvalidResidentReplacement
  parent: Azure.Iot.Operations.Protocol.PatternValidity
  langs:
  - csharp
  - vb
  name: InvalidResidentReplacement
  nameWithType: PatternValidity.InvalidResidentReplacement
  fullName: Azure.Iot.Operations.Protocol.PatternValidity.InvalidResidentReplacement
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InvalidResidentReplacement
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: InvalidResidentReplacement = 4
    return:
      type: Azure.Iot.Operations.Protocol.PatternValidity
- uid: Azure.Iot.Operations.Protocol.PatternValidity.InvalidTransientReplacement
  commentId: F:Azure.Iot.Operations.Protocol.PatternValidity.InvalidTransientReplacement
  id: InvalidTransientReplacement
  parent: Azure.Iot.Operations.Protocol.PatternValidity
  langs:
  - csharp
  - vb
  name: InvalidTransientReplacement
  nameWithType: PatternValidity.InvalidTransientReplacement
  fullName: Azure.Iot.Operations.Protocol.PatternValidity.InvalidTransientReplacement
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InvalidTransientReplacement
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/PatternValidity.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: InvalidTransientReplacement = 5
    return:
      type: Azure.Iot.Operations.Protocol.PatternValidity
references:
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
- uid: Azure.Iot.Operations.Protocol.PatternValidity
  commentId: T:Azure.Iot.Operations.Protocol.PatternValidity
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.PatternValidity.html
  name: PatternValidity
  nameWithType: PatternValidity
  fullName: Azure.Iot.Operations.Protocol.PatternValidity
