### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions
  commentId: T:Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions
  id: AcquireLockRequestOptions
  parent: Azure.Iot.Operations.Services.LeasedLock
  children:
  - Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId
  langs:
  - csharp
  - vb
  name: AcquireLockRequestOptions
  nameWithType: AcquireLockRequestOptions
  fullName: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeasedLock/AcquireLockRequestOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: AcquireLockRequestOptions
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeasedLock/AcquireLockRequestOptions.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeasedLock
  summary: Optional fields for an acquire lock request.
  example: []
  syntax:
    content: public class AcquireLockRequestOptions
    content.vb: Public Class AcquireLockRequestOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId
  commentId: P:Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId
  id: SessionId
  parent: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions
  langs:
  - csharp
  - vb
  name: SessionId
  nameWithType: AcquireLockRequestOptions.SessionId
  fullName: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeasedLock/AcquireLockRequestOptions.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SessionId
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeasedLock/AcquireLockRequestOptions.cs
    startLine: 22
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeasedLock
  summary: >-
    The optional value to include in the lock's value. If not provided, the lock's value will equal

    the lock holder name. If it is provided, the lock's value will equal {holderName}:{sessionId}
  remarks: >-
    <p>

    If this value is provided, then you'll need to provide the same value to <xref href="Azure.Iot.Operations.Services.LeasedLock.ReleaseLockRequestOptions.SessionId" data-throw-if-not-resolved="false"></xref>

    or attempts to release the lock will fail.

    </p>

    <p>

    By providing a unique sessionId, an application can use the same holderName and/or the same MQTT client

    in different threads to acquire the same lock without worrying about accidentally allowing two clients

    to both own a lock at the same time.

    </p>
  example: []
  syntax:
    content: public string? SessionId { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SessionId As String
  overload: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId*
references:
- uid: Azure.Iot.Operations.Services.LeasedLock
  commentId: N:Azure.Iot.Operations.Services.LeasedLock
  href: Azure.html
  name: Azure.Iot.Operations.Services.LeasedLock
  nameWithType: Azure.Iot.Operations.Services.LeasedLock
  fullName: Azure.Iot.Operations.Services.LeasedLock
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.LeasedLock
    name: LeasedLock
    href: Azure.Iot.Operations.Services.LeasedLock.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.LeasedLock
    name: LeasedLock
    href: Azure.Iot.Operations.Services.LeasedLock.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Services.LeasedLock.ReleaseLockRequestOptions.SessionId
  commentId: P:Azure.Iot.Operations.Services.LeasedLock.ReleaseLockRequestOptions.SessionId
  href: Azure.Iot.Operations.Services.LeasedLock.ReleaseLockRequestOptions.html#Azure_Iot_Operations_Services_LeasedLock_ReleaseLockRequestOptions_SessionId
  name: SessionId
  nameWithType: ReleaseLockRequestOptions.SessionId
  fullName: Azure.Iot.Operations.Services.LeasedLock.ReleaseLockRequestOptions.SessionId
- uid: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId*
  commentId: Overload:Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId
  href: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.html#Azure_Iot_Operations_Services_LeasedLock_AcquireLockRequestOptions_SessionId
  name: SessionId
  nameWithType: AcquireLockRequestOptions.SessionId
  fullName: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions.SessionId
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
