### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError
  commentId: T:Azure.Iot.Operations.Services.StateStore.ServiceError
  id: ServiceError
  parent: Azure.Iot.Operations.Services.StateStore
  children:
  - Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenLowerVersion
  - Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenSkew
  - Azure.Iot.Operations.Services.StateStore.ServiceError.KeyLengthZero
  - Azure.Iot.Operations.Services.StateStore.ServiceError.KeyQuotaExceeded
  - Azure.Iot.Operations.Services.StateStore.ServiceError.MissingFencingToken
  - Azure.Iot.Operations.Services.StateStore.ServiceError.NotAuthorized
  - Azure.Iot.Operations.Services.StateStore.ServiceError.SyntaxError
  - Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMalformed
  - Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMissing
  - Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampSkew
  - Azure.Iot.Operations.Services.StateStore.ServiceError.Unknown
  - Azure.Iot.Operations.Services.StateStore.ServiceError.UnknownCommand
  - Azure.Iot.Operations.Services.StateStore.ServiceError.WrongNumberOfArguments
  langs:
  - csharp
  - vb
  name: ServiceError
  nameWithType: ServiceError
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ServiceError
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 36
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: public enum ServiceError
    content.vb: Public Enum ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampSkew
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampSkew
  id: TimestampSkew
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: TimestampSkew
  nameWithType: ServiceError.TimestampSkew
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampSkew
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TimestampSkew
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 41
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: TimestampSkew = 0
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.MissingFencingToken
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.MissingFencingToken
  id: MissingFencingToken
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: MissingFencingToken
  nameWithType: ServiceError.MissingFencingToken
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.MissingFencingToken
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MissingFencingToken
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 48
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: MissingFencingToken = 1
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenSkew
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenSkew
  id: FencingTokenSkew
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: FencingTokenSkew
  nameWithType: ServiceError.FencingTokenSkew
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenSkew
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: FencingTokenSkew
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 52
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: FencingTokenSkew = 2
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenLowerVersion
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenLowerVersion
  id: FencingTokenLowerVersion
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: FencingTokenLowerVersion
  nameWithType: ServiceError.FencingTokenLowerVersion
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.FencingTokenLowerVersion
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: FencingTokenLowerVersion
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 56
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: FencingTokenLowerVersion = 3
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.KeyQuotaExceeded
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.KeyQuotaExceeded
  id: KeyQuotaExceeded
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: KeyQuotaExceeded
  nameWithType: ServiceError.KeyQuotaExceeded
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.KeyQuotaExceeded
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: KeyQuotaExceeded
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 60
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: KeyQuotaExceeded = 4
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.SyntaxError
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.SyntaxError
  id: SyntaxError
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: SyntaxError
  nameWithType: ServiceError.SyntaxError
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.SyntaxError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SyntaxError
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 67
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: SyntaxError = 5
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.NotAuthorized
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.NotAuthorized
  id: NotAuthorized
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: NotAuthorized
  nameWithType: ServiceError.NotAuthorized
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.NotAuthorized
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NotAuthorized
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 71
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: NotAuthorized = 6
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.UnknownCommand
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.UnknownCommand
  id: UnknownCommand
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: UnknownCommand
  nameWithType: ServiceError.UnknownCommand
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.UnknownCommand
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnknownCommand
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 78
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: UnknownCommand = 7
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.WrongNumberOfArguments
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.WrongNumberOfArguments
  id: WrongNumberOfArguments
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: WrongNumberOfArguments
  nameWithType: ServiceError.WrongNumberOfArguments
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.WrongNumberOfArguments
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: WrongNumberOfArguments
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 85
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: WrongNumberOfArguments = 8
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMissing
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMissing
  id: TimestampMissing
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: TimestampMissing
  nameWithType: ServiceError.TimestampMissing
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMissing
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TimestampMissing
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 92
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: TimestampMissing = 9
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMalformed
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMalformed
  id: TimestampMalformed
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: TimestampMalformed
  nameWithType: ServiceError.TimestampMalformed
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.TimestampMalformed
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TimestampMalformed
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 99
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: TimestampMalformed = 10
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.KeyLengthZero
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.KeyLengthZero
  id: KeyLengthZero
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: KeyLengthZero
  nameWithType: ServiceError.KeyLengthZero
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.KeyLengthZero
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: KeyLengthZero
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 103
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: KeyLengthZero = 11
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError.Unknown
  commentId: F:Azure.Iot.Operations.Services.StateStore.ServiceError.Unknown
  id: Unknown
  parent: Azure.Iot.Operations.Services.StateStore.ServiceError
  langs:
  - csharp
  - vb
  name: Unknown
  nameWithType: ServiceError.Unknown
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError.Unknown
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Unknown
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 107
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: Unknown = 12
    return:
      type: Azure.Iot.Operations.Services.StateStore.ServiceError
references:
- uid: Azure.Iot.Operations.Services.StateStore
  commentId: N:Azure.Iot.Operations.Services.StateStore
  href: Azure.html
  name: Azure.Iot.Operations.Services.StateStore
  nameWithType: Azure.Iot.Operations.Services.StateStore
  fullName: Azure.Iot.Operations.Services.StateStore
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
- uid: Azure.Iot.Operations.Services.StateStore.ServiceError
  commentId: T:Azure.Iot.Operations.Services.StateStore.ServiceError
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.ServiceError.html
  name: ServiceError
  nameWithType: ServiceError
  fullName: Azure.Iot.Operations.Services.StateStore.ServiceError
