### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.LeasedLock.LockState
  commentId: T:Azure.Iot.Operations.Services.LeasedLock.LockState
  id: LockState
  parent: Azure.Iot.Operations.Services.LeasedLock
  children:
  - Azure.Iot.Operations.Services.LeasedLock.LockState.Acquired
  - Azure.Iot.Operations.Services.LeasedLock.LockState.Released
  langs:
  - csharp
  - vb
  name: LockState
  nameWithType: LockState
  fullName: Azure.Iot.Operations.Services.LeasedLock.LockState
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LockState.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: LockState
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LockState.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeasedLock
  summary: The state of the leased lock.
  example: []
  syntax:
    content: public enum LockState
    content.vb: Public Enum LockState
- uid: Azure.Iot.Operations.Services.LeasedLock.LockState.Acquired
  commentId: F:Azure.Iot.Operations.Services.LeasedLock.LockState.Acquired
  id: Acquired
  parent: Azure.Iot.Operations.Services.LeasedLock.LockState
  langs:
  - csharp
  - vb
  name: Acquired
  nameWithType: LockState.Acquired
  fullName: Azure.Iot.Operations.Services.LeasedLock.LockState.Acquired
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LockState.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Acquired
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LockState.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeasedLock
  summary: The lock was just acquired.
  example: []
  syntax:
    content: Acquired = 0
    return:
      type: Azure.Iot.Operations.Services.LeasedLock.LockState
- uid: Azure.Iot.Operations.Services.LeasedLock.LockState.Released
  commentId: F:Azure.Iot.Operations.Services.LeasedLock.LockState.Released
  id: Released
  parent: Azure.Iot.Operations.Services.LeasedLock.LockState
  langs:
  - csharp
  - vb
  name: Released
  nameWithType: LockState.Released
  fullName: Azure.Iot.Operations.Services.LeasedLock.LockState.Released
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LockState.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Released
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeasedLock/LockState.cs
    startLine: 16
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeasedLock
  summary: >-
    The lock was released, or the previous lease on the lock expired. The lock is available to acquire

    at this time.
  example: []
  syntax:
    content: Released = 1
    return:
      type: Azure.Iot.Operations.Services.LeasedLock.LockState
references:
- uid: Azure.Iot.Operations.Services.LeasedLock
  commentId: N:Azure.Iot.Operations.Services.LeasedLock
  href: Azure.html
  name: Azure.Iot.Operations.Services.LeasedLock
  nameWithType: Azure.Iot.Operations.Services.LeasedLock
  fullName: Azure.Iot.Operations.Services.LeasedLock
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.LeasedLock
    name: LeasedLock
    href: Azure.Iot.Operations.Services.LeasedLock.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.LeasedLock
    name: LeasedLock
    href: Azure.Iot.Operations.Services.LeasedLock.html
- uid: Azure.Iot.Operations.Services.LeasedLock.LockState
  commentId: T:Azure.Iot.Operations.Services.LeasedLock.LockState
  parent: Azure.Iot.Operations.Services.LeasedLock
  href: Azure.Iot.Operations.Services.LeasedLock.LockState.html
  name: LockState
  nameWithType: LockState
  fullName: Azure.Iot.Operations.Services.LeasedLock.LockState
