### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.Akri.IDiscoveredAssetResourcesClient
  commentId: T:Azure.Iot.Operations.Services.Akri.IDiscoveredAssetResourcesClient
  id: IDiscoveredAssetResourcesClient
  parent: Azure.Iot.Operations.Services.Akri
  children: []
  langs:
  - csharp
  - vb
  name: IDiscoveredAssetResourcesClient
  nameWithType: IDiscoveredAssetResourcesClient
  fullName: Azure.Iot.Operations.Services.Akri.IDiscoveredAssetResourcesClient
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/Akri/IDiscoveredAssetResourcesClient.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IDiscoveredAssetResourcesClient
    path: ../../dotnet/src/Azure.Iot.Operations.Services/Akri/IDiscoveredAssetResourcesClient.cs
    startLine: 13
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.Akri
  summary: Interface for creating discovered assets and asset endpoint profiles.
  example: []
  syntax:
    content: 'public interface IDiscoveredAssetResourcesClient : IAsyncDisposable'
    content.vb: Public Interface IDiscoveredAssetResourcesClient Inherits IAsyncDisposable
  inheritedMembers:
  - System.IAsyncDisposable.DisposeAsync
references:
- uid: Azure.Iot.Operations.Services.Akri
  commentId: N:Azure.Iot.Operations.Services.Akri
  href: Azure.html
  name: Azure.Iot.Operations.Services.Akri
  nameWithType: Azure.Iot.Operations.Services.Akri
  fullName: Azure.Iot.Operations.Services.Akri
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.Akri
    name: Akri
    href: Azure.Iot.Operations.Services.Akri.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.Akri
    name: Akri
    href: Azure.Iot.Operations.Services.Akri.html
- uid: System.IAsyncDisposable.DisposeAsync
  commentId: M:System.IAsyncDisposable.DisposeAsync
  parent: System.IAsyncDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable.disposeasync
  name: DisposeAsync()
  nameWithType: IAsyncDisposable.DisposeAsync()
  fullName: System.IAsyncDisposable.DisposeAsync()
  spec.csharp:
  - uid: System.IAsyncDisposable.DisposeAsync
    name: DisposeAsync
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable.disposeasync
  - name: (
  - name: )
  spec.vb:
  - uid: System.IAsyncDisposable.DisposeAsync
    name: DisposeAsync
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable.disposeasync
  - name: (
  - name: )
- uid: System.IAsyncDisposable
  commentId: T:System.IAsyncDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable
  name: IAsyncDisposable
  nameWithType: IAsyncDisposable
  fullName: System.IAsyncDisposable
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
