### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  id: MqttQualityOfServiceLevel
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtLeastOnce
  - Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtMostOnce
  - Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.ExactlyOnce
  langs:
  - csharp
  - vb
  name: MqttQualityOfServiceLevel
  nameWithType: MqttQualityOfServiceLevel
  fullName: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttQualityOfServiceLevel
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttQualityOfServiceLevel
    content.vb: Public Enum MqttQualityOfServiceLevel
- uid: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtMostOnce
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtMostOnce
  id: AtMostOnce
  parent: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  langs:
  - csharp
  - vb
  name: AtMostOnce
  nameWithType: MqttQualityOfServiceLevel.AtMostOnce
  fullName: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtMostOnce
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: AtMostOnce
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: AtMostOnce = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
- uid: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtLeastOnce
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtLeastOnce
  id: AtLeastOnce
  parent: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  langs:
  - csharp
  - vb
  name: AtLeastOnce
  nameWithType: MqttQualityOfServiceLevel.AtLeastOnce
  fullName: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.AtLeastOnce
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: AtLeastOnce
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: AtLeastOnce = 1
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
- uid: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.ExactlyOnce
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.ExactlyOnce
  id: ExactlyOnce
  parent: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  langs:
  - csharp
  - vb
  name: ExactlyOnce
  nameWithType: MqttQualityOfServiceLevel.ExactlyOnce
  fullName: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.ExactlyOnce
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ExactlyOnce
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttQualityOfServiceLevel.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: ExactlyOnce = 2
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel.html
  name: MqttQualityOfServiceLevel
  nameWithType: MqttQualityOfServiceLevel
  fullName: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
