### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1
  commentId: T:Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1
  id: ExtendedRequest`1
  parent: Azure.Iot.Operations.Protocol.RPC
  children:
  - Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.Request
  - Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.RequestMetadata
  langs:
  - csharp
  - vb
  name: ExtendedRequest<TReq>
  nameWithType: ExtendedRequest<TReq>
  fullName: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest<TReq>
  type: Struct
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedRequest.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ExtendedRequest
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedRequest.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.RPC
  syntax:
    content: 'public struct ExtendedRequest<TReq> where TReq : class'
    typeParameters:
    - id: TReq
    content.vb: Public Structure ExtendedRequest(Of TReq As Class)
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  nameWithType.vb: ExtendedRequest(Of TReq)
  fullName.vb: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest(Of TReq)
  name.vb: ExtendedRequest(Of TReq)
- uid: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.Request
  commentId: P:Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.Request
  id: Request
  parent: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1
  langs:
  - csharp
  - vb
  name: Request
  nameWithType: ExtendedRequest<TReq>.Request
  fullName: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest<TReq>.Request
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedRequest.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Request
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedRequest.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.RPC
  syntax:
    content: public TReq Request { readonly get; set; }
    parameters: []
    return:
      type: '{TReq}'
    content.vb: Public Property Request As TReq
  overload: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.Request*
  nameWithType.vb: ExtendedRequest(Of TReq).Request
  fullName.vb: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest(Of TReq).Request
- uid: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.RequestMetadata
  commentId: P:Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.RequestMetadata
  id: RequestMetadata
  parent: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1
  langs:
  - csharp
  - vb
  name: RequestMetadata
  nameWithType: ExtendedRequest<TReq>.RequestMetadata
  fullName: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest<TReq>.RequestMetadata
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedRequest.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: RequestMetadata
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/RPC/ExtendedRequest.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.RPC
  syntax:
    content: public CommandRequestMetadata RequestMetadata { readonly get; set; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Protocol.RPC.CommandRequestMetadata
    content.vb: Public Property RequestMetadata As CommandRequestMetadata
  overload: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.RequestMetadata*
  nameWithType.vb: ExtendedRequest(Of TReq).RequestMetadata
  fullName.vb: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest(Of TReq).RequestMetadata
references:
- uid: Azure.Iot.Operations.Protocol.RPC
  commentId: N:Azure.Iot.Operations.Protocol.RPC
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.RPC
  nameWithType: Azure.Iot.Operations.Protocol.RPC
  fullName: Azure.Iot.Operations.Protocol.RPC
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.RPC
    name: RPC
    href: Azure.Iot.Operations.Protocol.RPC.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.RPC
    name: RPC
    href: Azure.Iot.Operations.Protocol.RPC.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.Request*
  commentId: Overload:Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.Request
  href: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest-1.html#Azure_Iot_Operations_Protocol_RPC_ExtendedRequest_1_Request
  name: Request
  nameWithType: ExtendedRequest<TReq>.Request
  fullName: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest<TReq>.Request
  nameWithType.vb: ExtendedRequest(Of TReq).Request
  fullName.vb: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest(Of TReq).Request
- uid: '{TReq}'
  commentId: '!:TReq'
  definition: TReq
  name: TReq
  nameWithType: TReq
  fullName: TReq
- uid: TReq
  name: TReq
  nameWithType: TReq
  fullName: TReq
- uid: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.RequestMetadata*
  commentId: Overload:Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1.RequestMetadata
  href: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest-1.html#Azure_Iot_Operations_Protocol_RPC_ExtendedRequest_1_RequestMetadata
  name: RequestMetadata
  nameWithType: ExtendedRequest<TReq>.RequestMetadata
  fullName: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest<TReq>.RequestMetadata
  nameWithType.vb: ExtendedRequest(Of TReq).RequestMetadata
  fullName.vb: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest(Of TReq).RequestMetadata
- uid: Azure.Iot.Operations.Protocol.RPC.CommandRequestMetadata
  commentId: T:Azure.Iot.Operations.Protocol.RPC.CommandRequestMetadata
  parent: Azure.Iot.Operations.Protocol.RPC
  href: Azure.Iot.Operations.Protocol.RPC.CommandRequestMetadata.html
  name: CommandRequestMetadata
  nameWithType: CommandRequestMetadata
  fullName: Azure.Iot.Operations.Protocol.RPC.CommandRequestMetadata
