### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  commentId: T:Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  id: ISchemaRegistryClient
  parent: Azure.Iot.Operations.Services.SchemaRegistry
  children:
  - Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync(System.String,System.String,System.Nullable{System.TimeSpan},System.Threading.CancellationToken)
  langs:
  - csharp
  - vb
  name: ISchemaRegistryClient
  nameWithType: ISchemaRegistryClient
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/SchemaRegistry/ISchemaRegistryClient.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ISchemaRegistryClient
    path: ../../dotnet/src/Azure.Iot.Operations.Services/SchemaRegistry/ISchemaRegistryClient.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.SchemaRegistry
  syntax:
    content: 'public interface ISchemaRegistryClient : IAsyncDisposable'
    content.vb: Public Interface ISchemaRegistryClient Inherits IAsyncDisposable
  inheritedMembers:
  - System.IAsyncDisposable.DisposeAsync
- uid: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync(System.String,System.String,System.Nullable{System.TimeSpan},System.Threading.CancellationToken)
  commentId: M:Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync(System.String,System.String,System.Nullable{System.TimeSpan},System.Threading.CancellationToken)
  id: GetAsync(System.String,System.String,System.Nullable{System.TimeSpan},System.Threading.CancellationToken)
  parent: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
  langs:
  - csharp
  - vb
  name: GetAsync(string, string, TimeSpan?, CancellationToken)
  nameWithType: ISchemaRegistryClient.GetAsync(string, string, TimeSpan?, CancellationToken)
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync(string, string, System.TimeSpan?, System.Threading.CancellationToken)
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/SchemaRegistry/ISchemaRegistryClient.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GetAsync
    path: ../../dotnet/src/Azure.Iot.Operations.Services/SchemaRegistry/ISchemaRegistryClient.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.SchemaRegistry
  syntax:
    content: Task<Object_Ms_Adr_SchemaRegistry_Schema__1?> GetAsync(string schemaId, string version = "1.0.0", TimeSpan? timeout = null, CancellationToken cancellationToken = default)
    parameters:
    - id: schemaId
      type: System.String
    - id: version
      type: System.String
    - id: timeout
      type: System.Nullable{System.TimeSpan}
    - id: cancellationToken
      type: System.Threading.CancellationToken
    return:
      type: System.Threading.Tasks.Task{Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1}
    content.vb: Function GetAsync(schemaId As String, version As String = "1.0.0", timeout As TimeSpan? = Nothing, cancellationToken As CancellationToken = Nothing) As Task(Of Object_Ms_Adr_SchemaRegistry_Schema__1)
  overload: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync*
  nameWithType.vb: ISchemaRegistryClient.GetAsync(String, String, TimeSpan?, CancellationToken)
  fullName.vb: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync(String, String, System.TimeSpan?, System.Threading.CancellationToken)
  name.vb: GetAsync(String, String, TimeSpan?, CancellationToken)
references:
- uid: Azure.Iot.Operations.Services.SchemaRegistry
  commentId: N:Azure.Iot.Operations.Services.SchemaRegistry
  href: Azure.html
  name: Azure.Iot.Operations.Services.SchemaRegistry
  nameWithType: Azure.Iot.Operations.Services.SchemaRegistry
  fullName: Azure.Iot.Operations.Services.SchemaRegistry
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.SchemaRegistry
    name: SchemaRegistry
    href: Azure.Iot.Operations.Services.SchemaRegistry.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.SchemaRegistry
    name: SchemaRegistry
    href: Azure.Iot.Operations.Services.SchemaRegistry.html
- uid: System.IAsyncDisposable.DisposeAsync
  commentId: M:System.IAsyncDisposable.DisposeAsync
  parent: System.IAsyncDisposable
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable.disposeasync
  name: DisposeAsync()
  nameWithType: IAsyncDisposable.DisposeAsync()
  fullName: System.IAsyncDisposable.DisposeAsync()
  spec.csharp:
  - uid: System.IAsyncDisposable.DisposeAsync
    name: DisposeAsync
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable.disposeasync
  - name: (
  - name: )
  spec.vb:
  - uid: System.IAsyncDisposable.DisposeAsync
    name: DisposeAsync
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable.disposeasync
  - name: (
  - name: )
- uid: System.IAsyncDisposable
  commentId: T:System.IAsyncDisposable
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iasyncdisposable
  name: IAsyncDisposable
  nameWithType: IAsyncDisposable
  fullName: System.IAsyncDisposable
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync*
  commentId: Overload:Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync
  href: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.html#Azure_Iot_Operations_Services_SchemaRegistry_ISchemaRegistryClient_GetAsync_System_String_System_String_System_Nullable_System_TimeSpan__System_Threading_CancellationToken_
  name: GetAsync
  nameWithType: ISchemaRegistryClient.GetAsync
  fullName: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient.GetAsync
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Nullable{System.TimeSpan}
  commentId: T:System.Nullable{System.TimeSpan}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan?
  nameWithType: TimeSpan?
  fullName: System.TimeSpan?
  spec.csharp:
  - uid: System.TimeSpan
    name: TimeSpan
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.timespan
  - name: '?'
  spec.vb:
  - uid: System.TimeSpan
    name: TimeSpan
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.timespan
  - name: '?'
- uid: System.Threading.CancellationToken
  commentId: T:System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.cancellationtoken
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading.Tasks.Task{Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1}
  commentId: T:System.Threading.Tasks.Task{Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<Object_Ms_Adr_SchemaRegistry_Schema__1>
  nameWithType: Task<Object_Ms_Adr_SchemaRegistry_Schema__1>
  fullName: System.Threading.Tasks.Task<Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1>
  nameWithType.vb: Task(Of Object_Ms_Adr_SchemaRegistry_Schema__1)
  fullName.vb: System.Threading.Tasks.Task(Of Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1)
  name.vb: Task(Of Object_Ms_Adr_SchemaRegistry_Schema__1)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1
    name: Object_Ms_Adr_SchemaRegistry_Schema__1
    href: Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1.html
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1
    name: Object_Ms_Adr_SchemaRegistry_Schema__1
    href: Azure.Iot.Operations.Services.SchemaRegistry.dtmi_ms_adr_SchemaRegistry__1.Object_Ms_Adr_SchemaRegistry_Schema__1.html
  - name: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Threading
  commentId: N:System.Threading
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading
  nameWithType: System.Threading
  fullName: System.Threading
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
