### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttUserProperty
  id: MqttUserProperty
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttUserProperty.#ctor(System.String,System.String)
  - Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name
  - Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value
  langs:
  - csharp
  - vb
  name: MqttUserProperty
  nameWithType: MqttUserProperty
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttUserProperty
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public class MqttUserProperty
    content.vb: Public Class MqttUserProperty
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.#ctor(System.String,System.String)
  commentId: M:Azure.Iot.Operations.Protocol.Models.MqttUserProperty.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: Azure.Iot.Operations.Protocol.Models.MqttUserProperty
  langs:
  - csharp
  - vb
  name: MqttUserProperty(string, string)
  nameWithType: MqttUserProperty.MqttUserProperty(string, string)
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.MqttUserProperty(string, string)
  type: Constructor
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: .ctor
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public MqttUserProperty(string name, string value)
    parameters:
    - id: name
      type: System.String
    - id: value
      type: System.String
    content.vb: Public Sub New(name As String, value As String)
  overload: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.#ctor*
  nameWithType.vb: MqttUserProperty.New(String, String)
  fullName.vb: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.New(String, String)
  name.vb: New(String, String)
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name
  commentId: P:Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name
  id: Name
  parent: Azure.Iot.Operations.Protocol.Models.MqttUserProperty
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: MqttUserProperty.Name
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Name
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
    startLine: 12
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name*
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value
  commentId: P:Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value
  id: Value
  parent: Azure.Iot.Operations.Protocol.Models.MqttUserProperty
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: MqttUserProperty.Value
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Value
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttUserProperty.cs
    startLine: 14
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public string Value { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Value As String
  overload: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value*
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.#ctor*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttUserProperty.#ctor
  href: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.html#Azure_Iot_Operations_Protocol_Models_MqttUserProperty__ctor_System_String_System_String_
  name: MqttUserProperty
  nameWithType: MqttUserProperty.MqttUserProperty
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.MqttUserProperty
  nameWithType.vb: MqttUserProperty.New
  fullName.vb: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name
  href: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.html#Azure_Iot_Operations_Protocol_Models_MqttUserProperty_Name
  name: Name
  nameWithType: MqttUserProperty.Name
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Name
- uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value
  href: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.html#Azure_Iot_Operations_Protocol_Models_MqttUserProperty_Value
  name: Value
  nameWithType: MqttUserProperty.Value
  fullName: Azure.Iot.Operations.Protocol.Models.MqttUserProperty.Value
