### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler
  commentId: T:Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler
  id: IMqttExtendedAuthenticationExchangeHandler
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync(Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext)
  langs:
  - csharp
  - vb
  name: IMqttExtendedAuthenticationExchangeHandler
  nameWithType: IMqttExtendedAuthenticationExchangeHandler
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttExtendedAuthenticationExchangeHandler.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IMqttExtendedAuthenticationExchangeHandler
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttExtendedAuthenticationExchangeHandler.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public interface IMqttExtendedAuthenticationExchangeHandler
    content.vb: Public Interface IMqttExtendedAuthenticationExchangeHandler
- uid: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync(Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext)
  commentId: M:Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync(Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext)
  id: HandleRequestAsync(Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext)
  parent: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler
  langs:
  - csharp
  - vb
  name: HandleRequestAsync(MqttExtendedAuthenticationExchangeContext)
  nameWithType: IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync(MqttExtendedAuthenticationExchangeContext)
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync(Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext)
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttExtendedAuthenticationExchangeHandler.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: HandleRequestAsync
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttExtendedAuthenticationExchangeHandler.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: Task HandleRequestAsync(MqttExtendedAuthenticationExchangeContext context)
    parameters:
    - id: context
      type: Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext
    return:
      type: System.Threading.Tasks.Task
    content.vb: Function HandleRequestAsync(context As MqttExtendedAuthenticationExchangeContext) As Task
  overload: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync*
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync
  href: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.html#Azure_Iot_Operations_Protocol_Models_IMqttExtendedAuthenticationExchangeHandler_HandleRequestAsync_Azure_Iot_Operations_Protocol_Models_MqttExtendedAuthenticationExchangeContext_
  name: HandleRequestAsync
  nameWithType: IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler.HandleRequestAsync
- uid: Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext.html
  name: MqttExtendedAuthenticationExchangeContext
  nameWithType: MqttExtendedAuthenticationExchangeContext
  fullName: Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
