### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  id: MqttTopicFilterCompareResult
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.FilterInvalid
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.IsMatch
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.NoMatch
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.TopicInvalid
  langs:
  - csharp
  - vb
  name: MqttTopicFilterCompareResult
  nameWithType: MqttTopicFilterCompareResult
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttTopicFilterCompareResult
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttTopicFilterCompareResult
    content.vb: Public Enum MqttTopicFilterCompareResult
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.NoMatch
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.NoMatch
  id: NoMatch
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  langs:
  - csharp
  - vb
  name: NoMatch
  nameWithType: MqttTopicFilterCompareResult.NoMatch
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.NoMatch
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NoMatch
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: NoMatch = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.IsMatch
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.IsMatch
  id: IsMatch
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  langs:
  - csharp
  - vb
  name: IsMatch
  nameWithType: MqttTopicFilterCompareResult.IsMatch
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.IsMatch
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IsMatch
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: IsMatch = 1
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.FilterInvalid
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.FilterInvalid
  id: FilterInvalid
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  langs:
  - csharp
  - vb
  name: FilterInvalid
  nameWithType: MqttTopicFilterCompareResult.FilterInvalid
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.FilterInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: FilterInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: FilterInvalid = 2
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.TopicInvalid
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.TopicInvalid
  id: TopicInvalid
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  langs:
  - csharp
  - vb
  name: TopicInvalid
  nameWithType: MqttTopicFilterCompareResult.TopicInvalid
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.TopicInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TopicInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterCompareResult.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: TopicInvalid = 3
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.html
  name: MqttTopicFilterCompareResult
  nameWithType: MqttTopicFilterCompareResult
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
