### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  id: MqttPayloadFormatIndicator
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.CharacterData
  - Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.Unspecified
  langs:
  - csharp
  - vb
  name: MqttPayloadFormatIndicator
  nameWithType: MqttPayloadFormatIndicator
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPayloadFormatIndicator.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttPayloadFormatIndicator
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPayloadFormatIndicator.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttPayloadFormatIndicator
    content.vb: Public Enum MqttPayloadFormatIndicator
- uid: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.Unspecified
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.Unspecified
  id: Unspecified
  parent: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  langs:
  - csharp
  - vb
  name: Unspecified
  nameWithType: MqttPayloadFormatIndicator.Unspecified
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.Unspecified
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPayloadFormatIndicator.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Unspecified
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPayloadFormatIndicator.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: Unspecified = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
- uid: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.CharacterData
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.CharacterData
  id: CharacterData
  parent: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  langs:
  - csharp
  - vb
  name: CharacterData
  nameWithType: MqttPayloadFormatIndicator.CharacterData
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.CharacterData
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPayloadFormatIndicator.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: CharacterData
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPayloadFormatIndicator.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: CharacterData = 1
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator.html
  name: MqttPayloadFormatIndicator
  nameWithType: MqttPayloadFormatIndicator
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
