### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Mqtt
  commentId: N:Azure.Iot.Operations.Mqtt
  id: Mqtt
  parent: Azure.Iot.Operations
  children:
  - Azure.Iot.Operations.Mqtt.MqttConnectingFailedException
  - Azure.Iot.Operations.Mqtt.MqttNetTraceLogger
  - Azure.Iot.Operations.Mqtt.OrderedAckMqttClient
  - Azure.Iot.Operations.Mqtt.Session
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Mqtt
  nameWithType: Azure.Iot.Operations.Mqtt
  fullName: Azure.Iot.Operations.Mqtt
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Mqtt
references:
- uid: Azure.Iot.Operations.Mqtt.Session
  commentId: N:Azure.Iot.Operations.Mqtt.Session
  href: Azure.html
  name: Azure.Iot.Operations.Mqtt.Session
  nameWithType: Azure.Iot.Operations.Mqtt.Session
  fullName: Azure.Iot.Operations.Mqtt.Session
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session
    name: Session
    href: Azure.Iot.Operations.Mqtt.Session.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session
    name: Session
    href: Azure.Iot.Operations.Mqtt.Session.html
- uid: Azure.Iot.Operations.Mqtt.MqttConnectingFailedException
  commentId: T:Azure.Iot.Operations.Mqtt.MqttConnectingFailedException
  href: Azure.Iot.Operations.Mqtt.MqttConnectingFailedException.html
  name: MqttConnectingFailedException
  nameWithType: MqttConnectingFailedException
  fullName: Azure.Iot.Operations.Mqtt.MqttConnectingFailedException
- uid: Azure.Iot.Operations.Mqtt.MqttNetTraceLogger
  commentId: T:Azure.Iot.Operations.Mqtt.MqttNetTraceLogger
  href: Azure.Iot.Operations.Mqtt.MqttNetTraceLogger.html
  name: MqttNetTraceLogger
  nameWithType: MqttNetTraceLogger
  fullName: Azure.Iot.Operations.Mqtt.MqttNetTraceLogger
- uid: Azure.Iot.Operations.Mqtt.OrderedAckMqttClient
  commentId: T:Azure.Iot.Operations.Mqtt.OrderedAckMqttClient
  parent: Azure.Iot.Operations.Mqtt
  href: Azure.Iot.Operations.Mqtt.OrderedAckMqttClient.html
  name: OrderedAckMqttClient
  nameWithType: OrderedAckMqttClient
  fullName: Azure.Iot.Operations.Mqtt.OrderedAckMqttClient
- uid: Azure.Iot.Operations.Mqtt
  commentId: N:Azure.Iot.Operations.Mqtt
  href: Azure.html
  name: Azure.Iot.Operations.Mqtt
  nameWithType: Azure.Iot.Operations.Mqtt
  fullName: Azure.Iot.Operations.Mqtt
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
