### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Events
  commentId: N:Azure.Iot.Operations.Protocol.Events
  id: Events
  parent: Azure.Iot.Operations.Protocol
  children:
  - Azure.Iot.Operations.Protocol.Events.MqttApplicationMessageReceivedEventArgs
  - Azure.Iot.Operations.Protocol.Events.MqttClientConnectedEventArgs
  - Azure.Iot.Operations.Protocol.Events.MqttClientDisconnectedEventArgs
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Protocol.Events
  nameWithType: Azure.Iot.Operations.Protocol.Events
  fullName: Azure.Iot.Operations.Protocol.Events
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Protocol
references:
- uid: Azure.Iot.Operations.Protocol.Events.MqttApplicationMessageReceivedEventArgs
  commentId: T:Azure.Iot.Operations.Protocol.Events.MqttApplicationMessageReceivedEventArgs
  href: Azure.Iot.Operations.Protocol.Events.MqttApplicationMessageReceivedEventArgs.html
  name: MqttApplicationMessageReceivedEventArgs
  nameWithType: MqttApplicationMessageReceivedEventArgs
  fullName: Azure.Iot.Operations.Protocol.Events.MqttApplicationMessageReceivedEventArgs
- uid: Azure.Iot.Operations.Protocol.Events.MqttClientConnectedEventArgs
  commentId: T:Azure.Iot.Operations.Protocol.Events.MqttClientConnectedEventArgs
  href: Azure.Iot.Operations.Protocol.Events.MqttClientConnectedEventArgs.html
  name: MqttClientConnectedEventArgs
  nameWithType: MqttClientConnectedEventArgs
  fullName: Azure.Iot.Operations.Protocol.Events.MqttClientConnectedEventArgs
- uid: Azure.Iot.Operations.Protocol.Events.MqttClientDisconnectedEventArgs
  commentId: T:Azure.Iot.Operations.Protocol.Events.MqttClientDisconnectedEventArgs
  href: Azure.Iot.Operations.Protocol.Events.MqttClientDisconnectedEventArgs.html
  name: MqttClientDisconnectedEventArgs
  nameWithType: MqttClientDisconnectedEventArgs
  fullName: Azure.Iot.Operations.Protocol.Events.MqttClientDisconnectedEventArgs
