### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider
  commentId: T:Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider
  id: IMqttClientCredentialsProvider
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  - Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  langs:
  - csharp
  - vb
  name: IMqttClientCredentialsProvider
  nameWithType: IMqttClientCredentialsProvider
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCredentialsProvider.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IMqttClientCredentialsProvider
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCredentialsProvider.cs
    startLine: 3
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public interface IMqttClientCredentialsProvider
    content.vb: Public Interface IMqttClientCredentialsProvider
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  commentId: M:Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  id: GetUserName(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  parent: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider
  langs:
  - csharp
  - vb
  name: GetUserName(MqttClientOptions)
  nameWithType: IMqttClientCredentialsProvider.GetUserName(MqttClientOptions)
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCredentialsProvider.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GetUserName
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCredentialsProvider.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: string GetUserName(MqttClientOptions clientOptions)
    parameters:
    - id: clientOptions
      type: Azure.Iot.Operations.Protocol.Models.MqttClientOptions
    return:
      type: System.String
    content.vb: Function GetUserName(clientOptions As MqttClientOptions) As String
  overload: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName*
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  commentId: M:Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  id: GetPassword(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  parent: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider
  langs:
  - csharp
  - vb
  name: GetPassword(MqttClientOptions)
  nameWithType: IMqttClientCredentialsProvider.GetPassword(MqttClientOptions)
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword(Azure.Iot.Operations.Protocol.Models.MqttClientOptions)
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCredentialsProvider.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: GetPassword
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/IMqttClientCredentialsProvider.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: byte[]? GetPassword(MqttClientOptions clientOptions)
    parameters:
    - id: clientOptions
      type: Azure.Iot.Operations.Protocol.Models.MqttClientOptions
    return:
      type: System.Byte[]
    content.vb: Function GetPassword(clientOptions As MqttClientOptions) As Byte()
  overload: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword*
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName
  href: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.html#Azure_Iot_Operations_Protocol_Models_IMqttClientCredentialsProvider_GetUserName_Azure_Iot_Operations_Protocol_Models_MqttClientOptions_
  name: GetUserName
  nameWithType: IMqttClientCredentialsProvider.GetUserName
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetUserName
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientOptions
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientOptions
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttClientOptions.html
  name: MqttClientOptions
  nameWithType: MqttClientOptions
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientOptions
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword
  href: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.html#Azure_Iot_Operations_Protocol_Models_IMqttClientCredentialsProvider_GetPassword_Azure_Iot_Operations_Protocol_Models_MqttClientOptions_
  name: GetPassword
  nameWithType: IMqttClientCredentialsProvider.GetPassword
  fullName: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider.GetPassword
- uid: System.Byte[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.byte
  name: byte[]
  nameWithType: byte[]
  fullName: byte[]
  nameWithType.vb: Byte()
  fullName.vb: Byte()
  name.vb: Byte()
  spec.csharp:
  - uid: System.Byte
    name: byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.Byte
    name: Byte
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.byte
  - name: (
  - name: )
