### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
  id: MqttClientSubscribeResultItem
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.#ctor(Azure.Iot.Operations.Protocol.Models.MqttTopicFilter,Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode)
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode
  - Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter
  langs:
  - csharp
  - vb
  name: MqttClientSubscribeResultItem
  nameWithType: MqttClientSubscribeResultItem
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttClientSubscribeResultItem
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public class MqttClientSubscribeResultItem
    content.vb: Public Class MqttClientSubscribeResultItem
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.#ctor(Azure.Iot.Operations.Protocol.Models.MqttTopicFilter,Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode)
  commentId: M:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.#ctor(Azure.Iot.Operations.Protocol.Models.MqttTopicFilter,Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode)
  id: '#ctor(Azure.Iot.Operations.Protocol.Models.MqttTopicFilter,Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode)'
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
  langs:
  - csharp
  - vb
  name: MqttClientSubscribeResultItem(MqttTopicFilter, MqttClientSubscribeReasonCode)
  nameWithType: MqttClientSubscribeResultItem.MqttClientSubscribeResultItem(MqttTopicFilter, MqttClientSubscribeReasonCode)
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.MqttClientSubscribeResultItem(Azure.Iot.Operations.Protocol.Models.MqttTopicFilter, Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode)
  type: Constructor
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: .ctor
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public MqttClientSubscribeResultItem(MqttTopicFilter topicFilter, MqttClientSubscribeReasonCode reasonCode)
    parameters:
    - id: topicFilter
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilter
    - id: reasonCode
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
    content.vb: Public Sub New(topicFilter As MqttTopicFilter, reasonCode As MqttClientSubscribeReasonCode)
  overload: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.#ctor*
  nameWithType.vb: MqttClientSubscribeResultItem.New(MqttTopicFilter, MqttClientSubscribeReasonCode)
  fullName.vb: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.New(Azure.Iot.Operations.Protocol.Models.MqttTopicFilter, Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode)
  name.vb: New(MqttTopicFilter, MqttClientSubscribeReasonCode)
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter
  commentId: P:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter
  id: TopicFilter
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
  langs:
  - csharp
  - vb
  name: TopicFilter
  nameWithType: MqttClientSubscribeResultItem.TopicFilter
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TopicFilter
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
    startLine: 17
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  summary: >-
    Gets or sets the topic filter.

    The topic filter can contain topics and wildcards.
  example: []
  syntax:
    content: public MqttTopicFilter TopicFilter { get; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilter
    content.vb: Public ReadOnly Property TopicFilter As MqttTopicFilter
  overload: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter*
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode
  commentId: P:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode
  id: ReasonCode
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
  langs:
  - csharp
  - vb
  name: ReasonCode
  nameWithType: MqttClientSubscribeResultItem.ReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ReasonCode
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientSubscribeResultItem.cs
    startLine: 23
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  summary: >-
    Gets or sets the result code.

    <remarks>MQTT 5.0.0+ feature.</remarks>
  example: []
  syntax:
    content: public MqttClientSubscribeReasonCode ReasonCode { get; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
    content.vb: Public ReadOnly Property ReasonCode As MqttClientSubscribeReasonCode
  overload: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode*
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.#ctor*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.#ctor
  href: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.html#Azure_Iot_Operations_Protocol_Models_MqttClientSubscribeResultItem__ctor_Azure_Iot_Operations_Protocol_Models_MqttTopicFilter_Azure_Iot_Operations_Protocol_Models_MqttClientSubscribeReasonCode_
  name: MqttClientSubscribeResultItem
  nameWithType: MqttClientSubscribeResultItem.MqttClientSubscribeResultItem
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.MqttClientSubscribeResultItem
  nameWithType.vb: MqttClientSubscribeResultItem.New
  fullName.vb: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.New
  name.vb: New
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilter
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttTopicFilter
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttTopicFilter.html
  name: MqttTopicFilter
  nameWithType: MqttTopicFilter
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilter
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode.html
  name: MqttClientSubscribeReasonCode
  nameWithType: MqttClientSubscribeReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter
  href: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.html#Azure_Iot_Operations_Protocol_Models_MqttClientSubscribeResultItem_TopicFilter
  name: TopicFilter
  nameWithType: MqttClientSubscribeResultItem.TopicFilter
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.TopicFilter
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode
  href: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.html#Azure_Iot_Operations_Protocol_Models_MqttClientSubscribeResultItem_ReasonCode
  name: ReasonCode
  nameWithType: MqttClientSubscribeResultItem.ReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem.ReasonCode
