### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
  commentId: T:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
  id: LeadershipChangeEventArgs
  parent: Azure.Iot.Operations.Services.LeaderElection
  children:
  - Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader
  - Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState
  - Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp
  langs:
  - csharp
  - vb
  name: LeadershipChangeEventArgs
  nameWithType: LeadershipChangeEventArgs
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: LeadershipChangeEventArgs
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeaderElection
  syntax:
    content: 'public sealed class LeadershipChangeEventArgs : EventArgs'
    content.vb: Public NotInheritable Class LeadershipChangeEventArgs Inherits EventArgs
  inheritance:
  - System.Object
  - System.EventArgs
  inheritedMembers:
  - System.EventArgs.Empty
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState
  commentId: P:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState
  id: NewState
  parent: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
  langs:
  - csharp
  - vb
  name: NewState
  nameWithType: LeadershipChangeEventArgs.NewState
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NewState
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeaderElection
  summary: The new state of the leadership position.
  example: []
  syntax:
    content: public LeadershipPositionState NewState { get; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Services.LeaderElection.LeadershipPositionState
    content.vb: Public Property NewState As LeadershipPositionState
  overload: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState*
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader
  commentId: P:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader
  id: NewLeader
  parent: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
  langs:
  - csharp
  - vb
  name: NewLeader
  nameWithType: LeadershipChangeEventArgs.NewLeader
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NewLeader
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
    startLine: 14
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeaderElection
  summary: The new leader. This value is null if this update is that the previous leader resigned or ended their term.
  example: []
  syntax:
    content: public LeaderElectionCandidate? NewLeader { get; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionCandidate
    content.vb: Public Property NewLeader As LeaderElectionCandidate
  overload: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader*
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp
  commentId: P:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp
  id: Timestamp
  parent: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
  langs:
  - csharp
  - vb
  name: Timestamp
  nameWithType: LeadershipChangeEventArgs.Timestamp
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp
  type: Property
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Timestamp
    path: ../../dotnet/src/Azure.Iot.Operations.Services/LeaderElection/LeadershipChangeEventArgs.cs
    startLine: 19
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.LeaderElection
  summary: The timestamp associated with this event.
  example: []
  syntax:
    content: public HybridLogicalClock Timestamp { get; }
    parameters: []
    return:
      type: Azure.Iot.Operations.Protocol.HybridLogicalClock
    content.vb: Public Property Timestamp As HybridLogicalClock
  overload: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp*
references:
- uid: Azure.Iot.Operations.Services.LeaderElection
  commentId: N:Azure.Iot.Operations.Services.LeaderElection
  href: Azure.html
  name: Azure.Iot.Operations.Services.LeaderElection
  nameWithType: Azure.Iot.Operations.Services.LeaderElection
  fullName: Azure.Iot.Operations.Services.LeaderElection
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.LeaderElection
    name: LeaderElection
    href: Azure.Iot.Operations.Services.LeaderElection.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.LeaderElection
    name: LeaderElection
    href: Azure.Iot.Operations.Services.LeaderElection.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.EventArgs
  commentId: T:System.EventArgs
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.eventargs
  name: EventArgs
  nameWithType: EventArgs
  fullName: System.EventArgs
- uid: System.EventArgs.Empty
  commentId: F:System.EventArgs.Empty
  parent: System.EventArgs
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.eventargs.empty
  name: Empty
  nameWithType: EventArgs.Empty
  fullName: System.EventArgs.Empty
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState*
  commentId: Overload:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState
  href: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.html#Azure_Iot_Operations_Services_LeaderElection_LeadershipChangeEventArgs_NewState
  name: NewState
  nameWithType: LeadershipChangeEventArgs.NewState
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewState
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipPositionState
  commentId: T:Azure.Iot.Operations.Services.LeaderElection.LeadershipPositionState
  parent: Azure.Iot.Operations.Services.LeaderElection
  href: Azure.Iot.Operations.Services.LeaderElection.LeadershipPositionState.html
  name: LeadershipPositionState
  nameWithType: LeadershipPositionState
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipPositionState
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader*
  commentId: Overload:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader
  href: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.html#Azure_Iot_Operations_Services_LeaderElection_LeadershipChangeEventArgs_NewLeader
  name: NewLeader
  nameWithType: LeadershipChangeEventArgs.NewLeader
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.NewLeader
- uid: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionCandidate
  commentId: T:Azure.Iot.Operations.Services.LeaderElection.LeaderElectionCandidate
  parent: Azure.Iot.Operations.Services.LeaderElection
  href: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionCandidate.html
  name: LeaderElectionCandidate
  nameWithType: LeaderElectionCandidate
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionCandidate
- uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp*
  commentId: Overload:Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp
  href: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.html#Azure_Iot_Operations_Services_LeaderElection_LeadershipChangeEventArgs_Timestamp
  name: Timestamp
  nameWithType: LeadershipChangeEventArgs.Timestamp
  fullName: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs.Timestamp
- uid: Azure.Iot.Operations.Protocol.HybridLogicalClock
  commentId: T:Azure.Iot.Operations.Protocol.HybridLogicalClock
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.HybridLogicalClock.html
  name: HybridLogicalClock
  nameWithType: HybridLogicalClock
  fullName: Azure.Iot.Operations.Protocol.HybridLogicalClock
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
