### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Retry
  commentId: N:Azure.Iot.Operations.Protocol.Retry
  id: Retry
  parent: Azure.Iot.Operations.Protocol
  children:
  - Azure.Iot.Operations.Protocol.Retry.ExponentialBackoffRetryPolicy
  - Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  - Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  - Azure.Iot.Operations.Protocol.Retry.RetryExpiredException
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Protocol.Retry
  nameWithType: Azure.Iot.Operations.Protocol.Retry
  fullName: Azure.Iot.Operations.Protocol.Retry
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Protocol
references:
- uid: Azure.Iot.Operations.Protocol.Retry.ExponentialBackoffRetryPolicy
  commentId: T:Azure.Iot.Operations.Protocol.Retry.ExponentialBackoffRetryPolicy
  href: Azure.Iot.Operations.Protocol.Retry.ExponentialBackoffRetryPolicy.html
  name: ExponentialBackoffRetryPolicy
  nameWithType: ExponentialBackoffRetryPolicy
  fullName: Azure.Iot.Operations.Protocol.Retry.ExponentialBackoffRetryPolicy
- uid: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  commentId: T:Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  parent: Azure.Iot.Operations.Protocol.Retry
  href: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.html
  name: IRetryPolicy
  nameWithType: IRetryPolicy
  fullName: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
- uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  commentId: T:Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  href: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.html
  name: NoRetryPolicy
  nameWithType: NoRetryPolicy
  fullName: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
- uid: Azure.Iot.Operations.Protocol.Retry.RetryExpiredException
  commentId: T:Azure.Iot.Operations.Protocol.Retry.RetryExpiredException
  href: Azure.Iot.Operations.Protocol.Retry.RetryExpiredException.html
  name: RetryExpiredException
  nameWithType: RetryExpiredException
  fullName: Azure.Iot.Operations.Protocol.Retry.RetryExpiredException
- uid: Azure.Iot.Operations.Protocol.Retry
  commentId: N:Azure.Iot.Operations.Protocol.Retry
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Retry
  nameWithType: Azure.Iot.Operations.Protocol.Retry
  fullName: Azure.Iot.Operations.Protocol.Retry
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Retry
    name: Retry
    href: Azure.Iot.Operations.Protocol.Retry.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Retry
    name: Retry
    href: Azure.Iot.Operations.Protocol.Retry.html
