### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  id: MqttPendingMessagesOverflowStrategy
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropNewMessage
  - Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropOldestQueuedMessage
  langs:
  - csharp
  - vb
  name: MqttPendingMessagesOverflowStrategy
  nameWithType: MqttPendingMessagesOverflowStrategy
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPendingMessagesOverflowStrategy.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttPendingMessagesOverflowStrategy
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPendingMessagesOverflowStrategy.cs
    startLine: 3
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttPendingMessagesOverflowStrategy
    content.vb: Public Enum MqttPendingMessagesOverflowStrategy
- uid: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropOldestQueuedMessage
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropOldestQueuedMessage
  id: DropOldestQueuedMessage
  parent: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  langs:
  - csharp
  - vb
  name: DropOldestQueuedMessage
  nameWithType: MqttPendingMessagesOverflowStrategy.DropOldestQueuedMessage
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropOldestQueuedMessage
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPendingMessagesOverflowStrategy.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: DropOldestQueuedMessage
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPendingMessagesOverflowStrategy.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: DropOldestQueuedMessage = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
- uid: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropNewMessage
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropNewMessage
  id: DropNewMessage
  parent: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  langs:
  - csharp
  - vb
  name: DropNewMessage
  nameWithType: MqttPendingMessagesOverflowStrategy.DropNewMessage
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.DropNewMessage
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPendingMessagesOverflowStrategy.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: DropNewMessage
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttPendingMessagesOverflowStrategy.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: DropNewMessage = 1
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy.html
  name: MqttPendingMessagesOverflowStrategy
  nameWithType: MqttPendingMessagesOverflowStrategy
  fullName: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
