### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem
  commentId: T:Azure.Iot.Operations.Protocol.IDelayableQueueItem
  id: IDelayableQueueItem
  parent: Azure.Iot.Operations.Protocol
  children:
  - Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady
  - Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady
  langs:
  - csharp
  - vb
  name: IDelayableQueueItem
  nameWithType: IDelayableQueueItem
  fullName: Azure.Iot.Operations.Protocol.IDelayableQueueItem
  type: Interface
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Mqtt/IDelayableQueueItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IDelayableQueueItem
    path: ../../dotnet/src/Azure.Iot.Operations.Mqtt/IDelayableQueueItem.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Mqtt
  namespace: Azure.Iot.Operations.Protocol
  summary: The base interface for all elements used in a BlockingConcurrentDelayableQueue&lt;T&gt;.
  example: []
  syntax:
    content: public interface IDelayableQueueItem
    content.vb: Public Interface IDelayableQueueItem
- uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady
  commentId: M:Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady
  id: IsReady
  parent: Azure.Iot.Operations.Protocol.IDelayableQueueItem
  langs:
  - csharp
  - vb
  name: IsReady()
  nameWithType: IDelayableQueueItem.IsReady()
  fullName: Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady()
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Mqtt/IDelayableQueueItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: IsReady
    path: ../../dotnet/src/Azure.Iot.Operations.Mqtt/IDelayableQueueItem.cs
    startLine: 11
  assemblies:
  - Azure.Iot.Operations.Mqtt
  namespace: Azure.Iot.Operations.Protocol
  summary: Check if this queue item is ready to be dequeued.
  example: []
  syntax:
    content: bool IsReady()
    return:
      type: System.Boolean
      description: True if the queue item is ready to be dequeued.
    content.vb: Function IsReady() As Boolean
  overload: Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady*
- uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady
  commentId: M:Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady
  id: MarkAsReady
  parent: Azure.Iot.Operations.Protocol.IDelayableQueueItem
  langs:
  - csharp
  - vb
  name: MarkAsReady()
  nameWithType: IDelayableQueueItem.MarkAsReady()
  fullName: Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady()
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Mqtt/IDelayableQueueItem.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MarkAsReady
    path: ../../dotnet/src/Azure.Iot.Operations.Mqtt/IDelayableQueueItem.cs
    startLine: 16
  assemblies:
  - Azure.Iot.Operations.Mqtt
  namespace: Azure.Iot.Operations.Protocol
  summary: Mark this queue item as ready to be dequeued.
  example: []
  syntax:
    content: void MarkAsReady()
    content.vb: Sub MarkAsReady()
  overload: Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady*
references:
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
- uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady*
  commentId: Overload:Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady
  href: Azure.Iot.Operations.Protocol.IDelayableQueueItem.html#Azure_Iot_Operations_Protocol_IDelayableQueueItem_IsReady
  name: IsReady
  nameWithType: IDelayableQueueItem.IsReady
  fullName: Azure.Iot.Operations.Protocol.IDelayableQueueItem.IsReady
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady*
  commentId: Overload:Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady
  href: Azure.Iot.Operations.Protocol.IDelayableQueueItem.html#Azure_Iot_Operations_Protocol_IDelayableQueueItem_MarkAsReady
  name: MarkAsReady
  nameWithType: IDelayableQueueItem.MarkAsReady
  fullName: Azure.Iot.Operations.Protocol.IDelayableQueueItem.MarkAsReady
