### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations
  id: Azure.Iot.Operations
  children:
  - Azure.Iot.Operations.Mqtt
  - Azure.Iot.Operations.Protocol
  - Azure.Iot.Operations.Services
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations
  type: Namespace
references:
- uid: Azure.Iot.Operations.Mqtt
  commentId: N:Azure.Iot.Operations.Mqtt
  href: Azure.html
  name: Azure.Iot.Operations.Mqtt
  nameWithType: Azure.Iot.Operations.Mqtt
  fullName: Azure.Iot.Operations.Mqtt
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
- uid: Azure.Iot.Operations.Services
  isExternal: true
