### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Mqtt.Session.Exceptions
  commentId: N:Azure.Iot.Operations.Mqtt.Session.Exceptions
  id: Exceptions
  parent: Azure.Iot.Operations.Mqtt.Session
  children:
  - Azure.Iot.Operations.Mqtt.Session.Exceptions.MessagePurgedFromQueueException
  - Azure.Iot.Operations.Mqtt.Session.Exceptions.MqttSessionExpiredException
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Mqtt.Session.Exceptions
  nameWithType: Azure.Iot.Operations.Mqtt.Session.Exceptions
  fullName: Azure.Iot.Operations.Mqtt.Session.Exceptions
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Mqtt
references:
- uid: Azure.Iot.Operations.Mqtt.Session.Exceptions.MessagePurgedFromQueueException
  commentId: T:Azure.Iot.Operations.Mqtt.Session.Exceptions.MessagePurgedFromQueueException
  href: Azure.Iot.Operations.Mqtt.Session.Exceptions.MessagePurgedFromQueueException.html
  name: MessagePurgedFromQueueException
  nameWithType: MessagePurgedFromQueueException
  fullName: Azure.Iot.Operations.Mqtt.Session.Exceptions.MessagePurgedFromQueueException
- uid: Azure.Iot.Operations.Mqtt.Session.Exceptions.MqttSessionExpiredException
  commentId: T:Azure.Iot.Operations.Mqtt.Session.Exceptions.MqttSessionExpiredException
  href: Azure.Iot.Operations.Mqtt.Session.Exceptions.MqttSessionExpiredException.html
  name: MqttSessionExpiredException
  nameWithType: MqttSessionExpiredException
  fullName: Azure.Iot.Operations.Mqtt.Session.Exceptions.MqttSessionExpiredException
