### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  id: MqttClientUnsubscribeReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.ImplementationSpecificError
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NoSubscriptionExisted
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NotAuthorized
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.PacketIdentifierInUse
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.Success
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.TopicFilterInvalid
  - Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.UnspecifiedError
  langs:
  - csharp
  - vb
  name: MqttClientUnsubscribeReasonCode
  nameWithType: MqttClientUnsubscribeReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttClientUnsubscribeReasonCode
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttClientUnsubscribeReasonCode
    content.vb: Public Enum MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.Success
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.Success
  id: Success
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: Success
  nameWithType: MqttClientUnsubscribeReasonCode.Success
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.Success
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Success
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: Success = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NoSubscriptionExisted
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NoSubscriptionExisted
  id: NoSubscriptionExisted
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: NoSubscriptionExisted
  nameWithType: MqttClientUnsubscribeReasonCode.NoSubscriptionExisted
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NoSubscriptionExisted
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NoSubscriptionExisted
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: NoSubscriptionExisted = 17
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.UnspecifiedError
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.UnspecifiedError
  id: UnspecifiedError
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: UnspecifiedError
  nameWithType: MqttClientUnsubscribeReasonCode.UnspecifiedError
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.UnspecifiedError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnspecifiedError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: UnspecifiedError = 128
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.ImplementationSpecificError
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.ImplementationSpecificError
  id: ImplementationSpecificError
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: ImplementationSpecificError
  nameWithType: MqttClientUnsubscribeReasonCode.ImplementationSpecificError
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.ImplementationSpecificError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ImplementationSpecificError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: ImplementationSpecificError = 131
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NotAuthorized
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NotAuthorized
  id: NotAuthorized
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: NotAuthorized
  nameWithType: MqttClientUnsubscribeReasonCode.NotAuthorized
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.NotAuthorized
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NotAuthorized
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 8
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: NotAuthorized = 135
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.TopicFilterInvalid
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.TopicFilterInvalid
  id: TopicFilterInvalid
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: TopicFilterInvalid
  nameWithType: MqttClientUnsubscribeReasonCode.TopicFilterInvalid
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.TopicFilterInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: TopicFilterInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: TopicFilterInvalid = 143
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.PacketIdentifierInUse
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.PacketIdentifierInUse
  id: PacketIdentifierInUse
  parent: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  langs:
  - csharp
  - vb
  name: PacketIdentifierInUse
  nameWithType: MqttClientUnsubscribeReasonCode.PacketIdentifierInUse
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.PacketIdentifierInUse
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: PacketIdentifierInUse
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttClientUnsubscribeReasonCode.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: PacketIdentifierInUse = 145
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode.html
  name: MqttClientUnsubscribeReasonCode
  nameWithType: MqttClientUnsubscribeReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
