### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  commentId: T:Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  id: AkriMqttErrorKind
  parent: Azure.Iot.Operations.Protocol
  children:
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ArgumentInvalid
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Cancellation
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ConfigurationInvalid
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ExecutionException
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderInvalid
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderMissing
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InternalLogicError
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InvocationException
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.MqttError
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.PayloadInvalid
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.StateInvalid
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Timeout
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnknownError
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedRequestVersion
  - Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedResponseVersion
  langs:
  - csharp
  - vb
  name: AkriMqttErrorKind
  nameWithType: AkriMqttErrorKind
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: AkriMqttErrorKind
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  syntax:
    content: public enum AkriMqttErrorKind
    content.vb: Public Enum AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ConfigurationInvalid
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ConfigurationInvalid
  id: ConfigurationInvalid
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: ConfigurationInvalid
  nameWithType: AkriMqttErrorKind.ConfigurationInvalid
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ConfigurationInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ConfigurationInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: A class property, configuration file, or environment variable has an invalid value.
  example: []
  syntax:
    content: ConfigurationInvalid = 0
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ArgumentInvalid
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ArgumentInvalid
  id: ArgumentInvalid
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: ArgumentInvalid
  nameWithType: AkriMqttErrorKind.ArgumentInvalid
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ArgumentInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ArgumentInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 12
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: A method was called with an invalid argument value.
  example: []
  syntax:
    content: ArgumentInvalid = 1
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderMissing
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderMissing
  id: HeaderMissing
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: HeaderMissing
  nameWithType: AkriMqttErrorKind.HeaderMissing
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderMissing
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: HeaderMissing
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 17
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: A required MQTT header property is missing.
  example: []
  syntax:
    content: HeaderMissing = 2
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderInvalid
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderInvalid
  id: HeaderInvalid
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: HeaderInvalid
  nameWithType: AkriMqttErrorKind.HeaderInvalid
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.HeaderInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: HeaderInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 22
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: An MQTT header property is has an invalid value.
  example: []
  syntax:
    content: HeaderInvalid = 3
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.PayloadInvalid
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.PayloadInvalid
  id: PayloadInvalid
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: PayloadInvalid
  nameWithType: AkriMqttErrorKind.PayloadInvalid
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.PayloadInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: PayloadInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 27
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: MQTT paylod cannot be deserialized.
  example: []
  syntax:
    content: PayloadInvalid = 4
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.StateInvalid
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.StateInvalid
  id: StateInvalid
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: StateInvalid
  nameWithType: AkriMqttErrorKind.StateInvalid
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.StateInvalid
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: StateInvalid
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 32
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: The current program state is invalid vis-a-vis the method that was called.
  example: []
  syntax:
    content: StateInvalid = 5
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InternalLogicError
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InternalLogicError
  id: InternalLogicError
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: InternalLogicError
  nameWithType: AkriMqttErrorKind.InternalLogicError
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InternalLogicError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InternalLogicError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 37
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: The client or service observed a condition that was thought to be impossible.
  example: []
  syntax:
    content: InternalLogicError = 6
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Timeout
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Timeout
  id: Timeout
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: Timeout
  nameWithType: AkriMqttErrorKind.Timeout
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Timeout
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Timeout
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 42
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: An operation was aborted due to timeout.
  example: []
  syntax:
    content: Timeout = 7
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Cancellation
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Cancellation
  id: Cancellation
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: Cancellation
  nameWithType: AkriMqttErrorKind.Cancellation
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.Cancellation
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Cancellation
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 47
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: An operation was canceled.
  example: []
  syntax:
    content: Cancellation = 8
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InvocationException
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InvocationException
  id: InvocationException
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: InvocationException
  nameWithType: AkriMqttErrorKind.InvocationException
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.InvocationException
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InvocationException
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 52
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: The command processor identified an error in the request.
  example: []
  syntax:
    content: InvocationException = 9
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ExecutionException
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ExecutionException
  id: ExecutionException
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: ExecutionException
  nameWithType: AkriMqttErrorKind.ExecutionException
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.ExecutionException
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ExecutionException
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 57
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: The command processor encountered an error while executing the command.
  example: []
  syntax:
    content: ExecutionException = 10
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnknownError
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnknownError
  id: UnknownError
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: UnknownError
  nameWithType: AkriMqttErrorKind.UnknownError
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnknownError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnknownError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 62
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: The client or service caught an unexpected error from a dependent component.
  example: []
  syntax:
    content: UnknownError = 11
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.MqttError
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.MqttError
  id: MqttError
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: MqttError
  nameWithType: AkriMqttErrorKind.MqttError
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.MqttError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttError
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 67
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: The MQTT communication encountered an error and failed. The exception message should be inspected for additional information.
  example: []
  syntax:
    content: MqttError = 12
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedRequestVersion
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedRequestVersion
  id: UnsupportedRequestVersion
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: UnsupportedRequestVersion
  nameWithType: AkriMqttErrorKind.UnsupportedRequestVersion
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedRequestVersion
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnsupportedRequestVersion
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 73
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: >-
    The request failed because the command executor did not support the protocol version specified by this request

    or this request specified a malformed protocol version.
  example: []
  syntax:
    content: UnsupportedRequestVersion = 13
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedResponseVersion
  commentId: F:Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedResponseVersion
  id: UnsupportedResponseVersion
  parent: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  langs:
  - csharp
  - vb
  name: UnsupportedResponseVersion
  nameWithType: AkriMqttErrorKind.UnsupportedResponseVersion
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.UnsupportedResponseVersion
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnsupportedResponseVersion
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/AkriMqttErrorKind.cs
    startLine: 79
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol
  summary: >-
    The request failed because the command executor's response to this request specified a protocol

    version not supported by this command invoker or specified a malformed protocol version.
  example: []
  syntax:
    content: UnsupportedResponseVersion = 14
    return:
      type: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
references:
- uid: Azure.Iot.Operations.Protocol
  commentId: N:Azure.Iot.Operations.Protocol
  href: Azure.html
  name: Azure.Iot.Operations.Protocol
  nameWithType: Azure.Iot.Operations.Protocol
  fullName: Azure.Iot.Operations.Protocol
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
- uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  commentId: T:Azure.Iot.Operations.Protocol.AkriMqttErrorKind
  parent: Azure.Iot.Operations.Protocol
  href: Azure.Iot.Operations.Protocol.AkriMqttErrorKind.html
  name: AkriMqttErrorKind
  nameWithType: AkriMqttErrorKind
  fullName: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
