### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Connection
  commentId: N:Azure.Iot.Operations.Protocol.Connection
  id: Connection
  parent: Azure.Iot.Operations.Protocol
  children:
  - Azure.Iot.Operations.Protocol.Connection.MqttConnectionSettings
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Protocol.Connection
  nameWithType: Azure.Iot.Operations.Protocol.Connection
  fullName: Azure.Iot.Operations.Protocol.Connection
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Protocol
references:
- uid: Azure.Iot.Operations.Protocol.Connection.MqttConnectionSettings
  commentId: T:Azure.Iot.Operations.Protocol.Connection.MqttConnectionSettings
  parent: Azure.Iot.Operations.Protocol.Connection
  href: Azure.Iot.Operations.Protocol.Connection.MqttConnectionSettings.html
  name: MqttConnectionSettings
  nameWithType: MqttConnectionSettings
  fullName: Azure.Iot.Operations.Protocol.Connection.MqttConnectionSettings
- uid: Azure.Iot.Operations.Protocol.Connection
  commentId: N:Azure.Iot.Operations.Protocol.Connection
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Connection
  nameWithType: Azure.Iot.Operations.Protocol.Connection
  fullName: Azure.Iot.Operations.Protocol.Connection
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Connection
    name: Connection
    href: Azure.Iot.Operations.Protocol.Connection.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Connection
    name: Connection
    href: Azure.Iot.Operations.Protocol.Connection.html
