### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  id: StateStoreErrorKind
  parent: Azure.Iot.Operations.Services.StateStore
  children:
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.AIOProtocolError
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.InvalidArgument
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.KeyLengthZero
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.SerializationError
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.ServiceError
  - Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.UnexpectedPayload
  langs:
  - csharp
  - vb
  name: StateStoreErrorKind
  nameWithType: StateStoreErrorKind
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: StateStoreErrorKind
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: public enum StateStoreErrorKind
    content.vb: Public Enum StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.AIOProtocolError
  commentId: F:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.AIOProtocolError
  id: AIOProtocolError
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  langs:
  - csharp
  - vb
  name: AIOProtocolError
  nameWithType: StateStoreErrorKind.AIOProtocolError
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.AIOProtocolError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: AIOProtocolError
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 10
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: AIOProtocolError = 0
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.ServiceError
  commentId: F:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.ServiceError
  id: ServiceError
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  langs:
  - csharp
  - vb
  name: ServiceError
  nameWithType: StateStoreErrorKind.ServiceError
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.ServiceError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ServiceError
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 14
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: ServiceError = 1
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.KeyLengthZero
  commentId: F:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.KeyLengthZero
  id: KeyLengthZero
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  langs:
  - csharp
  - vb
  name: KeyLengthZero
  nameWithType: StateStoreErrorKind.KeyLengthZero
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.KeyLengthZero
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: KeyLengthZero
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 18
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: KeyLengthZero = 2
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.SerializationError
  commentId: F:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.SerializationError
  id: SerializationError
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  langs:
  - csharp
  - vb
  name: SerializationError
  nameWithType: StateStoreErrorKind.SerializationError
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.SerializationError
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SerializationError
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 22
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: SerializationError = 3
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.InvalidArgument
  commentId: F:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.InvalidArgument
  id: InvalidArgument
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  langs:
  - csharp
  - vb
  name: InvalidArgument
  nameWithType: StateStoreErrorKind.InvalidArgument
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.InvalidArgument
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: InvalidArgument
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 26
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: InvalidArgument = 4
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.UnexpectedPayload
  commentId: F:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.UnexpectedPayload
  id: UnexpectedPayload
  parent: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  langs:
  - csharp
  - vb
  name: UnexpectedPayload
  nameWithType: StateStoreErrorKind.UnexpectedPayload
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.UnexpectedPayload
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: UnexpectedPayload
    path: ../../dotnet/src/Azure.Iot.Operations.Services/StateStore/StateStoreOperationException.cs
    startLine: 30
  assemblies:
  - Azure.Iot.Operations.Services
  namespace: Azure.Iot.Operations.Services.StateStore
  syntax:
    content: UnexpectedPayload = 5
    return:
      type: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
references:
- uid: Azure.Iot.Operations.Services.StateStore
  commentId: N:Azure.Iot.Operations.Services.StateStore
  href: Azure.html
  name: Azure.Iot.Operations.Services.StateStore
  nameWithType: Azure.Iot.Operations.Services.StateStore
  fullName: Azure.Iot.Operations.Services.StateStore
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Services
    name: Services
    href: Azure.Iot.Operations.Services.html
  - name: .
  - uid: Azure.Iot.Operations.Services.StateStore
    name: StateStore
    href: Azure.Iot.Operations.Services.StateStore.html
- uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  commentId: T:Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
  parent: Azure.Iot.Operations.Services.StateStore
  href: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind.html
  name: StateStoreErrorKind
  nameWithType: StateStoreErrorKind
  fullName: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
