### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Mqtt.Session
  commentId: N:Azure.Iot.Operations.Mqtt.Session
  id: Session
  parent: Azure.Iot.Operations.Mqtt
  children:
  - Azure.Iot.Operations.Mqtt.Session.Exceptions
  - Azure.Iot.Operations.Mqtt.Session.MqttSessionClient
  - Azure.Iot.Operations.Mqtt.Session.MqttSessionClientOptions
  langs:
  - csharp
  - vb
  name: Azure.Iot.Operations.Mqtt.Session
  nameWithType: Azure.Iot.Operations.Mqtt.Session
  fullName: Azure.Iot.Operations.Mqtt.Session
  type: Namespace
  assemblies:
  - Azure.Iot.Operations.Mqtt
references:
- uid: Azure.Iot.Operations.Mqtt.Session.Exceptions
  commentId: N:Azure.Iot.Operations.Mqtt.Session.Exceptions
  href: Azure.html
  name: Azure.Iot.Operations.Mqtt.Session.Exceptions
  nameWithType: Azure.Iot.Operations.Mqtt.Session.Exceptions
  fullName: Azure.Iot.Operations.Mqtt.Session.Exceptions
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session
    name: Session
    href: Azure.Iot.Operations.Mqtt.Session.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session.Exceptions
    name: Exceptions
    href: Azure.Iot.Operations.Mqtt.Session.Exceptions.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session
    name: Session
    href: Azure.Iot.Operations.Mqtt.Session.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session.Exceptions
    name: Exceptions
    href: Azure.Iot.Operations.Mqtt.Session.Exceptions.html
- uid: Azure.Iot.Operations.Mqtt.Session.MqttSessionClient
  commentId: T:Azure.Iot.Operations.Mqtt.Session.MqttSessionClient
  href: Azure.Iot.Operations.Mqtt.Session.MqttSessionClient.html
  name: MqttSessionClient
  nameWithType: MqttSessionClient
  fullName: Azure.Iot.Operations.Mqtt.Session.MqttSessionClient
- uid: Azure.Iot.Operations.Mqtt.Session.MqttSessionClientOptions
  commentId: T:Azure.Iot.Operations.Mqtt.Session.MqttSessionClientOptions
  parent: Azure.Iot.Operations.Mqtt.Session
  href: Azure.Iot.Operations.Mqtt.Session.MqttSessionClientOptions.html
  name: MqttSessionClientOptions
  nameWithType: MqttSessionClientOptions
  fullName: Azure.Iot.Operations.Mqtt.Session.MqttSessionClientOptions
- uid: Azure.Iot.Operations.Mqtt.Session
  commentId: N:Azure.Iot.Operations.Mqtt.Session
  href: Azure.html
  name: Azure.Iot.Operations.Mqtt.Session
  nameWithType: Azure.Iot.Operations.Mqtt.Session
  fullName: Azure.Iot.Operations.Mqtt.Session
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session
    name: Session
    href: Azure.Iot.Operations.Mqtt.Session.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    href: Azure.Iot.Operations.Mqtt.html
  - name: .
  - uid: Azure.Iot.Operations.Mqtt.Session
    name: Session
    href: Azure.Iot.Operations.Mqtt.Session.html
