### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  commentId: T:Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  id: NoRetryPolicy
  parent: Azure.Iot.Operations.Protocol.Retry
  children:
  - Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.#ctor
  - Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  langs:
  - csharp
  - vb
  name: NoRetryPolicy
  nameWithType: NoRetryPolicy
  fullName: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Retry/NoRetryPolicy.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: NoRetryPolicy
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Retry/NoRetryPolicy.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Retry
  summary: A retry policy that will never retry.
  example: []
  syntax:
    content: 'public class NoRetryPolicy : IRetryPolicy'
    content.vb: Public Class NoRetryPolicy Implements IRetryPolicy
  inheritance:
  - System.Object
  implements:
  - Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.#ctor
  commentId: M:Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.#ctor
  id: '#ctor'
  parent: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  langs:
  - csharp
  - vb
  name: NoRetryPolicy()
  nameWithType: NoRetryPolicy.NoRetryPolicy()
  fullName: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.NoRetryPolicy()
  type: Constructor
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Retry/NoRetryPolicy.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: .ctor
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Retry/NoRetryPolicy.cs
    startLine: 12
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Retry
  summary: Creates a retry policy that will never retry.
  example: []
  syntax:
    content: public NoRetryPolicy()
    content.vb: Public Sub New()
  overload: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.#ctor*
  nameWithType.vb: NoRetryPolicy.New()
  fullName.vb: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.New()
  name.vb: New()
- uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  commentId: M:Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  id: ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  parent: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
  langs:
  - csharp
  - vb
  name: ShouldRetry(uint, Exception, out TimeSpan)
  nameWithType: NoRetryPolicy.ShouldRetry(uint, Exception, out TimeSpan)
  fullName: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry(uint, System.Exception, out System.TimeSpan)
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Retry/NoRetryPolicy.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ShouldRetry
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Retry/NoRetryPolicy.cs
    startLine: 17
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Retry
  summary: >-
    Method called by the client when an operation fails to determine if a retry should be attempted,

    and how long to wait until retrying the operation.
  example:
  - >-
    <pre><code class="lang-csharp">class CustomRetryPolicy : IRetryPolicy

    {
        public bool ShouldRetry(uint currentRetryCount, Exception lastException, out TimeSpan retryDelay)
        {
            // Add custom logic as needed upon determining if it should retry and set the retryDelay out parameter
        }
    }</code></pre>
  syntax:
    content: public bool ShouldRetry(uint currentRetryCount, Exception lastException, out TimeSpan retryDelay)
    parameters:
    - id: currentRetryCount
      type: System.UInt32
      description: The number of times the current operation has been attempted.
    - id: lastException
      type: System.Exception
      description: The exception that prompted this retry policy check.
    - id: retryDelay
      type: System.TimeSpan
      description: Set this to the desired time to delay before the next attempt.
    return:
      type: System.Boolean
      description: True if the operation should be retried; otherwise false.
    content.vb: Public Function ShouldRetry(currentRetryCount As UInteger, lastException As Exception, retryDelay As TimeSpan) As Boolean
  overload: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry*
  implements:
  - Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  nameWithType.vb: NoRetryPolicy.ShouldRetry(UInteger, Exception, TimeSpan)
  fullName.vb: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry(UInteger, System.Exception, System.TimeSpan)
  name.vb: ShouldRetry(UInteger, Exception, TimeSpan)
references:
- uid: Azure.Iot.Operations.Protocol.Retry
  commentId: N:Azure.Iot.Operations.Protocol.Retry
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Retry
  nameWithType: Azure.Iot.Operations.Protocol.Retry
  fullName: Azure.Iot.Operations.Protocol.Retry
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Retry
    name: Retry
    href: Azure.Iot.Operations.Protocol.Retry.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Retry
    name: Retry
    href: Azure.Iot.Operations.Protocol.Retry.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  commentId: T:Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  parent: Azure.Iot.Operations.Protocol.Retry
  href: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.html
  name: IRetryPolicy
  nameWithType: IRetryPolicy
  fullName: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.#ctor*
  commentId: Overload:Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.#ctor
  href: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.html#Azure_Iot_Operations_Protocol_Retry_NoRetryPolicy__ctor
  name: NoRetryPolicy
  nameWithType: NoRetryPolicy.NoRetryPolicy
  fullName: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.NoRetryPolicy
  nameWithType.vb: NoRetryPolicy.New
  fullName.vb: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.New
  name.vb: New
- uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry*
  commentId: Overload:Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry
  href: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.html#Azure_Iot_Operations_Protocol_Retry_NoRetryPolicy_ShouldRetry_System_UInt32_System_Exception_System_TimeSpan__
  name: ShouldRetry
  nameWithType: NoRetryPolicy.ShouldRetry
  fullName: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy.ShouldRetry
- uid: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  commentId: M:Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
  parent: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
  isExternal: true
  href: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.html#Azure_Iot_Operations_Protocol_Retry_IRetryPolicy_ShouldRetry_System_UInt32_System_Exception_System_TimeSpan__
  name: ShouldRetry(uint, Exception, out TimeSpan)
  nameWithType: IRetryPolicy.ShouldRetry(uint, Exception, out TimeSpan)
  fullName: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(uint, System.Exception, out System.TimeSpan)
  nameWithType.vb: IRetryPolicy.ShouldRetry(UInteger, Exception, TimeSpan)
  fullName.vb: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(UInteger, System.Exception, System.TimeSpan)
  name.vb: ShouldRetry(UInteger, Exception, TimeSpan)
  spec.csharp:
  - uid: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
    name: ShouldRetry
    href: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.html#Azure_Iot_Operations_Protocol_Retry_IRetryPolicy_ShouldRetry_System_UInt32_System_Exception_System_TimeSpan__
  - name: (
  - uid: System.UInt32
    name: uint
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.uint32
  - name: ','
  - name: " "
  - uid: System.Exception
    name: Exception
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.exception
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: System.TimeSpan
    name: TimeSpan
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.timespan
  - name: )
  spec.vb:
  - uid: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.ShouldRetry(System.UInt32,System.Exception,System.TimeSpan@)
    name: ShouldRetry
    href: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy.html#Azure_Iot_Operations_Protocol_Retry_IRetryPolicy_ShouldRetry_System_UInt32_System_Exception_System_TimeSpan__
  - name: (
  - uid: System.UInt32
    name: UInteger
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.uint32
  - name: ','
  - name: " "
  - uid: System.Exception
    name: Exception
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.exception
  - name: ','
  - name: " "
  - uid: System.TimeSpan
    name: TimeSpan
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.timespan
  - name: )
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.uint32
  name: uint
  nameWithType: uint
  fullName: uint
  nameWithType.vb: UInteger
  fullName.vb: UInteger
  name.vb: UInteger
- uid: System.Exception
  commentId: T:System.Exception
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.exception
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
