### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  id: MqttAuthenticateReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ContinueAuthentication
  - Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ReAuthenticate
  - Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.Success
  langs:
  - csharp
  - vb
  name: MqttAuthenticateReasonCode
  nameWithType: MqttAuthenticateReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  type: Enum
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttAuthenticateReasonCode
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
    startLine: 3
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public enum MqttAuthenticateReasonCode
    content.vb: Public Enum MqttAuthenticateReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.Success
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.Success
  id: Success
  parent: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  langs:
  - csharp
  - vb
  name: Success
  nameWithType: MqttAuthenticateReasonCode.Success
  fullName: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.Success
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Success
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: Success = 0
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ContinueAuthentication
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ContinueAuthentication
  id: ContinueAuthentication
  parent: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  langs:
  - csharp
  - vb
  name: ContinueAuthentication
  nameWithType: MqttAuthenticateReasonCode.ContinueAuthentication
  fullName: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ContinueAuthentication
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ContinueAuthentication
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: ContinueAuthentication = 24
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
- uid: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ReAuthenticate
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ReAuthenticate
  id: ReAuthenticate
  parent: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  langs:
  - csharp
  - vb
  name: ReAuthenticate
  nameWithType: MqttAuthenticateReasonCode.ReAuthenticate
  fullName: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.ReAuthenticate
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ReAuthenticate
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttAuthenticateReasonCode.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: ReAuthenticate = 25
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode.html
  name: MqttAuthenticateReasonCode
  nameWithType: MqttAuthenticateReasonCode
  fullName: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
