### YamlMime:ManagedReference
items:
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  id: MqttTopicFilterComparer
  parent: Azure.Iot.Operations.Protocol.Models
  children:
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare(System.String,System.String)
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.LevelSeparator
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.MultiLevelWildcard
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.ReservedTopicPrefix
  - Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.SingleLevelWildcard
  langs:
  - csharp
  - vb
  name: MqttTopicFilterComparer
  nameWithType: MqttTopicFilterComparer
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  type: Class
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MqttTopicFilterComparer
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
    startLine: 2
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public static class MqttTopicFilterComparer
    content.vb: Public Module MqttTopicFilterComparer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.LevelSeparator
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.LevelSeparator
  id: LevelSeparator
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  langs:
  - csharp
  - vb
  name: LevelSeparator
  nameWithType: MqttTopicFilterComparer.LevelSeparator
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.LevelSeparator
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: LevelSeparator
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
    startLine: 4
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public const char LevelSeparator = '/'
    return:
      type: System.Char
    content.vb: Public Const LevelSeparator As Char = "/"c
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.MultiLevelWildcard
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.MultiLevelWildcard
  id: MultiLevelWildcard
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  langs:
  - csharp
  - vb
  name: MultiLevelWildcard
  nameWithType: MqttTopicFilterComparer.MultiLevelWildcard
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.MultiLevelWildcard
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: MultiLevelWildcard
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
    startLine: 5
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public const char MultiLevelWildcard = '#'
    return:
      type: System.Char
    content.vb: Public Const MultiLevelWildcard As Char = "#"c
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.SingleLevelWildcard
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.SingleLevelWildcard
  id: SingleLevelWildcard
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  langs:
  - csharp
  - vb
  name: SingleLevelWildcard
  nameWithType: MqttTopicFilterComparer.SingleLevelWildcard
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.SingleLevelWildcard
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: SingleLevelWildcard
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
    startLine: 6
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public const char SingleLevelWildcard = '+'
    return:
      type: System.Char
    content.vb: Public Const SingleLevelWildcard As Char = "+"c
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.ReservedTopicPrefix
  commentId: F:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.ReservedTopicPrefix
  id: ReservedTopicPrefix
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  langs:
  - csharp
  - vb
  name: ReservedTopicPrefix
  nameWithType: MqttTopicFilterComparer.ReservedTopicPrefix
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.ReservedTopicPrefix
  type: Field
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: ReservedTopicPrefix
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
    startLine: 7
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public const char ReservedTopicPrefix = '$'
    return:
      type: System.Char
    content.vb: Public Const ReservedTopicPrefix As Char = "$"c
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare(System.String,System.String)
  commentId: M:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare(System.String,System.String)
  id: Compare(System.String,System.String)
  parent: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
  langs:
  - csharp
  - vb
  name: Compare(string, string)
  nameWithType: MqttTopicFilterComparer.Compare(string, string)
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare(string, string)
  type: Method
  source:
    remote:
      path: dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
      branch: docfx
      repo: https://github.com/ryanwinterms/iot-operations-sdks
    id: Compare
    path: ../../dotnet/src/Azure.Iot.Operations.Protocol/Models/MqttTopicFilterComparer.cs
    startLine: 9
  assemblies:
  - Azure.Iot.Operations.Protocol
  namespace: Azure.Iot.Operations.Protocol.Models
  syntax:
    content: public static MqttTopicFilterCompareResult Compare(string topic, string filter)
    parameters:
    - id: topic
      type: System.String
    - id: filter
      type: System.String
    return:
      type: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
    content.vb: Public Shared Function Compare(topic As String, filter As String) As MqttTopicFilterCompareResult
  overload: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare*
  nameWithType.vb: MqttTopicFilterComparer.Compare(String, String)
  fullName.vb: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare(String, String)
  name.vb: Compare(String, String)
references:
- uid: Azure.Iot.Operations.Protocol.Models
  commentId: N:Azure.Iot.Operations.Protocol.Models
  href: Azure.html
  name: Azure.Iot.Operations.Protocol.Models
  nameWithType: Azure.Iot.Operations.Protocol.Models
  fullName: Azure.Iot.Operations.Protocol.Models
  spec.csharp:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
  spec.vb:
  - uid: Azure
    name: Azure
    href: Azure.html
  - name: .
  - uid: Azure.Iot
    name: Iot
    href: Azure.Iot.html
  - name: .
  - uid: Azure.Iot.Operations
    name: Operations
    href: Azure.Iot.Operations.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    href: Azure.Iot.Operations.Protocol.html
  - name: .
  - uid: Azure.Iot.Operations.Protocol.Models
    name: Models
    href: Azure.Iot.Operations.Protocol.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Char
  commentId: T:System.Char
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.char
  name: char
  nameWithType: char
  fullName: char
  nameWithType.vb: Char
  fullName.vb: Char
  name.vb: Char
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare*
  commentId: Overload:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare
  href: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.html#Azure_Iot_Operations_Protocol_Models_MqttTopicFilterComparer_Compare_System_String_System_String_
  name: Compare
  nameWithType: MqttTopicFilterComparer.Compare
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer.Compare
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  commentId: T:Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
  parent: Azure.Iot.Operations.Protocol.Models
  href: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult.html
  name: MqttTopicFilterCompareResult
  nameWithType: MqttTopicFilterCompareResult
  fullName: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
