### YamlMime:TableOfContent
items:
- uid: Azure.Iot.Operations
  name: Azure.Iot.Operations
  items:
  - uid: Azure.Iot.Operations.Mqtt
    name: Mqtt
    items:
    - uid: Azure.Iot.Operations.Mqtt.Session
      name: Session
      items:
      - uid: Azure.Iot.Operations.Mqtt.Session.Exceptions
        name: Exceptions
        items:
        - uid: Azure.Iot.Operations.Mqtt.Session.Exceptions.MessagePurgedFromQueueException
          name: MessagePurgedFromQueueException
        - uid: Azure.Iot.Operations.Mqtt.Session.Exceptions.MqttSessionExpiredException
          name: MqttSessionExpiredException
      - uid: Azure.Iot.Operations.Mqtt.Session.MqttSessionClient
        name: MqttSessionClient
      - uid: Azure.Iot.Operations.Mqtt.Session.MqttSessionClientOptions
        name: MqttSessionClientOptions
    - uid: Azure.Iot.Operations.Mqtt.MqttConnectingFailedException
      name: MqttConnectingFailedException
    - uid: Azure.Iot.Operations.Mqtt.MqttNetTraceLogger
      name: MqttNetTraceLogger
    - uid: Azure.Iot.Operations.Mqtt.OrderedAckMqttClient
      name: OrderedAckMqttClient
  - uid: Azure.Iot.Operations.Protocol
    name: Protocol
    items:
    - uid: Azure.Iot.Operations.Protocol.Connection
      name: Connection
      items:
      - uid: Azure.Iot.Operations.Protocol.Connection.MqttConnectionSettings
        name: MqttConnectionSettings
    - uid: Azure.Iot.Operations.Protocol.Events
      name: Events
      items:
      - uid: Azure.Iot.Operations.Protocol.Events.MqttApplicationMessageReceivedEventArgs
        name: MqttApplicationMessageReceivedEventArgs
      - uid: Azure.Iot.Operations.Protocol.Events.MqttClientConnectedEventArgs
        name: MqttClientConnectedEventArgs
      - uid: Azure.Iot.Operations.Protocol.Events.MqttClientDisconnectedEventArgs
        name: MqttClientDisconnectedEventArgs
    - uid: Azure.Iot.Operations.Protocol.Models
      name: Models
      items:
      - uid: Azure.Iot.Operations.Protocol.Models.DefaultMqttCertificatesProvider
        name: DefaultMqttCertificatesProvider
      - uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCertificatesProvider
        name: IMqttClientCertificatesProvider
      - uid: Azure.Iot.Operations.Protocol.Models.IMqttClientChannelOptions
        name: IMqttClientChannelOptions
      - uid: Azure.Iot.Operations.Protocol.Models.IMqttClientCredentialsProvider
        name: IMqttClientCredentialsProvider
      - uid: Azure.Iot.Operations.Protocol.Models.IMqttExtendedAuthenticationExchangeHandler
        name: IMqttExtendedAuthenticationExchangeHandler
      - uid: Azure.Iot.Operations.Protocol.Models.MqttApplicationMessage
        name: MqttApplicationMessage
      - uid: Azure.Iot.Operations.Protocol.Models.MqttApplicationMessageReceivedReasonCode
        name: MqttApplicationMessageReceivedReasonCode
      - uid: Azure.Iot.Operations.Protocol.Models.MqttAuthPacket
        name: MqttAuthPacket
      - uid: Azure.Iot.Operations.Protocol.Models.MqttAuthenticateReasonCode
        name: MqttAuthenticateReasonCode
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientCertificateSelectionEventArgs
        name: MqttClientCertificateSelectionEventArgs
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientCertificateValidationEventArgs
        name: MqttClientCertificateValidationEventArgs
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientConnectResult
        name: MqttClientConnectResult
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientConnectResultCode
        name: MqttClientConnectResultCode
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientCredentials
        name: MqttClientCredentials
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientDisconnectOptions
        name: MqttClientDisconnectOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientDisconnectOptionsReason
        name: MqttClientDisconnectOptionsReason
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientDisconnectReason
        name: MqttClientDisconnectReason
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientOptions
        name: MqttClientOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishReasonCode
        name: MqttClientPublishReasonCode
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientPublishResult
        name: MqttClientPublishResult
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeOptions
        name: MqttClientSubscribeOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeReasonCode
        name: MqttClientSubscribeReasonCode
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResult
        name: MqttClientSubscribeResult
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientSubscribeResultItem
        name: MqttClientSubscribeResultItem
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientTcpOptions
        name: MqttClientTcpOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientTlsOptions
        name: MqttClientTlsOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeOptions
        name: MqttClientUnsubscribeOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeReasonCode
        name: MqttClientUnsubscribeReasonCode
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeResult
        name: MqttClientUnsubscribeResult
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientUnsubscribeResultItem
        name: MqttClientUnsubscribeResultItem
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientWebSocketOptions
        name: MqttClientWebSocketOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttClientWebSocketProxyOptions
        name: MqttClientWebSocketProxyOptions
      - uid: Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeContext
        name: MqttExtendedAuthenticationExchangeContext
      - uid: Azure.Iot.Operations.Protocol.Models.MqttExtendedAuthenticationExchangeData
        name: MqttExtendedAuthenticationExchangeData
      - uid: Azure.Iot.Operations.Protocol.Models.MqttPayloadFormatIndicator
        name: MqttPayloadFormatIndicator
      - uid: Azure.Iot.Operations.Protocol.Models.MqttPendingMessagesOverflowStrategy
        name: MqttPendingMessagesOverflowStrategy
      - uid: Azure.Iot.Operations.Protocol.Models.MqttProtocolVersion
        name: MqttProtocolVersion
      - uid: Azure.Iot.Operations.Protocol.Models.MqttQualityOfServiceLevel
        name: MqttQualityOfServiceLevel
      - uid: Azure.Iot.Operations.Protocol.Models.MqttRetainHandling
        name: MqttRetainHandling
      - uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilter
        name: MqttTopicFilter
      - uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterCompareResult
        name: MqttTopicFilterCompareResult
      - uid: Azure.Iot.Operations.Protocol.Models.MqttTopicFilterComparer
        name: MqttTopicFilterComparer
      - uid: Azure.Iot.Operations.Protocol.Models.MqttUserProperty
        name: MqttUserProperty
    - uid: Azure.Iot.Operations.Protocol.RPC
      name: RPC
      items:
      - uid: Azure.Iot.Operations.Protocol.RPC.CommandExecutor`2
        name: CommandExecutor<TReq, TResp>
      - uid: Azure.Iot.Operations.Protocol.RPC.CommandInvoker`2
        name: CommandInvoker<TReq, TResp>
      - uid: Azure.Iot.Operations.Protocol.RPC.CommandRequestMetadata
        name: CommandRequestMetadata
      - uid: Azure.Iot.Operations.Protocol.RPC.CommandResponseMetadata
        name: CommandResponseMetadata
      - uid: Azure.Iot.Operations.Protocol.RPC.CommandStatusCode
        name: CommandStatusCode
      - uid: Azure.Iot.Operations.Protocol.RPC.ExtendedRequest`1
        name: ExtendedRequest<TReq>
      - uid: Azure.Iot.Operations.Protocol.RPC.ExtendedResponse`1
        name: ExtendedResponse<TResp>
      - uid: Azure.Iot.Operations.Protocol.RPC.InvocationException
        name: InvocationException
      - uid: Azure.Iot.Operations.Protocol.RPC.RpcCallAsync`1
        name: RpcCallAsync<TResp>
    - uid: Azure.Iot.Operations.Protocol.Retry
      name: Retry
      items:
      - uid: Azure.Iot.Operations.Protocol.Retry.ExponentialBackoffRetryPolicy
        name: ExponentialBackoffRetryPolicy
      - uid: Azure.Iot.Operations.Protocol.Retry.IRetryPolicy
        name: IRetryPolicy
      - uid: Azure.Iot.Operations.Protocol.Retry.NoRetryPolicy
        name: NoRetryPolicy
      - uid: Azure.Iot.Operations.Protocol.Retry.RetryExpiredException
        name: RetryExpiredException
    - uid: Azure.Iot.Operations.Protocol.Telemetry
      name: Telemetry
      items:
      - uid: Azure.Iot.Operations.Protocol.Telemetry.CloudEvent
        name: CloudEvent
      - uid: Azure.Iot.Operations.Protocol.Telemetry.IncomingTelemetryMetadata
        name: IncomingTelemetryMetadata
      - uid: Azure.Iot.Operations.Protocol.Telemetry.OutgoingTelemetryMetadata
        name: OutgoingTelemetryMetadata
      - uid: Azure.Iot.Operations.Protocol.Telemetry.TelemetryReceiver`1
        name: TelemetryReceiver<T>
      - uid: Azure.Iot.Operations.Protocol.Telemetry.TelemetrySender`1
        name: TelemetrySender<T>
    - uid: Azure.Iot.Operations.Protocol.AkriMqttErrorKind
      name: AkriMqttErrorKind
    - uid: Azure.Iot.Operations.Protocol.AkriMqttException
      name: AkriMqttException
    - uid: Azure.Iot.Operations.Protocol.AkriSystemProperties
      name: AkriSystemProperties
    - uid: Azure.Iot.Operations.Protocol.CommandBehaviorAttribute
      name: CommandBehaviorAttribute
    - uid: Azure.Iot.Operations.Protocol.CommandTopicAttribute
      name: CommandTopicAttribute
    - uid: Azure.Iot.Operations.Protocol.GuidExtensions
      name: GuidExtensions
    - uid: Azure.Iot.Operations.Protocol.HybridLogicalClock
      name: HybridLogicalClock
    - uid: Azure.Iot.Operations.Protocol.HybridLogicalClockException
      name: HybridLogicalClockException
    - uid: Azure.Iot.Operations.Protocol.IDelayableQueueItem
      name: IDelayableQueueItem
    - uid: Azure.Iot.Operations.Protocol.IMqttClient
      name: IMqttClient
    - uid: Azure.Iot.Operations.Protocol.IMqttPubSubClient
      name: IMqttPubSubClient
    - uid: Azure.Iot.Operations.Protocol.IPayloadSerializer
      name: IPayloadSerializer
    - uid: Azure.Iot.Operations.Protocol.IWallClock
      name: IWallClock
    - uid: Azure.Iot.Operations.Protocol.ModelIdAttribute
      name: ModelIdAttribute
    - uid: Azure.Iot.Operations.Protocol.PatternValidity
      name: PatternValidity
    - uid: Azure.Iot.Operations.Protocol.ServiceGroupIdAttribute
      name: ServiceGroupIdAttribute
    - uid: Azure.Iot.Operations.Protocol.TelemetryTopicAttribute
      name: TelemetryTopicAttribute
    - uid: Azure.Iot.Operations.Protocol.WallClock
      name: WallClock
  - uid: Azure.Iot.Operations.Services
    name: Services
    items:
    - uid: Azure.Iot.Operations.Services.Akri
      name: Akri
      items:
      - uid: Azure.Iot.Operations.Services.Akri.CombinedPrefixedReadOnlyDictionary`1
        name: CombinedPrefixedReadOnlyDictionary<TValue>
      - uid: Azure.Iot.Operations.Services.Akri.DecimalString
        name: DecimalString
      - uid: Azure.Iot.Operations.Services.Akri.DiscoveredAssetResourcesClient
        name: DiscoveredAssetResourcesClient
      - uid: Azure.Iot.Operations.Services.Akri.EmptyJson
        name: EmptyJson
      - uid: Azure.Iot.Operations.Services.Akri.IDiscoveredAssetResourcesClient
        name: IDiscoveredAssetResourcesClient
      - uid: Azure.Iot.Operations.Services.Akri.Utf8JsonSerializer
        name: Utf8JsonSerializer
    - uid: Azure.Iot.Operations.Services.LeaderElection
      name: LeaderElection
      items:
      - uid: Azure.Iot.Operations.Services.LeaderElection.CampaignRequestOptions
        name: CampaignRequestOptions
      - uid: Azure.Iot.Operations.Services.LeaderElection.CampaignResponse
        name: CampaignResponse
      - uid: Azure.Iot.Operations.Services.LeaderElection.GetCurrentLeaderResponse
        name: GetCurrentLeaderResponse
      - uid: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionAutomaticRenewalOptions
        name: LeaderElectionAutomaticRenewalOptions
      - uid: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionCandidate
        name: LeaderElectionCandidate
      - uid: Azure.Iot.Operations.Services.LeaderElection.LeaderElectionClient
        name: LeaderElectionClient
      - uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipChangeEventArgs
        name: LeadershipChangeEventArgs
      - uid: Azure.Iot.Operations.Services.LeaderElection.LeadershipPositionState
        name: LeadershipPositionState
      - uid: Azure.Iot.Operations.Services.LeaderElection.ObserveLeadershipChangesRequestOptions
        name: ObserveLeadershipChangesRequestOptions
      - uid: Azure.Iot.Operations.Services.LeaderElection.ResignationRequestOptions
        name: ResignationRequestOptions
      - uid: Azure.Iot.Operations.Services.LeaderElection.ResignationResponse
        name: ResignationResponse
    - uid: Azure.Iot.Operations.Services.LeasedLock
      name: LeasedLock
      items:
      - uid: Azure.Iot.Operations.Services.LeasedLock.AcquireLockRequestOptions
        name: AcquireLockRequestOptions
      - uid: Azure.Iot.Operations.Services.LeasedLock.AcquireLockResponse
        name: AcquireLockResponse
      - uid: Azure.Iot.Operations.Services.LeasedLock.GetLockHolderResponse
        name: GetLockHolderResponse
      - uid: Azure.Iot.Operations.Services.LeasedLock.LeasedLockAutomaticRenewalOptions
        name: LeasedLockAutomaticRenewalOptions
      - uid: Azure.Iot.Operations.Services.LeasedLock.LeasedLockClient
        name: LeasedLockClient
      - uid: Azure.Iot.Operations.Services.LeasedLock.LeasedLockHolder
        name: LeasedLockHolder
      - uid: Azure.Iot.Operations.Services.LeasedLock.LockChangeEventArgs
        name: LockChangeEventArgs
      - uid: Azure.Iot.Operations.Services.LeasedLock.LockState
        name: LockState
      - uid: Azure.Iot.Operations.Services.LeasedLock.ObserveLockRequestOptions
        name: ObserveLockRequestOptions
      - uid: Azure.Iot.Operations.Services.LeasedLock.ReleaseLockRequestOptions
        name: ReleaseLockRequestOptions
      - uid: Azure.Iot.Operations.Services.LeasedLock.ReleaseLockResponse
        name: ReleaseLockResponse
    - uid: Azure.Iot.Operations.Services.SchemaRegistry
      name: SchemaRegistry
      items:
      - uid: Azure.Iot.Operations.Services.SchemaRegistry.CombinedPrefixedReadOnlyDictionary`1
        name: CombinedPrefixedReadOnlyDictionary<TValue>
      - uid: Azure.Iot.Operations.Services.SchemaRegistry.EmptyJson
        name: EmptyJson
      - uid: Azure.Iot.Operations.Services.SchemaRegistry.ISchemaRegistryClient
        name: ISchemaRegistryClient
      - uid: Azure.Iot.Operations.Services.SchemaRegistry.SchemaRegistryClient
        name: SchemaRegistryClient
      - uid: Azure.Iot.Operations.Services.SchemaRegistry.Utf8JsonSerializer
        name: Utf8JsonSerializer
    - uid: Azure.Iot.Operations.Services.StateStore
      name: StateStore
      items:
      - uid: Azure.Iot.Operations.Services.StateStore.CombinedPrefixedReadOnlyDictionary`1
        name: CombinedPrefixedReadOnlyDictionary<TValue>
      - uid: Azure.Iot.Operations.Services.StateStore.IStateStoreClient
        name: IStateStoreClient
      - uid: Azure.Iot.Operations.Services.StateStore.KeyChangeMessageReceivedEventArgs
        name: KeyChangeMessageReceivedEventArgs
      - uid: Azure.Iot.Operations.Services.StateStore.KeyState
        name: KeyState
      - uid: Azure.Iot.Operations.Services.StateStore.PassthroughSerializer
        name: PassthroughSerializer
      - uid: Azure.Iot.Operations.Services.StateStore.ServiceError
        name: ServiceError
      - uid: Azure.Iot.Operations.Services.StateStore.SetCondition
        name: SetCondition
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreClient
        name: StateStoreClient
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteRequestOptions
        name: StateStoreDeleteRequestOptions
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreDeleteResponse
        name: StateStoreDeleteResponse
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreErrorKind
        name: StateStoreErrorKind
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreGetResponse
        name: StateStoreGetResponse
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreKey
        name: StateStoreKey
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreObject
        name: StateStoreObject
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreObserveRequestOptions
        name: StateStoreObserveRequestOptions
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreOperationException
        name: StateStoreOperationException
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreResponse
        name: StateStoreResponse
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreSetRequestOptions
        name: StateStoreSetRequestOptions
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreSetResponse
        name: StateStoreSetResponse
      - uid: Azure.Iot.Operations.Services.StateStore.StateStoreValue
        name: StateStoreValue
memberLayout: SamePage
