/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

use azure_iot_operations_protocol::common::payload_serialize::BypassPayload;

/// A provided convenience struct for data that is externally serialized via custom code.
pub type CustomPayload = BypassPayload;
