/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace ProtocolInterop.Demo
{
    using System;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class CounterErrorException : Exception
    {
        public CounterErrorException(CounterError counterError)
            : base(counterError.Explanation ?? "The requested counter operation could not be completed.")
        {
            CounterError = counterError;
        }

        public CounterError CounterError { get; }
    }
}
