/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace ProtocolInterop.Demo
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class IncrementResponseSchema
    {
        /// <summary>
        /// The 'counterValue' Field.
        /// </summary>
        [JsonPropertyName("counterValue")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? CounterValue { get; set; } = default;

        /// <summary>
        /// The 'incrementError' Field.
        /// </summary>
        [JsonPropertyName("incrementError")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public CounterError? IncrementError { get; set; } = default;

    }
}
