/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace ProtocolInterop.Demo
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class IncrementRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("counterName")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string CounterName { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (CounterName is null)
            {
                throw new ArgumentNullException("counterName field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (CounterName is null)
            {
                throw new ArgumentNullException("counterName field cannot be null");
            }
        }
    }
}
