/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.AssetAndDeviceRegistry.AdrBaseService
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using Azure.Iot.Operations.Services.AssetAndDeviceRegistry;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "0.10.0.0")]
    public partial class EventRuntimeHealthEventTelemetry : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Telemetry event emitted for reporting the runtime health of events.
        /// </summary>
        [JsonPropertyName("eventRuntimeHealthEvent")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public EventRuntimeHealthEventSchema EventRuntimeHealthEvent { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (EventRuntimeHealthEvent is null)
            {
                throw new ArgumentNullException("eventRuntimeHealthEvent field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (EventRuntimeHealthEvent is null)
            {
                throw new ArgumentNullException("eventRuntimeHealthEvent field cannot be null");
            }
        }
    }
}
