---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: passive-replication-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passive-replication-deployment
  labels:
    app: passive-replication
spec:
  replicas: 5 # The number of passive replication pods to deploy
  selector:
    matchLabels:
      app: passive-replication
  template:
    metadata:
      labels:
        app: passive-replication
    spec:
      serviceAccountName: passive-replication-service-account
      containers:
        - name: passive-replication-sample
          image: passivereplicationsample
          imagePullPolicy: Never
          volumeMounts:
            - name: mqtt-client-token
              mountPath: /var/run/secrets/tokens
            - name: aio-ca-trust-bundle
              mountPath: /var/run/certs/aio-ca/
          env:
            - name: AIO_MQTT_CLIENT_ID
              value: "PassiveReplicationApp"
            - name: AIO_BROKER_HOSTNAME
              value: "aio-broker"
            - name: AIO_BROKER_TCP_PORT
              value: "18883"
            - name: AIO_MQTT_USE_TLS
              value: "true"
            - name: AIO_TLS_CA_FILE
              value: "/var/run/certs/aio-ca/ca.crt"
            - name: AIO_SAT_FILE
              value: "/var/run/secrets/tokens/mqtt-client-token"
      volumes:
        - name: mqtt-client-token
          projected:
            sources:
              - serviceAccountToken:
                  path: mqtt-client-token
                  audience: aio-internal
        - name: aio-ca-trust-bundle
          configMap:
            name: azure-iot-operations-aio-ca-trust-bundle
