output: '{{.Dir}}/README.md'
repository:
    url: https://github.com/Azure/iot-operations-sdks
    defaultBranch: main
    path: /go/internal
excludeDirs: ./container/... ./log/... ./mage/... ./options/... ./wallclock/...
