/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::label::Label;

/// Request payload for creating a Schema version.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct CreateSchemaVersionAttributes {
    #[serde(rename = "groupId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub group_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub description: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub documentation: Option<String>,

    /// Queryable Key Value pairs to be added to the Version
    #[builder(default)]
    pub labels: Vec<Label>,

    /// The versionId of this version's ancestor if it has an ancestor.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub ancestor: Option<u64>,

    /// Content type of the schema version.
    #[serde(rename = "contentType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub content_type: Option<String>,

    /// Schema format identifier, e.g. `JsonSchema/draft-07`, `Protobuf/3`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub format: Option<String>,

    /// Base64-encoded schema document content.
    #[serde(rename = "schemaDocument")]
    pub schema_document: Bytes,

    /// Queryable Key Value pairs to be added to the parent Schema
    #[serde(rename = "schemaLabels")]
    #[builder(default)]
    pub schema_labels: Vec<Label>,
}
