/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

/// Input arguments for action 'getThingDescriptionVersion'
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct GetThingDescriptionVersionInputArguments {
    /// The 'groupId' Field.
    #[serde(rename = "groupId")]
    pub group_id: String,

    /// The 'thingDescriptionId' Field.
    #[serde(rename = "thingDescriptionId")]
    pub thing_description_id: String,

    /// The 'versionId' Field.
    #[serde(rename = "versionId")]
    pub version_id: String,
}
