/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

/// Request payload for creating or updating a Group.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct GroupAttributes {
    #[serde(rename = "groupType")]
    pub group_type: String,

    #[serde(rename = "groupId")]
    pub group_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub description: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub documentation: Option<String>,

    #[builder(default)]
    pub labels: HashMap<String, String>,

    /// Extension-specific attributes (e.g., `envelope`, `protocol` for message groups).
    #[builder(default)]
    pub extensions: HashMap<String, Bytes>,
}
