/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ResourceMetaAttributes {
    /// Extension-specific attributes (e.g., `format` and `content_type` for schemas).
    #[builder(default)]
    pub extensions: HashMap<String, Bytes>,

    /// The 'labels' Field.
    #[builder(default)]
    pub labels: HashMap<String, String>,

    /// Resource identifier within the group.
    pub id: String,
}
