/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::label::Label;

#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ResourceMeta {
    /// The 'createdAt' Field.
    #[serde(rename = "createdAt")]
    pub created_at: DateTime<Utc>,

    /// The 'defaultVersionId' Field.
    #[serde(rename = "defaultVersionId")]
    pub default_version_id: String,

    /// The 'epoch' Field.
    pub epoch: u64,

    /// Extension-specific attributes (e.g., `format` and `content_type` for schemas).
    #[builder(default)]
    pub extensions: HashMap<String, Bytes>,

    /// The 'labels' Field.
    #[builder(default)]
    pub labels: Vec<Label>,

    /// Resource identifier within the group.
    pub id: String,

    /// The 'modifiedAt' Field.
    #[serde(rename = "modifiedAt")]
    pub modified_at: DateTime<Utc>,

    /// Full XID path.
    pub xid: String,
}
