/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

/// Additional fields and field guarantees for the schema extension.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct SchemaVersionExtensions {
    /// The versionId of this version's ancestor, or this version's versionId if it has no ancestor as an integer. Must match ancestor on the referenced Version entity.
    pub ancestor: u64,

    /// Version identifier as an integer. Must match versionId on the referenced Version entity.
    #[serde(rename = "versionId")]
    pub version_id: u64,

    /// Content type of the schema version.
    #[serde(rename = "contentType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub content_type: Option<String>,

    /// Schema format identifier, e.g. `JsonSchema/draft-07`, `Protobuf/3`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub format: Option<String>,

    /// The raw schema document for this version as bytes.
    #[serde(rename = "schemaDoc")]
    pub schema_doc: Bytes,
}
