/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};

/// Additional fields and field guarantees for the thing description extension.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ThingDescriptionVersionExtensions {
    /// Content type of the thing description version.
    #[serde(rename = "contentType")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub content_type: Option<String>,

    /// Thing description format identifier, e.g. `WoT-TD/1.1`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub format: Option<String>,

    /// The raw thing description document for this version as bytes.
    #[serde(rename = "thingDescriptionDocument")]
    pub thing_description_document: Bytes,

    /// The hash of the thing description document for this version.
    #[serde(rename = "thingDescriptionDocumentHash")]
    pub thing_description_document_hash: String,
}
