/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace SharedComplexSchemasSample.CommandComplexSchemas
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using SharedComplexSchemasSample;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class DoSomethingRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("input")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public DoSomethingRequestSchema Input { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Input is null)
            {
                throw new ArgumentNullException("input field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Input is null)
            {
                throw new ArgumentNullException("input field cannot be null");
            }
        }
    }
}
