/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace SharedComplexSchemasSample.CommandComplexSchemas
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using SharedComplexSchemasSample;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class DoSomethingRequestSchema
    {
        /// <summary>
        /// The 'actions' Field.
        /// </summary>
        [JsonPropertyName("actions")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<string>? Actions { get; set; } = default;

        /// <summary>
        /// The 'when' Field.
        /// </summary>
        [JsonPropertyName("when")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public WhenSchema? When { get; set; } = default;

    }
}
