// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::collections::HashMap;
use std::sync::LazyLock;

pub(super) static KIND_SYSTEM_UNITS: LazyLock<HashMap<(&'static str, &'static str), &'static str>> =
    LazyLock::new(|| {
        HashMap::from([
            (("AbsoluteActivity", "CGS"), "unit:BQ-SEC-PER-M3"),
            (("AbsoluteActivity", "CGS-EMU"), "unit:BQ-SEC-PER-M3"),
            (("AbsoluteActivity", "CGS-GAUSS"), "unit:BQ-SEC-PER-M3"),
            (("AbsoluteActivity", "SI"), "unit:BQ-SEC-PER-M3"),
            (("AbsorbedDose", "CGS"), "unit:GRAY"),
            (("AbsorbedDose", "CGS-EMU"), "unit:GRAY"),
            (("AbsorbedDose", "CGS-GAUSS"), "unit:GRAY"),
            (("AbsorbedDose", "SI"), "unit:GRAY"),
            (("AbsorbedDoseRate", "CGS"), "unit:W-PER-GM"),
            (("AbsorbedDoseRate", "CGS-EMU"), "unit:W-PER-GM"),
            (("AbsorbedDoseRate", "CGS-GAUSS"), "unit:W-PER-GM"),
            (("AbsorbedDoseRate", "SI"), "unit:W-PER-GM"),
            (("Acceleration", "CGS"), "unit:GALILEO"),
            (("Acceleration", "CGS-EMU"), "unit:M-PER-SEC2"),
            (("Acceleration", "CGS-GAUSS"), "unit:GALILEO"),
            (("Acceleration", "IMPERIAL"), "unit:FT-PER-SEC2"),
            (("Acceleration", "SI"), "unit:M-PER-SEC2"),
            (("Acceleration", "USCS"), "unit:KN-PER-SEC"),
            (("Acidity", "ASU"), "unit:PH"),
            (("Acidity", "CGS"), "unit:PH"),
            (("Acidity", "CGS-EMU"), "unit:PH"),
            (("Acidity", "CGS-ESU"), "unit:PH"),
            (("Acidity", "CGS-GAUSS"), "unit:PH"),
            (("Acidity", "IMPERIAL"), "unit:PH"),
            (("Acidity", "PLANCK"), "unit:PH"),
            (("Acidity", "SI"), "unit:PH"),
            (("AcousticImpedance", "CGS"), "unit:PA-SEC-PER-M"),
            (("AcousticImpedance", "CGS-EMU"), "unit:PA-SEC-PER-M"),
            (("AcousticImpedance", "CGS-GAUSS"), "unit:PA-SEC-PER-M"),
            (("AcousticImpedance", "SI"), "unit:PA-SEC-PER-M"),
            (("Action", "CGS"), "unit:AttoJ-SEC"),
            (("Action", "CGS-EMU"), "unit:AttoJ-SEC"),
            (("Action", "CGS-GAUSS"), "unit:AttoJ-SEC"),
            (("Action", "SI"), "unit:AttoJ-SEC"),
            (("Activity", "CGS"), "unit:BQ"),
            (("Activity", "CGS-EMU"), "unit:BQ"),
            (("Activity", "CGS-GAUSS"), "unit:BQ"),
            (("Activity", "IMPERIAL"), "unit:BQ"),
            (("Activity", "SI"), "unit:BQ"),
            (("Activity", "USCS"), "unit:BQ"),
            (("ActivityConcentration", "CGS"), "unit:BQ-PER-L"),
            (("ActivityConcentration", "CGS-EMU"), "unit:BQ-PER-L"),
            (("ActivityConcentration", "CGS-GAUSS"), "unit:BQ-PER-L"),
            (("ActivityConcentration", "SI"), "unit:BQ-PER-L"),
            (("Admittance", "CGS"), "unit:MHO"),
            (("Admittance", "CGS-EMU"), "unit:S"),
            (("Admittance", "CGS-GAUSS"), "unit:S"),
            (("Admittance", "PLANCK"), "unit:S"),
            (("Admittance", "SI"), "unit:S"),
            (("AmountOfSubstance", "SI"), "unit:MOL"),
            (("AmountOfSubstance", "USCS"), "unit:SCM_1ATM_0DEG_C"),
            (("AmountOfSubstancePerMass", "SI"), "unit:MOL-PER-KiloGM"),
            (
                ("AmountOfSubstancePerMassPressure", "SI"),
                "unit:MOL-PER-KiloGM-PA",
            ),
            (("Angle", "ASU"), "unit:DEG"),
            (("Angle", "CGS"), "unit:DEG"),
            (("Angle", "CGS-EMU"), "unit:DEG"),
            (("Angle", "CGS-ESU"), "unit:DEG"),
            (("Angle", "CGS-GAUSS"), "unit:DEG"),
            (("Angle", "IMPERIAL"), "unit:DEG"),
            (("Angle", "PLANCK"), "unit:DEG"),
            (("Angle", "SI"), "unit:DEG"),
            (("Angle", "USCS"), "unit:ARCMIN"),
            (("AngularAcceleration", "CGS"), "unit:RAD-PER-SEC2"),
            (("AngularAcceleration", "CGS-EMU"), "unit:RAD-PER-SEC2"),
            (("AngularAcceleration", "CGS-GAUSS"), "unit:RAD-PER-SEC2"),
            (("AngularAcceleration", "IMPERIAL"), "unit:DEG-PER-SEC2"),
            (("AngularAcceleration", "SI"), "unit:RAD-PER-SEC2"),
            (("AngularCrossSection", "CGS"), "unit:M2-PER-SR"),
            (("AngularCrossSection", "CGS-EMU"), "unit:M2-PER-SR"),
            (("AngularCrossSection", "CGS-GAUSS"), "unit:M2-PER-SR"),
            (("AngularCrossSection", "SI"), "unit:M2-PER-SR"),
            (("AngularFrequency", "CGS"), "unit:RAD-PER-HR"),
            (("AngularFrequency", "CGS-EMU"), "unit:RAD-PER-HR"),
            (("AngularFrequency", "CGS-GAUSS"), "unit:RAD-PER-HR"),
            (("AngularFrequency", "IMPERIAL"), "unit:DEG-PER-HR"),
            (("AngularFrequency", "SI"), "unit:RAD-PER-HR"),
            (("AngularImpulse", "CGS"), "unit:J-SEC"),
            (("AngularImpulse", "CGS-EMU"), "unit:J-SEC"),
            (("AngularImpulse", "CGS-GAUSS"), "unit:J-SEC"),
            (("AngularImpulse", "IMPERIAL"), "unit:FT-LB_F-SEC"),
            (("AngularImpulse", "SI"), "unit:J-SEC"),
            (("AngularImpulse", "USCS"), "unit:FT-LB_F-SEC"),
            (("AngularMomentumPerAngle", "CGS"), "unit:N-M-SEC-PER-RAD"),
            (
                ("AngularMomentumPerAngle", "CGS-EMU"),
                "unit:N-M-SEC-PER-RAD",
            ),
            (
                ("AngularMomentumPerAngle", "CGS-GAUSS"),
                "unit:N-M-SEC-PER-RAD",
            ),
            (("AngularMomentumPerAngle", "SI"), "unit:N-M-SEC-PER-RAD"),
            (("AngularWavenumber", "CGS"), "unit:RAD-PER-M"),
            (("AngularWavenumber", "CGS-EMU"), "unit:RAD-PER-M"),
            (("AngularWavenumber", "CGS-GAUSS"), "unit:RAD-PER-M"),
            (("AngularWavenumber", "SI"), "unit:RAD-PER-M"),
            (("APIGravity", "ASU"), "unit:DEGREE_API"),
            (("APIGravity", "CGS"), "unit:DEGREE_API"),
            (("APIGravity", "CGS-EMU"), "unit:DEGREE_API"),
            (("APIGravity", "CGS-ESU"), "unit:DEGREE_API"),
            (("APIGravity", "CGS-GAUSS"), "unit:DEGREE_API"),
            (("APIGravity", "IMPERIAL"), "unit:DEGREE_API"),
            (("APIGravity", "PLANCK"), "unit:DEGREE_API"),
            (("APIGravity", "SI"), "unit:DEGREE_API"),
            (("ApparentPower", "CGS-EMU"), "unit:VA"),
            (("ApparentPower", "CGS-GAUSS"), "unit:VA"),
            (("ApparentPower", "PLANCK"), "unit:VA"),
            (("ApparentPower", "SI"), "unit:VA"),
            (("Area", "CGS"), "unit:HA"),
            (("Area", "CGS-EMU"), "unit:HA"),
            (("Area", "CGS-GAUSS"), "unit:HA"),
            (("Area", "IMPERIAL"), "unit:AC"),
            (("Area", "PLANCK"), "unit:PlanckArea"),
            (("Area", "SI"), "unit:HA"),
            (("Area", "USCS"), "unit:AC"),
            (("AreaAngle", "CGS"), "unit:M2-SR"),
            (("AreaAngle", "CGS-EMU"), "unit:M2-SR"),
            (("AreaAngle", "CGS-GAUSS"), "unit:M2-SR"),
            (("AreaAngle", "SI"), "unit:M2-SR"),
            (("AreaPerLength", "SI"), "unit:M2-PER-M"),
            (("AreaPerPower", "SI"), "unit:M2-PER-W"),
            (("AreaPerTime", "CGS"), "unit:M2-HZ"),
            (("AreaPerTime", "CGS-EMU"), "unit:M2-HZ"),
            (("AreaPerTime", "CGS-GAUSS"), "unit:M2-HZ"),
            (("AreaPerTime", "IMPERIAL"), "unit:FT2-PER-HR"),
            (("AreaPerTime", "SI"), "unit:M2-HZ"),
            (("AreaPerTime", "USCS"), "unit:FT2-PER-HR"),
            (("AreaRatio", "CGS"), "unit:M2-PER-HA"),
            (("AreaRatio", "CGS-EMU"), "unit:M2-PER-HA"),
            (("AreaRatio", "CGS-GAUSS"), "unit:M2-PER-HA"),
            (("AreaRatio", "SI"), "unit:M2-PER-HA"),
            (("AreaTemperature", "IMPERIAL"), "unit:FT2-DEG_F"),
            (("AreaTemperature", "SI"), "unit:M2-K"),
            (("AreaTemperature", "USCS"), "unit:FT2-DEG_F"),
            (("AreaThermalExpansion", "SI"), "unit:M2-PER-K"),
            (("AreaTime", "CGS"), "unit:CentiM2-MIN"),
            (("AreaTime", "CGS-EMU"), "unit:CentiM2-MIN"),
            (("AreaTime", "CGS-GAUSS"), "unit:CentiM2-MIN"),
            (("AreaTime", "IMPERIAL"), "unit:HR-FT2"),
            (("AreaTime", "SI"), "unit:CentiM2-MIN"),
            (("AreaTime", "USCS"), "unit:HR-FT2"),
            (("AreaTimeTemperature", "IMPERIAL"), "unit:FT2-HR-DEG_F"),
            (("AreaTimeTemperature", "USCS"), "unit:FT2-HR-DEG_F"),
            (
                ("AtmosphericHydroxylationRate", "SI"),
                "unit:M3-PER-MOL-SEC",
            ),
            (("AtomicNumber", "CGS"), "unit:Z"),
            (("BiogeochemicalRate", "SI"), "unit:MOL-PER-GM-HR"),
            (("Capacitance", "CGS"), "unit:FARAD"),
            (("Capacitance", "CGS-EMU"), "unit:FARAD"),
            (("Capacitance", "CGS-ESU"), "unit:FARAD_Stat"),
            (("Capacitance", "CGS-GAUSS"), "unit:FARAD"),
            (("Capacitance", "PLANCK"), "unit:FARAD"),
            (("Capacitance", "SI"), "unit:FARAD"),
            (("CatalyticActivity", "SI"), "unit:KAT"),
            (("CatalyticActivityConcentration", "SI"), "unit:KAT-PER-L"),
            (
                ("CoefficientOfHeatTransfer", "CGS"),
                "unit:CAL_IT-PER-SEC-CentiM2-K",
            ),
            (
                ("CoefficientOfHeatTransfer", "IMPERIAL"),
                "unit:BTU_IT-PER-FT2-HR-DEG_F",
            ),
            (("CoefficientOfHeatTransfer", "SI"), "unit:W-PER-M2-K"),
            (
                ("CoefficientOfHeatTransfer", "USCS"),
                "unit:BTU_IT-PER-FT2-HR-DEG_F",
            ),
            (("Compressibility", "CGS"), "unit:PER-PA"),
            (("Compressibility", "CGS-EMU"), "unit:PER-PA"),
            (("Compressibility", "CGS-GAUSS"), "unit:PER-PA"),
            (("Compressibility", "SI"), "unit:PER-PA"),
            (("Concentration", "SI"), "unit:MOL-PER-L"),
            (("ConductionSpeed", "CGS"), "unit:KiloHZ-M"),
            (("ConductionSpeed", "CGS-EMU"), "unit:KiloHZ-M"),
            (("ConductionSpeed", "CGS-GAUSS"), "unit:KiloHZ-M"),
            (("ConductionSpeed", "SI"), "unit:KiloHZ-M"),
            (("Conductivity", "CGS"), "unit:MicroS-PER-CentiM"),
            (("Conductivity", "CGS-EMU"), "unit:S-PER-M"),
            (("Conductivity", "CGS-GAUSS"), "unit:S-PER-M"),
            (("Conductivity", "SI"), "unit:S-PER-M"),
            (("ConductivityVariance", "CGS"), "unit:MicroS2-PER-CentiM2"),
            (
                ("ConductivityVariance", "CGS-EMU"),
                "unit:MicroS2-PER-CentiM2",
            ),
            (
                ("ConductivityVariance", "CGS-GAUSS"),
                "unit:MicroS2-PER-CentiM2",
            ),
            (("ConductivityVariance", "SI"), "unit:MicroS2-PER-CentiM2"),
            (("CostPerArea", "SI"), "unit:CCY_CHF-PER-HA"),
            (("CostPerEnergy", "SI"), "unit:CCY_EUR-PER-W-HR"),
            (("CostPerMass", "SI"), "unit:CCY_CHF-PER-KiloGM"),
            (("CostPerPower", "SI"), "unit:CCY_EUR-PER-W"),
            (("Count", "ASU"), "unit:NUM"),
            (("Count", "CGS"), "unit:UNITLESS"),
            (("Count", "CGS-EMU"), "unit:UNITLESS"),
            (("Count", "CGS-ESU"), "unit:NUM"),
            (("Count", "CGS-GAUSS"), "unit:UNITLESS"),
            (("Count", "IMPERIAL"), "unit:NUM"),
            (("Count", "PLANCK"), "unit:NUM"),
            (("Count", "SI"), "unit:UNITLESS"),
            (("Count", "USCS"), "unit:UNITLESS"),
            (
                ("CubicElectricDipoleMomentPerSquareEnergy", "CGS"),
                "unit:C3-M-PER-J2",
            ),
            (
                ("CubicElectricDipoleMomentPerSquareEnergy", "CGS-EMU"),
                "unit:C3-M-PER-J2",
            ),
            (
                ("CubicElectricDipoleMomentPerSquareEnergy", "CGS-GAUSS"),
                "unit:C3-M-PER-J2",
            ),
            (
                ("CubicElectricDipoleMomentPerSquareEnergy", "SI"),
                "unit:C3-M-PER-J2",
            ),
            (("CurrencyPerFlight", "ASU"), "unit:MegaCCY_USD-PER-FLIGHT"),
            (("CurrencyPerFlight", "CGS"), "unit:MegaCCY_USD-PER-FLIGHT"),
            (
                ("CurrencyPerFlight", "CGS-EMU"),
                "unit:MegaCCY_USD-PER-FLIGHT",
            ),
            (
                ("CurrencyPerFlight", "CGS-ESU"),
                "unit:MegaCCY_USD-PER-FLIGHT",
            ),
            (
                ("CurrencyPerFlight", "CGS-GAUSS"),
                "unit:MegaCCY_USD-PER-FLIGHT",
            ),
            (
                ("CurrencyPerFlight", "IMPERIAL"),
                "unit:MegaCCY_USD-PER-FLIGHT",
            ),
            (
                ("CurrencyPerFlight", "PLANCK"),
                "unit:MegaCCY_USD-PER-FLIGHT",
            ),
            (("CurrencyPerFlight", "SI"), "unit:MegaCCY_USD-PER-FLIGHT"),
            (("Curvature", "CGS"), "unit:DIOPTER"),
            (("Density", "CGS"), "unit:GM-PER-L"),
            (("Density", "CGS-EMU"), "unit:GM-PER-L"),
            (("Density", "CGS-GAUSS"), "unit:GM-PER-L"),
            (("Density", "IMPERIAL"), "unit:LB-PER-FT3"),
            (("Density", "PLANCK"), "unit:PlanckDensity"),
            (("Density", "SI"), "unit:GM-PER-L"),
            (("Density", "USCS"), "unit:LB-PER-FT3"),
            (("Dimensionless", "ASU"), "unit:OCT"),
            (("Dimensionless", "CGS"), "unit:OCT"),
            (("Dimensionless", "CGS-EMU"), "unit:OCT"),
            (("Dimensionless", "CGS-ESU"), "unit:OCT"),
            (("Dimensionless", "CGS-GAUSS"), "unit:OCT"),
            (("Dimensionless", "IMPERIAL"), "unit:OCT"),
            (("Dimensionless", "PLANCK"), "unit:OCT"),
            (("Dimensionless", "SI"), "unit:NP"),
            (("DimensionlessRatio", "ASU"), "unit:GR"),
            (("DimensionlessRatio", "CGS"), "unit:GR"),
            (("DimensionlessRatio", "CGS-EMU"), "unit:GR"),
            (("DimensionlessRatio", "CGS-ESU"), "unit:GR"),
            (("DimensionlessRatio", "CGS-GAUSS"), "unit:GR"),
            (("DimensionlessRatio", "IMPERIAL"), "unit:GR"),
            (("DimensionlessRatio", "PLANCK"), "unit:GR"),
            (("DimensionlessRatio", "SI"), "unit:GR"),
            (("Distance", "IMPERIAL"), "unit:MIL_Length"),
            (("Distance", "USCS"), "unit:MIL_Length"),
            (("DoseEquivalent", "CGS"), "unit:SV"),
            (("DoseEquivalent", "CGS-EMU"), "unit:SV"),
            (("DoseEquivalent", "CGS-GAUSS"), "unit:SV"),
            (("DoseEquivalent", "SI"), "unit:SV"),
            (("DryVolume", "IMPERIAL"), "unit:BU_UK"),
            (("DryVolume", "USCS"), "unit:CORD"),
            (("DynamicViscosity", "CGS"), "unit:POISE"),
            (("DynamicViscosity", "CGS-EMU"), "unit:PA-SEC"),
            (("DynamicViscosity", "CGS-GAUSS"), "unit:POISE"),
            (("DynamicViscosity", "IMPERIAL"), "unit:LB-PER-FT-HR"),
            (("DynamicViscosity", "SI"), "unit:PA-SEC"),
            (("DynamicViscosity", "USCS"), "unit:LB-PER-FT-HR"),
            (("ElectricCharge", "CGS"), "unit:C"),
            (("ElectricCharge", "CGS-EMU"), "unit:C"),
            (("ElectricCharge", "CGS-ESU"), "unit:C_Stat"),
            (("ElectricCharge", "CGS-GAUSS"), "unit:C"),
            (("ElectricCharge", "PLANCK"), "unit:PlanckCharge"),
            (("ElectricCharge", "SI"), "unit:C"),
            (("ElectricChargeDensity", "CGS"), "unit:MegaC-PER-M3"),
            (("ElectricChargeDensity", "CGS-EMU"), "unit:MegaC-PER-M3"),
            (("ElectricChargeDensity", "CGS-GAUSS"), "unit:MegaC-PER-M3"),
            (("ElectricChargeDensity", "SI"), "unit:MegaC-PER-M3"),
            (("ElectricChargeLineDensity", "CGS"), "unit:C-PER-M"),
            (("ElectricChargeLineDensity", "CGS-EMU"), "unit:C-PER-M"),
            (("ElectricChargeLineDensity", "CGS-GAUSS"), "unit:C-PER-M"),
            (("ElectricChargeLineDensity", "SI"), "unit:C-PER-M"),
            (
                ("ElectricChargePerAmountOfSubstance", "CGS"),
                "unit:C_Stat-PER-MOL",
            ),
            (
                ("ElectricChargePerAmountOfSubstance", "SI"),
                "unit:C-PER-MOL",
            ),
            (("ElectricChargePerArea", "CGS"), "unit:C-PER-M2"),
            (("ElectricChargePerArea", "CGS-EMU"), "unit:C-PER-M2"),
            (
                ("ElectricChargePerArea", "CGS-ESU"),
                "unit:C_Stat-PER-CentiM2",
            ),
            (("ElectricChargePerArea", "CGS-GAUSS"), "unit:C-PER-M2"),
            (("ElectricChargePerArea", "SI"), "unit:C-PER-M2"),
            (("ElectricChargePerMass", "CGS"), "unit:R"),
            (("ElectricChargePerMass", "CGS-EMU"), "unit:R"),
            (("ElectricChargePerMass", "CGS-GAUSS"), "unit:R"),
            (("ElectricChargePerMass", "SI"), "unit:R"),
            (("ElectricChargeVolumeDensity", "CGS"), "unit:C-PER-M3"),
            (("ElectricChargeVolumeDensity", "CGS-EMU"), "unit:C-PER-M3"),
            (
                ("ElectricChargeVolumeDensity", "CGS-GAUSS"),
                "unit:C-PER-M3",
            ),
            (("ElectricChargeVolumeDensity", "SI"), "unit:C-PER-M3"),
            (("ElectricConductivity", "CGS"), "unit:S_Ab"),
            (("ElectricConductivity", "CGS-EMU"), "unit:S_Ab"),
            (("ElectricConductivity", "CGS-ESU"), "unit:S_Stat"),
            (("ElectricConductivity", "SI"), "unit:MHO_Stat"),
            (("ElectricCurrent", "CGS"), "unit:A_Ab"),
            (("ElectricCurrent", "CGS-EMU"), "unit:BIOT"),
            (("ElectricCurrent", "CGS-ESU"), "unit:A_Stat"),
            (("ElectricCurrent", "CGS-GAUSS"), "unit:A"),
            (("ElectricCurrent", "PLANCK"), "unit:A"),
            (("ElectricCurrent", "SI"), "unit:A"),
            (("ElectricCurrentDensity", "CGS"), "unit:A_Ab-PER-CentiM2"),
            (("ElectricCurrentDensity", "CGS-EMU"), "unit:A-PER-M2"),
            (
                ("ElectricCurrentDensity", "CGS-ESU"),
                "unit:A_Stat-PER-CentiM2",
            ),
            (("ElectricCurrentDensity", "CGS-GAUSS"), "unit:A-PER-M2"),
            (
                ("ElectricCurrentDensity", "PLANCK"),
                "unit:PlanckCurrentDensity",
            ),
            (("ElectricCurrentDensity", "SI"), "unit:A-PER-M2"),
            (("ElectricCurrentPerAngle", "CGS-EMU"), "unit:A-PER-RAD"),
            (("ElectricCurrentPerAngle", "CGS-GAUSS"), "unit:A-PER-RAD"),
            (("ElectricCurrentPerAngle", "SI"), "unit:A-PER-RAD"),
            (("ElectricCurrentPerEnergy", "CGS-EMU"), "unit:A-PER-J"),
            (("ElectricCurrentPerEnergy", "CGS-GAUSS"), "unit:A-PER-J"),
            (("ElectricCurrentPerEnergy", "SI"), "unit:A-PER-J"),
            (("ElectricCurrentPerTemperature", "CGS"), "unit:A-PER-DEG_C"),
            (("ElectricCurrentPerTemperature", "SI"), "unit:A-PER-DEG_C"),
            (("ElectricDipoleMoment", "CGS"), "unit:C-M"),
            (("ElectricDipoleMoment", "CGS-EMU"), "unit:C-M"),
            (("ElectricDipoleMoment", "CGS-GAUSS"), "unit:C-M"),
            (("ElectricDipoleMoment", "SI"), "unit:C-M"),
            (("ElectricFieldStrength", "CGS"), "unit:V_Ab-PER-CentiM"),
            (("ElectricFieldStrength", "CGS-EMU"), "unit:V-PER-M"),
            (("ElectricFieldStrength", "CGS-GAUSS"), "unit:V-PER-M"),
            (("ElectricFieldStrength", "SI"), "unit:V-PER-M"),
            (("ElectricFlux", "CGS"), "unit:V_Stat-CentiM"),
            (("ElectricFlux", "CGS-EMU"), "unit:V-M"),
            (("ElectricFlux", "CGS-GAUSS"), "unit:V-M"),
            (("ElectricFlux", "SI"), "unit:V-M"),
            (("ElectricPotential", "CGS"), "unit:V_Ab"),
            (("ElectricPotential", "CGS-EMU"), "unit:V"),
            (("ElectricPotential", "CGS-ESU"), "unit:V_Stat"),
            (("ElectricPotential", "CGS-GAUSS"), "unit:V"),
            (("ElectricPotential", "PLANCK"), "unit:V"),
            (("ElectricPotential", "SI"), "unit:V"),
            (("ElectricQuadrupoleMoment", "CGS"), "unit:C-M2"),
            (("ElectricQuadrupoleMoment", "CGS-EMU"), "unit:C-M2"),
            (("ElectricQuadrupoleMoment", "CGS-GAUSS"), "unit:C-M2"),
            (("ElectricQuadrupoleMoment", "SI"), "unit:C-M2"),
            (
                ("ElectromagneticPermeability", "CGS"),
                "unit:H_Stat-PER-CentiM",
            ),
            (("ElectromagneticPermeability", "CGS-EMU"), "unit:H-PER-M"),
            (
                ("ElectromagneticPermeability", "CGS-ESU"),
                "unit:H_Stat-PER-CentiM",
            ),
            (("ElectromagneticPermeability", "CGS-GAUSS"), "unit:H-PER-M"),
            (("ElectromagneticPermeability", "SI"), "unit:H-PER-M"),
            (
                ("ElectromagneticPermeabilityRatio", "CGS-EMU"),
                "unit:PERMEABILITY_EM_REL",
            ),
            (("Energy", "CGS"), "unit:J"),
            (("Energy", "CGS-EMU"), "unit:J"),
            (("Energy", "CGS-GAUSS"), "unit:J"),
            (("Energy", "IMPERIAL"), "unit:BTU_IT"),
            (("Energy", "PLANCK"), "unit:PlanckEnergy"),
            (("Energy", "SI"), "unit:J"),
            (("Energy", "USCS"), "unit:TOE"),
            (("EnergyDensity", "CGS"), "unit:J-PER-M3"),
            (("EnergyDensity", "CGS-EMU"), "unit:J-PER-M3"),
            (("EnergyDensity", "CGS-GAUSS"), "unit:J-PER-M3"),
            (("EnergyDensity", "IMPERIAL"), "unit:BTU_IT-PER-FT3"),
            (("EnergyDensity", "SI"), "unit:J-PER-M3"),
            (("EnergyDensity", "USCS"), "unit:BTU_IT-PER-FT3"),
            (("EnergyDensityOfStates", "CGS"), "unit:PER-J-M3"),
            (("EnergyDensityOfStates", "CGS-EMU"), "unit:PER-J-M3"),
            (("EnergyDensityOfStates", "CGS-GAUSS"), "unit:PER-J-M3"),
            (("EnergyDensityOfStates", "SI"), "unit:PER-J-M3"),
            (("EnergyPerArea", "CGS"), "unit:J-PER-M2"),
            (("EnergyPerArea", "CGS-EMU"), "unit:J-PER-M2"),
            (("EnergyPerArea", "CGS-GAUSS"), "unit:J-PER-M2"),
            (("EnergyPerArea", "IMPERIAL"), "unit:LB_F-PER-IN"),
            (("EnergyPerArea", "SI"), "unit:J-PER-M2"),
            (("EnergyPerArea", "USCS"), "unit:LB_F-PER-IN"),
            (("EnergyPerAreaElectricCharge", "CGS-EMU"), "unit:V-PER-M2"),
            (
                ("EnergyPerAreaElectricCharge", "CGS-GAUSS"),
                "unit:V-PER-M2",
            ),
            (("EnergyPerAreaElectricCharge", "SI"), "unit:V-PER-M2"),
            (
                ("EnergyPerMassAmountOfSubstance", "IMPERIAL"),
                "unit:BTU_IT-PER-MOL_LB",
            ),
            (
                ("EnergyPerMassAmountOfSubstance", "USCS"),
                "unit:BTU_IT-PER-MOL_LB",
            ),
            (
                ("EnergyPerSquareMagneticFluxDensity", "CGS-EMU"),
                "unit:J-PER-T2",
            ),
            (
                ("EnergyPerSquareMagneticFluxDensity", "CGS-GAUSS"),
                "unit:J-PER-T2",
            ),
            (
                ("EnergyPerSquareMagneticFluxDensity", "SI"),
                "unit:J-PER-T2",
            ),
            (("EnergyPerTemperature", "SI"), "unit:KiloJ-PER-K"),
            (
                ("EvaporativeHeatTransferCoefficient", "CGS"),
                "unit:W-PER-M2-PA",
            ),
            (
                ("EvaporativeHeatTransferCoefficient", "CGS-EMU"),
                "unit:W-PER-M2-PA",
            ),
            (
                ("EvaporativeHeatTransferCoefficient", "CGS-GAUSS"),
                "unit:W-PER-M2-PA",
            ),
            (
                ("EvaporativeHeatTransferCoefficient", "SI"),
                "unit:W-PER-M2-PA",
            ),
            (("ExposureRate", "CGS"), "unit:C-PER-KiloGM-SEC"),
            (("ExposureRate", "CGS-EMU"), "unit:C-PER-KiloGM-SEC"),
            (("ExposureRate", "CGS-GAUSS"), "unit:C-PER-KiloGM-SEC"),
            (("ExposureRate", "SI"), "unit:C-PER-KiloGM-SEC"),
            (("Flux", "CGS"), "unit:PER-M2-SEC"),
            (("Flux", "CGS-EMU"), "unit:PER-M2-SEC"),
            (("Flux", "CGS-GAUSS"), "unit:PER-M2-SEC"),
            (("Flux", "SI"), "unit:PER-M2-SEC"),
            (("Force", "CGS"), "unit:N"),
            (("Force", "CGS-EMU"), "unit:N"),
            (("Force", "CGS-GAUSS"), "unit:N"),
            (("Force", "IMPERIAL"), "unit:PDL"),
            (("Force", "PLANCK"), "unit:PlanckForce"),
            (("Force", "SI"), "unit:N"),
            (("Force", "USCS"), "unit:PDL"),
            (("ForcePerAngle", "CGS"), "unit:N-PER-RAD"),
            (("ForcePerAngle", "CGS-EMU"), "unit:N-PER-RAD"),
            (("ForcePerAngle", "CGS-GAUSS"), "unit:N-PER-RAD"),
            (("ForcePerAngle", "SI"), "unit:N-PER-RAD"),
            (("ForcePerArea", "CGS"), "unit:PA"),
            (("ForcePerArea", "CGS-EMU"), "unit:PA"),
            (("ForcePerArea", "CGS-GAUSS"), "unit:PA"),
            (("ForcePerArea", "IMPERIAL"), "unit:PSI"),
            (("ForcePerArea", "PLANCK"), "unit:PlanckPressure"),
            (("ForcePerArea", "SI"), "unit:PA"),
            (("ForcePerArea", "USCS"), "unit:PSI"),
            (("ForcePerAreaTime", "CGS"), "unit:PA-PER-HR"),
            (("ForcePerAreaTime", "CGS-EMU"), "unit:PA-PER-HR"),
            (("ForcePerAreaTime", "CGS-GAUSS"), "unit:PA-PER-HR"),
            (("ForcePerAreaTime", "IMPERIAL"), "unit:LB_F-PER-IN2-SEC"),
            (("ForcePerAreaTime", "SI"), "unit:PA-PER-HR"),
            (("ForcePerAreaTime", "USCS"), "unit:LB_F-PER-IN2-SEC"),
            (("ForcePerElectricCharge", "CGS"), "unit:N-PER-C"),
            (("ForcePerElectricCharge", "CGS-EMU"), "unit:N-PER-C"),
            (("ForcePerElectricCharge", "CGS-GAUSS"), "unit:N-PER-C"),
            (("ForcePerElectricCharge", "SI"), "unit:N-PER-C"),
            (("ForcePerLength", "CGS"), "unit:N-PER-M"),
            (("ForcePerLength", "CGS-EMU"), "unit:N-PER-M"),
            (("ForcePerLength", "CGS-GAUSS"), "unit:N-PER-M"),
            (("ForcePerLength", "IMPERIAL"), "unit:LB_F-PER-FT"),
            (("ForcePerLength", "SI"), "unit:N-PER-M"),
            (("ForcePerLength", "USCS"), "unit:LB_F-PER-FT"),
            (("Frequency", "CGS"), "unit:HZ"),
            (("Frequency", "CGS-EMU"), "unit:HZ"),
            (("Frequency", "CGS-GAUSS"), "unit:HZ"),
            (("Frequency", "IMPERIAL"), "unit:HZ"),
            (("Frequency", "PLANCK"), "unit:PlanckFrequency"),
            (("Frequency", "SI"), "unit:HZ"),
            (("Frequency", "USCS"), "unit:HZ"),
            (("HallCoefficient", "CGS"), "unit:M3-PER-C"),
            (("HallCoefficient", "CGS-EMU"), "unit:M3-PER-C"),
            (("HallCoefficient", "CGS-GAUSS"), "unit:M3-PER-C"),
            (("HallCoefficient", "SI"), "unit:M3-PER-C"),
            (("HeatCapacity", "IMPERIAL"), "unit:BTU_IT-PER-DEG_F"),
            (("HeatCapacity", "SI"), "unit:J-PER-K"),
            (("HeatCapacity", "USCS"), "unit:BTU_IT-PER-DEG_F"),
            (("HeatFlowRate", "CGS"), "unit:CAL_TH-PER-MIN"),
            (("HeatFlowRate", "IMPERIAL"), "unit:BTU_TH-PER-HR"),
            (("HeatFlowRate", "USCS"), "unit:BTU_TH-PER-HR"),
            (("HydraulicPermeability", "CGS"), "unit:DARCY"),
            (("HydraulicPermeability", "SI"), "unit:DARCY"),
            (("Inductance", "CGS"), "unit:H_Ab"),
            (("Inductance", "CGS-EMU"), "unit:H"),
            (("Inductance", "CGS-ESU"), "unit:H_Stat"),
            (("Inductance", "CGS-GAUSS"), "unit:H"),
            (("Inductance", "SI"), "unit:H"),
            (("InformationEntropy", "ASU"), "unit:BAN"),
            (("InformationEntropy", "CGS"), "unit:BAN"),
            (("InformationEntropy", "CGS-EMU"), "unit:BAN"),
            (("InformationEntropy", "CGS-ESU"), "unit:BAN"),
            (("InformationEntropy", "CGS-GAUSS"), "unit:BAN"),
            (("InformationEntropy", "IMPERIAL"), "unit:BAN"),
            (("InformationEntropy", "PLANCK"), "unit:BAN"),
            (("InformationEntropy", "SI"), "unit:BAN"),
            (("InverseAmountOfSubstance", "SI"), "unit:PER-MOL"),
            (("InverseEnergy", "CGS-EMU"), "unit:PER-KiloVA-HR"),
            (("InverseEnergy", "CGS-GAUSS"), "unit:PER-KiloVA-HR"),
            (("InverseEnergy", "SI"), "unit:PER-KiloVA-HR"),
            (("InverseLength", "CGS"), "unit:KY"),
            (("InverseLength", "CGS-EMU"), "unit:PER-M"),
            (("InverseLength", "CGS-GAUSS"), "unit:KY"),
            (("InverseLength", "SI"), "unit:PER-M"),
            (("InverseLengthTemperature", "SI"), "unit:PER-M-K"),
            (("InverseMagneticFlux", "CGS-EMU"), "unit:PER-WB"),
            (("InverseMagneticFlux", "CGS-GAUSS"), "unit:PER-WB"),
            (("InverseMagneticFlux", "SI"), "unit:PER-WB"),
            (("InverseMass", "CGS"), "unit:PER-GM"),
            (("InverseMass", "CGS-EMU"), "unit:PER-GM"),
            (("InverseMass", "CGS-GAUSS"), "unit:PER-GM"),
            (("InverseMass", "SI"), "unit:PER-GM"),
            (("InversePermittivity", "CGS"), "unit:M-PER-FARAD"),
            (("InversePermittivity", "CGS-EMU"), "unit:M-PER-FARAD"),
            (("InversePermittivity", "CGS-GAUSS"), "unit:M-PER-FARAD"),
            (("InversePermittivity", "SI"), "unit:M-PER-FARAD"),
            (("InverseSquareEnergy", "CGS"), "unit:PER-J2"),
            (("InverseSquareEnergy", "CGS-EMU"), "unit:PER-J2"),
            (("InverseSquareEnergy", "CGS-GAUSS"), "unit:PER-J2"),
            (("InverseSquareEnergy", "SI"), "unit:PER-J2"),
            (("InverseSquareMass", "PLANCK"), "unit:PER-PlanckMass2"),
            (("InverseSquareMass", "SI"), "unit:PER-KiloGM2"),
            (("InverseSquareTime", "CGS"), "unit:PER-SEC2"),
            (("InverseSquareTime", "CGS-EMU"), "unit:PER-SEC2"),
            (("InverseSquareTime", "CGS-GAUSS"), "unit:PER-SEC2"),
            (("InverseSquareTime", "IMPERIAL"), "unit:PER-SEC2"),
            (("InverseSquareTime", "SI"), "unit:PER-SEC2"),
            (("InverseSquareTime", "USCS"), "unit:PER-SEC2"),
            (("InverseTimeTemperature", "SI"), "unit:HZ-PER-K"),
            (("InverseVolume", "CGS"), "unit:PER-L"),
            (("InverseVolume", "CGS-EMU"), "unit:PER-L"),
            (("InverseVolume", "CGS-GAUSS"), "unit:PER-L"),
            (("InverseVolume", "IMPERIAL"), "unit:PER-FT3"),
            (("InverseVolume", "SI"), "unit:PER-L"),
            (("InverseVolume", "USCS"), "unit:PER-FT3"),
            (("Irradiance", "CGS"), "unit:MegaJ-PER-M2-DAY"),
            (("Irradiance", "CGS-EMU"), "unit:MegaJ-PER-M2-DAY"),
            (("Irradiance", "CGS-GAUSS"), "unit:MegaJ-PER-M2-DAY"),
            (("Irradiance", "SI"), "unit:MegaJ-PER-M2-DAY"),
            (("KinematicViscosity", "CGS"), "unit:ST"),
            (("Length", "CGS"), "unit:CentiM"),
            (("Length", "CGS-EMU"), "unit:CentiM"),
            (("Length", "CGS-GAUSS"), "unit:CentiM"),
            (("Length", "IMPERIAL"), "unit:CH"),
            (("Length", "PLANCK"), "unit:PlanckLength"),
            (("Length", "SI"), "unit:M"),
            (("Length", "USCS"), "unit:CH"),
            (("LengthEnergy", "CGS"), "unit:MegaEV-FemtoM"),
            (("LengthEnergy", "CGS-EMU"), "unit:MegaEV-FemtoM"),
            (("LengthEnergy", "CGS-GAUSS"), "unit:MegaEV-FemtoM"),
            (("LengthEnergy", "SI"), "unit:MegaEV-FemtoM"),
            (("LengthMass", "CGS"), "unit:M-KiloGM"),
            (("LengthMass", "CGS-EMU"), "unit:M-KiloGM"),
            (("LengthMass", "CGS-GAUSS"), "unit:M-KiloGM"),
            (("LengthMass", "IMPERIAL"), "unit:LB-IN"),
            (("LengthMass", "SI"), "unit:M-KiloGM"),
            (("LengthMass", "USCS"), "unit:LB-IN"),
            (("LengthMolarEnergy", "SI"), "unit:J-M-PER-MOL"),
            (("LengthTemperature", "CGS"), "unit:DEG_C-CentiM"),
            (("LengthTemperature", "SI"), "unit:K-M"),
            (("LengthTemperatureTime", "CGS"), "unit:CentiM-SEC-DEG_C"),
            (("LengthTemperatureTime", "SI"), "unit:CentiM-SEC-DEG_C"),
            (("LinearCompressibility", "CGS"), "unit:MicroM-PER-N"),
            (("LinearCompressibility", "CGS-EMU"), "unit:MicroM-PER-N"),
            (("LinearCompressibility", "CGS-GAUSS"), "unit:MicroM-PER-N"),
            (("LinearCompressibility", "SI"), "unit:MicroM-PER-N"),
            (("LinearEnergyTransfer", "CGS"), "unit:KiloEV-PER-MicroM"),
            (
                ("LinearEnergyTransfer", "CGS-EMU"),
                "unit:KiloEV-PER-MicroM",
            ),
            (
                ("LinearEnergyTransfer", "CGS-GAUSS"),
                "unit:KiloEV-PER-MicroM",
            ),
            (("LinearEnergyTransfer", "SI"), "unit:KiloEV-PER-MicroM"),
            (("LinearMomentum", "CGS"), "unit:N-SEC"),
            (("LinearMomentum", "CGS-EMU"), "unit:N-SEC"),
            (("LinearMomentum", "CGS-GAUSS"), "unit:N-SEC"),
            (("LinearMomentum", "PLANCK"), "unit:PlanckMomentum"),
            (("LinearMomentum", "SI"), "unit:N-SEC"),
            (("LinearThermalExpansion", "IMPERIAL"), "unit:FT-PER-DEG_F"),
            (("LinearThermalExpansion", "SI"), "unit:M-PER-K"),
            (("LinearThermalExpansion", "USCS"), "unit:FT-PER-DEG_F"),
            (("LinearVelocity", "CGS"), "unit:GigaHZ-M"),
            (("LinearVelocity", "CGS-EMU"), "unit:GigaHZ-M"),
            (("LinearVelocity", "CGS-GAUSS"), "unit:GigaHZ-M"),
            (("LinearVelocity", "IMPERIAL"), "unit:FT-PER-HR"),
            (("LinearVelocity", "SI"), "unit:GigaHZ-M"),
            (("LinearVelocity", "USCS"), "unit:KN"),
            (("LineicPower", "CGS"), "unit:W-PER-M"),
            (("LineicPower", "CGS-EMU"), "unit:W-PER-M"),
            (("LineicPower", "CGS-GAUSS"), "unit:W-PER-M"),
            (("LineicPower", "SI"), "unit:W-PER-M"),
            (("LiquidVolume", "CGS"), "unit:CentiL"),
            (("LiquidVolume", "CGS-EMU"), "unit:CentiL"),
            (("LiquidVolume", "CGS-GAUSS"), "unit:CentiL"),
            (("LiquidVolume", "IMPERIAL"), "unit:GAL_UK"),
            (("LiquidVolume", "SI"), "unit:CentiL"),
            (("LiquidVolume", "USCS"), "unit:CUP"),
            (("LorenzCoefficient", "SI"), "unit:V2-PER-K2"),
            (("Luminance", "CGS"), "unit:LA"),
            (("Luminance", "SI"), "unit:CD-PER-M2"),
            (("Luminance", "USCS"), "unit:LA_FT"),
            (("LuminousEfficacy", "SI"), "unit:LM-PER-W"),
            (("LuminousEnergy", "SI"), "unit:LM-SEC"),
            (("LuminousExposure", "SI"), "unit:LUX-HR"),
            (("LuminousFlux", "SI"), "unit:LM"),
            (("LuminousFluxPerArea", "CGS"), "unit:PHOT"),
            (("LuminousFluxPerArea", "SI"), "unit:LUX"),
            (("LuminousIntensity", "CGS"), "unit:CP"),
            (("LuminousIntensity", "SI"), "unit:CD"),
            (("LuminousIntensityDistribution", "SI"), "unit:CD-PER-LM"),
            (("MachNumber", "ASU"), "unit:MACH"),
            (("MachNumber", "CGS"), "unit:MACH"),
            (("MachNumber", "CGS-EMU"), "unit:MACH"),
            (("MachNumber", "CGS-ESU"), "unit:MACH"),
            (("MachNumber", "CGS-GAUSS"), "unit:MACH"),
            (("MachNumber", "IMPERIAL"), "unit:MACH"),
            (("MachNumber", "PLANCK"), "unit:MACH"),
            (("MachNumber", "SI"), "unit:MACH"),
            (("MagneticAreaMoment", "CGS"), "unit:A_Ab-CentiM2"),
            (("MagneticAreaMoment", "CGS-EMU"), "unit:A-M2"),
            (("MagneticAreaMoment", "CGS-GAUSS"), "unit:A-M2"),
            (("MagneticAreaMoment", "SI"), "unit:A-M2"),
            (("MagneticDipoleMoment", "CGS-EMU"), "unit:WB-M"),
            (("MagneticDipoleMoment", "CGS-GAUSS"), "unit:WB-M"),
            (("MagneticDipoleMoment", "SI"), "unit:WB-M"),
            (("MagneticFieldStrength", "CGS"), "unit:OERSTED"),
            (("MagneticFieldStrength", "CGS-EMU"), "unit:A-PER-M"),
            (("MagneticFieldStrength", "CGS-GAUSS"), "unit:A-PER-M"),
            (("MagneticFieldStrength", "SI"), "unit:A-PER-M"),
            (("MagneticFieldStrength", "USCS"), "unit:AT-PER-IN"),
            (("MagneticFlux", "CGS"), "unit:MX"),
            (("MagneticFlux", "CGS-EMU"), "unit:WB"),
            (("MagneticFlux", "CGS-GAUSS"), "unit:WB"),
            (("MagneticFlux", "SI"), "unit:WB"),
            (("MagneticFluxDensity", "CGS"), "unit:T_Ab"),
            (("MagneticFluxDensity", "CGS-EMU"), "unit:T"),
            (("MagneticFluxDensity", "CGS-GAUSS"), "unit:T"),
            (("MagneticFluxDensity", "SI"), "unit:T"),
            (("MagneticFluxPerLength", "CGS-EMU"), "unit:T-M"),
            (("MagneticFluxPerLength", "CGS-GAUSS"), "unit:T-M"),
            (("MagneticFluxPerLength", "SI"), "unit:T-M"),
            (("MagneticReluctivity", "CGS-EMU"), "unit:PER-T-M"),
            (("MagneticReluctivity", "CGS-GAUSS"), "unit:PER-T-M"),
            (("MagneticReluctivity", "SI"), "unit:PER-T-M"),
            (("MagneticVectorPotential", "CGS-EMU"), "unit:WB-PER-M"),
            (("MagneticVectorPotential", "CGS-GAUSS"), "unit:WB-PER-M"),
            (("MagneticVectorPotential", "SI"), "unit:WB-PER-M"),
            (("MagnetomotiveForce", "CGS"), "unit:GI"),
            (("MagnetomotiveForce", "CGS-EMU"), "unit:GI"),
            (("MagnetomotiveForce", "SI"), "unit:AT"),
            (("Mass", "CGS"), "unit:GM"),
            (("Mass", "CGS-EMU"), "unit:GM"),
            (("Mass", "CGS-GAUSS"), "unit:GM"),
            (("Mass", "IMPERIAL"), "unit:LB"),
            (("Mass", "PLANCK"), "unit:PlanckMass"),
            (("Mass", "SI"), "unit:KiloGM"),
            (("Mass", "USCS"), "unit:LB"),
            (("MassAttenuationCoefficient", "CGS"), "unit:M2-PER-GM"),
            (("MassAttenuationCoefficient", "CGS-EMU"), "unit:M2-PER-GM"),
            (
                ("MassAttenuationCoefficient", "CGS-GAUSS"),
                "unit:M2-PER-GM",
            ),
            (("MassAttenuationCoefficient", "SI"), "unit:M2-PER-GM"),
            (
                ("MassConcentrationRateOfChange", "CGS"),
                "unit:MicroGM-PER-L-DAY",
            ),
            (
                ("MassConcentrationRateOfChange", "CGS-EMU"),
                "unit:MicroGM-PER-L-DAY",
            ),
            (
                ("MassConcentrationRateOfChange", "CGS-GAUSS"),
                "unit:MicroGM-PER-L-DAY",
            ),
            (
                ("MassConcentrationRateOfChange", "SI"),
                "unit:MicroGM-PER-L-DAY",
            ),
            (("MassFlowRate", "CGS"), "unit:GM-PER-HR"),
            (("MassFlowRate", "CGS-EMU"), "unit:GM-PER-HR"),
            (("MassFlowRate", "CGS-GAUSS"), "unit:GM-PER-HR"),
            (("MassFlowRate", "IMPERIAL"), "unit:LB-PER-HR"),
            (("MassFlowRate", "SI"), "unit:GM-PER-HR"),
            (("MassFlowRate", "USCS"), "unit:LB-PER-HR"),
            (("MassPerArea", "CGS"), "unit:GM-PER-HA"),
            (("MassPerArea", "CGS-EMU"), "unit:GM-PER-HA"),
            (("MassPerArea", "CGS-GAUSS"), "unit:GM-PER-HA"),
            (("MassPerArea", "IMPERIAL"), "unit:LB-PER-AC"),
            (("MassPerArea", "SI"), "unit:GM-PER-HA"),
            (("MassPerArea", "USCS"), "unit:LB-PER-AC"),
            (("MassPerAreaTime", "CGS"), "unit:GM-PER-M2-YR"),
            (("MassPerAreaTime", "CGS-EMU"), "unit:GM-PER-M2-YR"),
            (("MassPerAreaTime", "CGS-GAUSS"), "unit:GM-PER-M2-YR"),
            (("MassPerAreaTime", "SI"), "unit:GM-PER-M2-HR"),
            (("MassPerElectricCharge", "CGS-EMU"), "unit:T-SEC"),
            (("MassPerElectricCharge", "CGS-GAUSS"), "unit:T-SEC"),
            (("MassPerElectricCharge", "SI"), "unit:T-SEC"),
            (("MassPerEnergy", "CGS"), "unit:KiloGM-PER-J"),
            (("MassPerEnergy", "CGS-EMU"), "unit:KiloGM-PER-J"),
            (("MassPerEnergy", "CGS-GAUSS"), "unit:KiloGM-PER-J"),
            (("MassPerEnergy", "IMPERIAL"), "unit:KiloGM-PER-MegaBTU_IT"),
            (("MassPerEnergy", "SI"), "unit:KiloGM-PER-J"),
            (("MassPerEnergy", "USCS"), "unit:KiloGM-PER-MegaBTU_IT"),
            (("MassPerLength", "CGS"), "unit:GM-PER-M"),
            (("MassPerLength", "CGS-EMU"), "unit:GM-PER-M"),
            (("MassPerLength", "CGS-GAUSS"), "unit:GM-PER-M"),
            (("MassPerLength", "IMPERIAL"), "unit:LB-PER-FT"),
            (("MassPerLength", "SI"), "unit:GM-PER-M"),
            (("MassPerLength", "USCS"), "unit:LB-PER-FT"),
            (("MassPerTime", "CGS"), "unit:N-SEC-PER-M"),
            (("MassPerTime", "CGS-EMU"), "unit:N-SEC-PER-M"),
            (("MassPerTime", "CGS-GAUSS"), "unit:N-SEC-PER-M"),
            (("MassPerTime", "SI"), "unit:N-SEC-PER-M"),
            (("MassRatio", "CGS"), "unit:GM-PER-GM"),
            (("MassRatio", "CGS-EMU"), "unit:GM-PER-GM"),
            (("MassRatio", "CGS-GAUSS"), "unit:GM-PER-GM"),
            (("MassRatio", "SI"), "unit:GM-PER-GM"),
            (
                ("MassSpecificBiogeochemicalRate", "CGS"),
                "unit:MilliGM-PER-GM-HR",
            ),
            (
                ("MassSpecificBiogeochemicalRate", "CGS-EMU"),
                "unit:MilliGM-PER-GM-HR",
            ),
            (
                ("MassSpecificBiogeochemicalRate", "CGS-GAUSS"),
                "unit:MilliGM-PER-GM-HR",
            ),
            (
                ("MassSpecificBiogeochemicalRate", "SI"),
                "unit:MicroGM-PER-GM-HR",
            ),
            (("MassTemperature", "CGS"), "unit:LB-DEG_R"),
            (("MassTemperature", "IMPERIAL"), "unit:LB-DEG_F"),
            (("MassTemperature", "SI"), "unit:KiloGM-K"),
            (("MassTemperature", "USCS"), "unit:LB-DEG_F"),
            (("MechanicalMobility", "CGS"), "unit:MOHM"),
            (("Mobility", "CGS-EMU"), "unit:M2-PER-V-SEC"),
            (("Mobility", "CGS-GAUSS"), "unit:M2-PER-V-SEC"),
            (("Mobility", "SI"), "unit:M2-PER-V-SEC"),
            (
                ("ModulusOfRotationalSubgradeReaction", "CGS"),
                "unit:N-M-PER-M-RAD",
            ),
            (
                ("ModulusOfRotationalSubgradeReaction", "CGS-EMU"),
                "unit:N-M-PER-M-RAD",
            ),
            (
                ("ModulusOfRotationalSubgradeReaction", "CGS-GAUSS"),
                "unit:N-M-PER-M-RAD",
            ),
            (
                ("ModulusOfRotationalSubgradeReaction", "SI"),
                "unit:N-M-PER-DEG-M",
            ),
            (("MolarAbsorptionCoefficient", "SI"), "unit:M2-PER-MOL"),
            (("MolarAngularMomentum", "SI"), "unit:J-SEC-PER-MOL"),
            (("MolarConductivity", "SI"), "unit:S-M2-PER-MOL"),
            (("MolarEnergy", "CGS"), "unit:KiloCAL-PER-MOL"),
            (("MolarEnergy", "IMPERIAL"), "unit:KiloCAL-PER-MOL"),
            (("MolarEnergy", "SI"), "unit:J-PER-MOL"),
            (("MolarEnergy", "USCS"), "unit:KiloCAL-PER-MOL"),
            (("MolarFlowRate", "SI"), "unit:MOL-PER-HR"),
            (("MolarFluxDensity", "CGS"), "unit:MilliMOL-PER-M2-HR"),
            (("MolarFluxDensity", "CGS-EMU"), "unit:MilliMOL-PER-M2-HR"),
            (("MolarFluxDensity", "CGS-GAUSS"), "unit:MilliMOL-PER-M2-HR"),
            (("MolarFluxDensity", "SI"), "unit:MilliMOL-PER-M2-HR"),
            (("MolarHeatCapacity", "CGS"), "unit:KiloCAL-PER-MOL-DEG_C"),
            (
                ("MolarHeatCapacity", "IMPERIAL"),
                "unit:KiloCAL-PER-MOL-DEG_C",
            ),
            (("MolarHeatCapacity", "SI"), "unit:J-PER-MOL-K"),
            (("MolarHeatCapacity", "USCS"), "unit:KiloCAL-PER-MOL-DEG_C"),
            (("MolarMass", "SI"), "unit:GM-PER-MOL"),
            (("MolarOpticalRotatoryPower", "SI"), "unit:RAD-M2-PER-MOL"),
            (("MolarRefractivity", "SI"), "unit:L-PER-MOL"),
            (("MolecularMass", "CGS"), "unit:DA"),
            (("MomentOfForce", "CGS"), "unit:N-M"),
            (("MomentOfForce", "CGS-EMU"), "unit:N-M"),
            (("MomentOfForce", "CGS-GAUSS"), "unit:N-M"),
            (("MomentOfForce", "IMPERIAL"), "unit:LB_F-FT"),
            (("MomentOfForce", "SI"), "unit:N-M"),
            (("MomentOfForce", "USCS"), "unit:LB_F-FT"),
            (("MomentOfInertia", "CGS"), "unit:KiloGM-M2"),
            (("MomentOfInertia", "CGS-EMU"), "unit:KiloGM-M2"),
            (("MomentOfInertia", "CGS-GAUSS"), "unit:KiloGM-M2"),
            (("MomentOfInertia", "IMPERIAL"), "unit:LB-FT2"),
            (("MomentOfInertia", "SI"), "unit:KiloGM-M2"),
            (("MomentOfInertia", "USCS"), "unit:LB-FT2"),
            (("MomentumPerAngle", "CGS"), "unit:N-SEC-PER-RAD"),
            (("MomentumPerAngle", "CGS-EMU"), "unit:N-SEC-PER-RAD"),
            (("MomentumPerAngle", "CGS-GAUSS"), "unit:N-SEC-PER-RAD"),
            (("MomentumPerAngle", "SI"), "unit:N-SEC-PER-RAD"),
            (("Pace", "CGS"), "unit:MIN-PER-KiloM"),
            (("Pace", "CGS-EMU"), "unit:MIN-PER-KiloM"),
            (("Pace", "CGS-GAUSS"), "unit:MIN-PER-KiloM"),
            (("Pace", "IMPERIAL"), "unit:MIN-PER-MI"),
            (("Pace", "SI"), "unit:MIN-PER-KiloM"),
            (("ParticleFluence", "CGS"), "unit:PER-M2"),
            (("ParticleFluence", "CGS-EMU"), "unit:PER-M2"),
            (("ParticleFluence", "CGS-GAUSS"), "unit:PER-M2"),
            (("ParticleFluence", "SI"), "unit:PER-M2"),
            (("PermeabilityRatio", "CGS-EMU"), "unit:PERMEABILITY_REL"),
            (("Permittivity", "CGS"), "unit:FARAD-PER-M"),
            (("Permittivity", "CGS-EMU"), "unit:FARAD-PER-M"),
            (("Permittivity", "CGS-GAUSS"), "unit:FARAD-PER-M"),
            (("Permittivity", "SI"), "unit:FARAD-PER-M"),
            (("PhotonIntensity", "CGS"), "unit:PER-SEC-SR"),
            (("PhotonIntensity", "CGS-EMU"), "unit:PER-SEC-SR"),
            (("PhotonIntensity", "CGS-GAUSS"), "unit:PER-SEC-SR"),
            (("PhotonIntensity", "SI"), "unit:PER-SEC-SR"),
            (("PhotonRadiance", "CGS"), "unit:PER-SEC-M2-SR"),
            (("PhotonRadiance", "CGS-EMU"), "unit:PER-SEC-M2-SR"),
            (("PhotonRadiance", "CGS-GAUSS"), "unit:PER-SEC-M2-SR"),
            (("PhotonRadiance", "SI"), "unit:PER-SEC-M2-SR"),
            (("PhotosyntheticPhotonFlux", "SI"), "unit:MicroMOL-PER-SEC"),
            (
                ("PhotosyntheticPhotonFluxDensity", "SI"),
                "unit:MOL-PER-M2-DAY",
            ),
            (("Polarizability", "CGS"), "unit:C2-M2-PER-J"),
            (("Polarizability", "CGS-EMU"), "unit:C-M2-PER-V"),
            (("Polarizability", "CGS-GAUSS"), "unit:C-M2-PER-V"),
            (("Polarizability", "SI"), "unit:C-M2-PER-V"),
            (("Power", "CGS"), "unit:W"),
            (("Power", "CGS-EMU"), "unit:W"),
            (("Power", "CGS-GAUSS"), "unit:W"),
            (("Power", "IMPERIAL"), "unit:HP"),
            (("Power", "PLANCK"), "unit:W"),
            (("Power", "SI"), "unit:W"),
            (("Power", "USCS"), "unit:HP"),
            (("PowerArea", "CGS"), "unit:W-M2"),
            (("PowerArea", "CGS-EMU"), "unit:W-M2"),
            (("PowerArea", "CGS-GAUSS"), "unit:W-M2"),
            (("PowerArea", "SI"), "unit:W-M2"),
            (("PowerAreaPerSolidAngle", "CGS"), "unit:W-M2-PER-SR"),
            (("PowerAreaPerSolidAngle", "CGS-EMU"), "unit:W-M2-PER-SR"),
            (("PowerAreaPerSolidAngle", "CGS-GAUSS"), "unit:W-M2-PER-SR"),
            (("PowerAreaPerSolidAngle", "SI"), "unit:W-M2-PER-SR"),
            (("PowerDensity", "CGS"), "unit:W-PER-M3"),
            (("PowerDensity", "CGS-EMU"), "unit:W-PER-M3"),
            (("PowerDensity", "CGS-GAUSS"), "unit:W-PER-M3"),
            (("PowerDensity", "SI"), "unit:W-PER-M3"),
            (("PowerPerArea", "CGS"), "unit:W-PER-M2"),
            (("PowerPerArea", "CGS-EMU"), "unit:W-PER-M2"),
            (("PowerPerArea", "CGS-GAUSS"), "unit:W-PER-M2"),
            (("PowerPerArea", "IMPERIAL"), "unit:BTU_IT-PER-HR-FT2"),
            (("PowerPerArea", "SI"), "unit:W-PER-M2"),
            (("PowerPerArea", "USCS"), "unit:W-PER-FT2"),
            (("PowerPerAreaQuarticTemperature", "SI"), "unit:W-PER-M2-K4"),
            (("PowerPerElectricCharge", "CGS-EMU"), "unit:V-PER-SEC"),
            (("PowerPerElectricCharge", "CGS-GAUSS"), "unit:V-PER-SEC"),
            (("PowerPerElectricCharge", "SI"), "unit:V-PER-SEC"),
            (("PressureCoefficient", "SI"), "unit:PA-PER-K"),
            (
                ("PressureInRelationToVolumeFlowRate", "CGS"),
                "unit:PA-SEC-PER-M3",
            ),
            (
                ("PressureInRelationToVolumeFlowRate", "CGS-EMU"),
                "unit:PA-SEC-PER-M3",
            ),
            (
                ("PressureInRelationToVolumeFlowRate", "CGS-GAUSS"),
                "unit:PA-SEC-PER-M3",
            ),
            (
                ("PressureInRelationToVolumeFlowRate", "SI"),
                "unit:PA-SEC-PER-M3",
            ),
            (("PressureLossPerLength", "CGS"), "unit:KiloGM-PER-M2-SEC2"),
            (
                ("PressureLossPerLength", "CGS-EMU"),
                "unit:KiloGM-PER-M2-SEC2",
            ),
            (
                ("PressureLossPerLength", "CGS-GAUSS"),
                "unit:KiloGM-PER-M2-SEC2",
            ),
            (("PressureLossPerLength", "SI"), "unit:KiloGM-PER-M2-SEC2"),
            (("PressureRatio", "CGS"), "unit:PA-PER-BAR"),
            (("PressureRatio", "IMPERIAL"), "unit:PSI-PER-PSI"),
            (("PressureRatio", "USCS"), "unit:PSI-PER-PSI"),
            (
                ("QuarticElectricDipoleMomentPerCubicEnergy", "CGS"),
                "unit:C4-M4-PER-J3",
            ),
            (
                ("QuarticElectricDipoleMomentPerCubicEnergy", "CGS-EMU"),
                "unit:C4-M4-PER-J3",
            ),
            (
                ("QuarticElectricDipoleMomentPerCubicEnergy", "CGS-GAUSS"),
                "unit:C4-M4-PER-J3",
            ),
            (
                ("QuarticElectricDipoleMomentPerCubicEnergy", "SI"),
                "unit:C4-M4-PER-J3",
            ),
            (("Radiance", "CGS"), "unit:W-PER-M2-SR"),
            (("Radiance", "CGS-EMU"), "unit:W-PER-M2-SR"),
            (("Radiance", "CGS-GAUSS"), "unit:W-PER-M2-SR"),
            (("Radiance", "SI"), "unit:W-PER-M2-SR"),
            (("RadiantIntensity", "CGS"), "unit:W-PER-SR"),
            (("RadiantIntensity", "CGS-EMU"), "unit:W-PER-SR"),
            (("RadiantIntensity", "CGS-GAUSS"), "unit:W-PER-SR"),
            (("RadiantIntensity", "SI"), "unit:W-PER-SR"),
            (("RelativeHumidity", "ASU"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "CGS"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "CGS-EMU"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "CGS-ESU"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "CGS-GAUSS"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "IMPERIAL"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "PLANCK"), "unit:PERCENT_RH"),
            (("RelativeHumidity", "SI"), "unit:PERCENT_RH"),
            (("Reluctance", "CGS-EMU"), "unit:PER-H"),
            (("Reluctance", "CGS-GAUSS"), "unit:PER-H"),
            (("Reluctance", "SI"), "unit:PER-H"),
            (("Resistance", "CGS"), "unit:OHM_Ab"),
            (("Resistance", "CGS-EMU"), "unit:OHM"),
            (("Resistance", "CGS-ESU"), "unit:OHM_Stat"),
            (("Resistance", "CGS-GAUSS"), "unit:OHM"),
            (("Resistance", "PLANCK"), "unit:OHM"),
            (("Resistance", "SI"), "unit:OHM"),
            (("Resistivity", "CGS-EMU"), "unit:OHM-M"),
            (("Resistivity", "CGS-GAUSS"), "unit:OHM-M"),
            (("Resistivity", "SI"), "unit:OHM-M"),
            (("RichardsonConstant", "SI"), "unit:A-PER-M2-K2"),
            (("RotationalFrequency", "IMPERIAL"), "unit:CYC-PER-SEC"),
            (("RotationalFrequency", "SI"), "unit:CYC-PER-SEC"),
            (("RotationalFrequency", "USCS"), "unit:CYC-PER-SEC"),
            (("SecondAxialMomentOfArea", "CGS"), "unit:M4"),
            (("SecondAxialMomentOfArea", "CGS-EMU"), "unit:M4"),
            (("SecondAxialMomentOfArea", "CGS-GAUSS"), "unit:M4"),
            (("SecondAxialMomentOfArea", "IMPERIAL"), "unit:IN4"),
            (("SecondAxialMomentOfArea", "SI"), "unit:M4"),
            (("SecondAxialMomentOfArea", "USCS"), "unit:IN4"),
            (("SectionAreaIntegral", "CGS"), "unit:M5"),
            (("SectionAreaIntegral", "CGS-EMU"), "unit:M5"),
            (("SectionAreaIntegral", "CGS-GAUSS"), "unit:M5"),
            (("SectionAreaIntegral", "SI"), "unit:M5"),
            (("SeebeckCoefficient", "SI"), "unit:V-PER-K"),
            (("SignalDetectionThreshold", "ASU"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "CGS"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "CGS-EMU"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "CGS-ESU"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "CGS-GAUSS"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "IMPERIAL"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "PLANCK"), "unit:DeciB_C"),
            (("SignalDetectionThreshold", "SI"), "unit:DeciB_C"),
            (("Slowing-DownDensity", "CGS"), "unit:PER-M3-SEC"),
            (("Slowing-DownDensity", "CGS-EMU"), "unit:PER-M3-SEC"),
            (("Slowing-DownDensity", "CGS-GAUSS"), "unit:PER-M3-SEC"),
            (("Slowing-DownDensity", "SI"), "unit:PER-M3-SEC"),
            (("SolidAngle", "ASU"), "unit:FA"),
            (("SolidAngle", "CGS"), "unit:FA"),
            (("SolidAngle", "CGS-EMU"), "unit:FA"),
            (("SolidAngle", "CGS-ESU"), "unit:FA"),
            (("SolidAngle", "CGS-GAUSS"), "unit:FA"),
            (("SolidAngle", "IMPERIAL"), "unit:FA"),
            (("SolidAngle", "PLANCK"), "unit:FA"),
            (("SolidAngle", "SI"), "unit:FA"),
            (("SoundExposure", "CGS"), "unit:PA2-SEC"),
            (("SoundExposure", "CGS-EMU"), "unit:PA2-SEC"),
            (("SoundExposure", "CGS-GAUSS"), "unit:PA2-SEC"),
            (("SoundExposure", "SI"), "unit:PA2-SEC"),
            (("SoundPressureLevel", "ASU"), "unit:B"),
            (("SoundPressureLevel", "CGS"), "unit:B"),
            (("SoundPressureLevel", "CGS-EMU"), "unit:B"),
            (("SoundPressureLevel", "CGS-ESU"), "unit:B"),
            (("SoundPressureLevel", "CGS-GAUSS"), "unit:B"),
            (("SoundPressureLevel", "IMPERIAL"), "unit:B"),
            (("SoundPressureLevel", "PLANCK"), "unit:B"),
            (("SoundPressureLevel", "SI"), "unit:B"),
            (("SpecificAcousticImpedance", "CGS"), "unit:RAYL"),
            (
                ("SpecificAcousticImpedance", "CGS-EMU"),
                "unit:N-SEC-PER-M3",
            ),
            (
                ("SpecificAcousticImpedance", "CGS-GAUSS"),
                "unit:N-SEC-PER-M3",
            ),
            (("SpecificAcousticImpedance", "SI"), "unit:RAYL_MKS"),
            (("SpecificActivity", "CGS"), "unit:BQ-PER-KiloGM"),
            (("SpecificActivity", "CGS-EMU"), "unit:BQ-PER-KiloGM"),
            (("SpecificActivity", "CGS-GAUSS"), "unit:BQ-PER-KiloGM"),
            (("SpecificActivity", "SI"), "unit:BQ-PER-KiloGM"),
            (("SpecificEnergy", "CGS"), "unit:J-PER-GM"),
            (("SpecificEnergy", "CGS-EMU"), "unit:J-PER-GM"),
            (("SpecificEnergy", "CGS-GAUSS"), "unit:J-PER-GM"),
            (("SpecificEnergy", "IMPERIAL"), "unit:BTU_IT-PER-LB"),
            (("SpecificEnergy", "SI"), "unit:J-PER-GM"),
            (("SpecificEnergy", "USCS"), "unit:BTU_IT-PER-LB"),
            (("SpecificHeatCapacity", "CGS"), "unit:CAL_IT-PER-GM-K"),
            (("SpecificHeatCapacity", "IMPERIAL"), "unit:CAL_IT-PER-GM-K"),
            (("SpecificHeatCapacity", "SI"), "unit:J-PER-GM-K"),
            (("SpecificHeatCapacity", "USCS"), "unit:CAL_IT-PER-GM-K"),
            (("SpecificHeatPressure", "SI"), "unit:J-PER-KiloGM-K-PA"),
            (("SpecificHeatVolume", "SI"), "unit:J-PER-KiloGM-K-M3"),
            (("SpecificModulus", "CGS"), "unit:M2-PER-SEC2"),
            (("SpecificModulus", "CGS-EMU"), "unit:M2-PER-SEC2"),
            (("SpecificModulus", "CGS-GAUSS"), "unit:M2-PER-SEC2"),
            (("SpecificModulus", "SI"), "unit:M2-PER-SEC2"),
            (
                ("SpecificOpticalRotatoryPower", "CGS"),
                "unit:RAD-M2-PER-KiloGM",
            ),
            (
                ("SpecificOpticalRotatoryPower", "CGS-EMU"),
                "unit:RAD-M2-PER-KiloGM",
            ),
            (
                ("SpecificOpticalRotatoryPower", "CGS-GAUSS"),
                "unit:RAD-M2-PER-KiloGM",
            ),
            (
                ("SpecificOpticalRotatoryPower", "SI"),
                "unit:RAD-M2-PER-KiloGM",
            ),
            (("SpecificVolume", "CGS"), "unit:DeciL-PER-GM"),
            (("SpecificVolume", "CGS-EMU"), "unit:DeciL-PER-GM"),
            (("SpecificVolume", "CGS-GAUSS"), "unit:DeciL-PER-GM"),
            (("SpecificVolume", "SI"), "unit:DeciL-PER-GM"),
            (("SpecificWeight", "CGS"), "unit:N-PER-M3"),
            (("SpecificWeight", "CGS-EMU"), "unit:N-PER-M3"),
            (("SpecificWeight", "CGS-GAUSS"), "unit:N-PER-M3"),
            (("SpecificWeight", "SI"), "unit:N-PER-M3"),
            (("SpectralAngularCrossSection", "CGS"), "unit:M2-PER-SR-J"),
            (
                ("SpectralAngularCrossSection", "CGS-EMU"),
                "unit:M2-PER-SR-J",
            ),
            (
                ("SpectralAngularCrossSection", "CGS-GAUSS"),
                "unit:M2-PER-SR-J",
            ),
            (("SpectralAngularCrossSection", "SI"), "unit:M2-PER-SR-J"),
            (("SpectralCrossSection", "CGS"), "unit:M2-PER-J"),
            (("SpectralCrossSection", "CGS-EMU"), "unit:M2-PER-J"),
            (("SpectralCrossSection", "CGS-GAUSS"), "unit:M2-PER-J"),
            (("SpectralCrossSection", "SI"), "unit:M2-PER-J"),
            (("SpectralRadiance", "CGS"), "unit:W-PER-M2-NanoM-SR"),
            (("SpectralRadiance", "CGS-EMU"), "unit:W-PER-M2-NanoM-SR"),
            (("SpectralRadiance", "CGS-GAUSS"), "unit:W-PER-M2-NanoM-SR"),
            (("SpectralRadiance", "SI"), "unit:W-PER-M2-MicroM"),
            (("SpectralRadiantEnergyDensity", "CGS"), "unit:J-PER-M4"),
            (("SpectralRadiantEnergyDensity", "CGS-EMU"), "unit:J-PER-M4"),
            (
                ("SpectralRadiantEnergyDensity", "CGS-GAUSS"),
                "unit:J-PER-M4",
            ),
            (("SpectralRadiantEnergyDensity", "SI"), "unit:J-PER-M4"),
            (("Speed", "CGS"), "unit:HZ-M"),
            (("Speed", "CGS-EMU"), "unit:HZ-M"),
            (("Speed", "CGS-GAUSS"), "unit:HZ-M"),
            (("Speed", "IMPERIAL"), "unit:FT3-PER-MIN-FT2"),
            (("Speed", "SI"), "unit:HZ-M"),
            (("Speed", "USCS"), "unit:FT3-PER-MIN-FT2"),
            (("SquareTime", "CGS"), "unit:SEC2"),
            (("SquareTime", "CGS-EMU"), "unit:SEC2"),
            (("SquareTime", "CGS-GAUSS"), "unit:SEC2"),
            (("SquareTime", "IMPERIAL"), "unit:SEC2"),
            (("SquareTime", "SI"), "unit:SEC2"),
            (("SquareTime", "USCS"), "unit:SEC2"),
            (
                ("StandardGravitationalParameter", "CGS"),
                "unit:M3-PER-SEC2",
            ),
            (
                ("StandardGravitationalParameter", "CGS-EMU"),
                "unit:M3-PER-SEC2",
            ),
            (
                ("StandardGravitationalParameter", "CGS-GAUSS"),
                "unit:M3-PER-SEC2",
            ),
            (("StandardGravitationalParameter", "SI"), "unit:M3-PER-SEC2"),
            (("StressIntensityFactor", "CGS"), "unit:PA-M0dot5"),
            (("StressIntensityFactor", "CGS-EMU"), "unit:PA-M0dot5"),
            (("StressIntensityFactor", "CGS-GAUSS"), "unit:PA-M0dot5"),
            (("StressIntensityFactor", "SI"), "unit:PA-M0dot5"),
            (
                ("StressOpticCoefficient", "CGS"),
                "unit:NanoM-PER-CentiM-MegaPA",
            ),
            (
                ("StressOpticCoefficient", "CGS-EMU"),
                "unit:NanoM-PER-CentiM-MegaPA",
            ),
            (
                ("StressOpticCoefficient", "CGS-GAUSS"),
                "unit:NanoM-PER-CentiM-MegaPA",
            ),
            (("StressOpticCoefficient", "IMPERIAL"), "unit:PER-PSI"),
            (
                ("StressOpticCoefficient", "SI"),
                "unit:NanoM-PER-CentiM-MegaPA",
            ),
            (("StressOpticCoefficient", "USCS"), "unit:PER-PSI"),
            (("SurfaceActivityDensity", "CGS"), "unit:BQ-PER-M2"),
            (("SurfaceActivityDensity", "CGS-EMU"), "unit:BQ-PER-M2"),
            (("SurfaceActivityDensity", "CGS-GAUSS"), "unit:BQ-PER-M2"),
            (("SurfaceActivityDensity", "SI"), "unit:BQ-PER-M2"),
            (("Temperature", "CGS"), "unit:DEG_C"),
            (("Temperature", "IMPERIAL"), "unit:DEG_F"),
            (("Temperature", "PLANCK"), "unit:PlanckTemperature"),
            (("Temperature", "SI"), "unit:K"),
            (("Temperature", "USCS"), "unit:DEG_F"),
            (("TemperatureAmountOfSubstance", "CGS"), "unit:MOL-DEG_C"),
            (("TemperatureAmountOfSubstance", "SI"), "unit:MOL-K"),
            (("TemperatureGradient", "CGS"), "unit:DEG_C-PER-M"),
            (("TemperatureGradient", "SI"), "unit:K-PER-M"),
            (("TemperaturePerMagneticFluxDensity", "SI"), "unit:K-PER-T"),
            (
                ("TemperaturePerSquareTime", "IMPERIAL"),
                "unit:DEG_F-PER-SEC2",
            ),
            (("TemperaturePerSquareTime", "SI"), "unit:K-PER-SEC2"),
            (("TemperaturePerSquareTime", "USCS"), "unit:DEG_F-PER-SEC2"),
            (("TemperaturePerTime", "CGS"), "unit:DEG_C-PER-HR"),
            (("TemperaturePerTime", "IMPERIAL"), "unit:DEG_F-PER-HR"),
            (("TemperaturePerTime", "SI"), "unit:K-PER-HR"),
            (("TemperaturePerTime", "USCS"), "unit:DEG_F-PER-HR"),
            (("TemperatureRatio", "ASU"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "CGS"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "CGS-EMU"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "CGS-ESU"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "CGS-GAUSS"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "IMPERIAL"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "PLANCK"), "unit:DEG_F-PER-K"),
            (("TemperatureRatio", "SI"), "unit:K-PER-K"),
            (("TemperatureVariance", "CGS"), "unit:DEG_C2"),
            (("TemperatureVariance", "SI"), "unit:DEG_C2"),
            (("ThermalConductance", "SI"), "unit:W-PER-K"),
            (
                ("ThermalConductivity", "CGS"),
                "unit:CAL_IT-PER-SEC-CentiM-K",
            ),
            (
                ("ThermalConductivity", "IMPERIAL"),
                "unit:BTU_IT-PER-SEC-FT-DEG_R",
            ),
            (("ThermalConductivity", "SI"), "unit:W-PER-M-K"),
            (
                ("ThermalConductivity", "USCS"),
                "unit:BTU_IT-PER-SEC-FT-DEG_R",
            ),
            (("ThermalEnergy", "CGS"), "unit:CAL_MEAN"),
            (("ThermalEnergy", "IMPERIAL"), "unit:BTU_MEAN"),
            (("ThermalEnergy", "USCS"), "unit:BTU_MEAN"),
            (("ThermalEnergyLength", "IMPERIAL"), "unit:BTU_IT-FT"),
            (("ThermalEnergyLength", "USCS"), "unit:BTU_IT-FT"),
            (("ThermalExpansionCoefficient", "SI"), "unit:PER-K"),
            (("ThermalInsulance", "CGS"), "unit:CLO"),
            (
                ("ThermalInsulance", "IMPERIAL"),
                "unit:DEG_F-HR-FT2-PER-BTU_IT",
            ),
            (("ThermalInsulance", "SI"), "unit:M2-K-PER-W"),
            (("ThermalInsulance", "USCS"), "unit:DEG_F-HR-FT2-PER-BTU_IT"),
            (
                ("ThermalResistance", "IMPERIAL"),
                "unit:DEG_F-HR-PER-BTU_IT",
            ),
            (("ThermalResistance", "SI"), "unit:K-PER-W"),
            (("ThermalResistance", "USCS"), "unit:DEG_F-HR-PER-BTU_IT"),
            (("ThermalResistivity", "SI"), "unit:K-M-PER-W"),
            (("ThrustToMassRatio", "CGS"), "unit:N-PER-KiloGM"),
            (("ThrustToMassRatio", "CGS-EMU"), "unit:N-PER-KiloGM"),
            (("ThrustToMassRatio", "CGS-GAUSS"), "unit:N-PER-KiloGM"),
            (("ThrustToMassRatio", "IMPERIAL"), "unit:LB_F-PER-LB"),
            (("ThrustToMassRatio", "SI"), "unit:N-PER-KiloGM"),
            (("ThrustToMassRatio", "USCS"), "unit:LB_F-PER-LB"),
            (("Time", "CGS"), "unit:SEC"),
            (("Time", "CGS-EMU"), "unit:SEC"),
            (("Time", "CGS-GAUSS"), "unit:SEC"),
            (("Time", "IMPERIAL"), "unit:HR"),
            (("Time", "PLANCK"), "unit:PlanckTime"),
            (("Time", "SI"), "unit:SEC"),
            (("Time", "USCS"), "unit:HR"),
            (("TimePerCount", "SI"), "unit:HR-PER-NUM"),
            (("TimeRatio", "CGS"), "unit:HR-PER-YR"),
            (("TimeRatio", "CGS-EMU"), "unit:HR-PER-YR"),
            (("TimeRatio", "CGS-GAUSS"), "unit:HR-PER-YR"),
            (("TimeRatio", "SI"), "unit:HR-PER-YR"),
            (("TimeRatio", "USCS"), "unit:HR-PER-YR"),
            (("TimeTemperature", "CGS"), "unit:DEG_C-HR"),
            (("TimeTemperature", "IMPERIAL"), "unit:DEG_F-HR"),
            (("TimeTemperature", "SI"), "unit:K-DAY"),
            (("TimeTemperature", "USCS"), "unit:DEG_F-HR"),
            (("TorquePerLength", "CGS"), "unit:N-M-PER-M"),
            (("TorquePerLength", "CGS-EMU"), "unit:N-M-PER-M"),
            (("TorquePerLength", "CGS-GAUSS"), "unit:N-M-PER-M"),
            (("TorquePerLength", "SI"), "unit:N-M-PER-M"),
            (("TorsionalSpringConstant", "CGS"), "unit:N-M-PER-RAD"),
            (("TorsionalSpringConstant", "CGS-EMU"), "unit:N-M-PER-RAD"),
            (("TorsionalSpringConstant", "CGS-GAUSS"), "unit:N-M-PER-RAD"),
            (("TorsionalSpringConstant", "SI"), "unit:N-M-PER-RAD"),
            (("TotalAtomicStoppingPower", "CGS"), "unit:J-M2"),
            (("TotalAtomicStoppingPower", "CGS-EMU"), "unit:J-M2"),
            (("TotalAtomicStoppingPower", "CGS-GAUSS"), "unit:J-M2"),
            (("TotalAtomicStoppingPower", "SI"), "unit:J-M2"),
            (("TotalLinearStoppingPower", "CGS"), "unit:J-PER-M"),
            (("TotalLinearStoppingPower", "CGS-EMU"), "unit:J-PER-M"),
            (("TotalLinearStoppingPower", "CGS-GAUSS"), "unit:J-PER-M"),
            (("TotalLinearStoppingPower", "SI"), "unit:J-PER-M"),
            (("TotalMassStoppingPower", "CGS"), "unit:J-M2-PER-KiloGM"),
            (
                ("TotalMassStoppingPower", "CGS-EMU"),
                "unit:J-M2-PER-KiloGM",
            ),
            (
                ("TotalMassStoppingPower", "CGS-GAUSS"),
                "unit:J-M2-PER-KiloGM",
            ),
            (("TotalMassStoppingPower", "SI"), "unit:J-M2-PER-KiloGM"),
            (("Turbidity", "CGS"), "unit:NTU"),
            (("VapourPermeability", "SI"), "unit:KiloGM-PER-PA-SEC-M"),
            (("VapourPermeance", "CGS"), "unit:KiloGM-PER-M2-PA-SEC"),
            (("VapourPermeance", "CGS-EMU"), "unit:KiloGM-PER-M2-PA-SEC"),
            (
                ("VapourPermeance", "CGS-GAUSS"),
                "unit:KiloGM-PER-M2-PA-SEC",
            ),
            (("VapourPermeance", "SI"), "unit:KiloGM-PER-M2-PA-SEC"),
            (("VapourPermeance", "USCS"), "unit:PERM_US"),
            (("VentilationRatePerFloorArea", "CGS"), "unit:L-PER-SEC-M2"),
            (
                ("VentilationRatePerFloorArea", "CGS-EMU"),
                "unit:L-PER-SEC-M2",
            ),
            (
                ("VentilationRatePerFloorArea", "CGS-GAUSS"),
                "unit:L-PER-SEC-M2",
            ),
            (("VentilationRatePerFloorArea", "SI"), "unit:L-PER-SEC-M2"),
            (("VibrationalDensityOfStates", "CGS"), "unit:SEC-PER-RAD-M3"),
            (
                ("VibrationalDensityOfStates", "CGS-EMU"),
                "unit:SEC-PER-RAD-M3",
            ),
            (
                ("VibrationalDensityOfStates", "CGS-GAUSS"),
                "unit:SEC-PER-RAD-M3",
            ),
            (("VibrationalDensityOfStates", "SI"), "unit:SEC-PER-RAD-M3"),
            (("Volume", "CGS"), "unit:L"),
            (("Volume", "CGS-EMU"), "unit:L"),
            (("Volume", "CGS-GAUSS"), "unit:L"),
            (("Volume", "IMPERIAL"), "unit:FBM"),
            (("Volume", "PLANCK"), "unit:PlanckVolume"),
            (("Volume", "SI"), "unit:L"),
            (("Volume", "USCS"), "unit:NT"),
            (("VolumeFlowRate", "CGS"), "unit:L-PER-HR"),
            (("VolumeFlowRate", "CGS-EMU"), "unit:L-PER-HR"),
            (("VolumeFlowRate", "CGS-GAUSS"), "unit:L-PER-HR"),
            (("VolumeFlowRate", "IMPERIAL"), "unit:FT3-PER-HR"),
            (("VolumeFlowRate", "SI"), "unit:L-PER-HR"),
            (("VolumeFlowRate", "USCS"), "unit:FT3-PER-HR"),
            (("VolumeFraction", "CGS"), "unit:L-PER-L"),
            (("VolumeFraction", "CGS-EMU"), "unit:L-PER-L"),
            (("VolumeFraction", "CGS-GAUSS"), "unit:L-PER-L"),
            (("VolumeFraction", "SI"), "unit:L-PER-L"),
            (("VolumePerArea", "CGS"), "unit:M3-PER-HA"),
            (("VolumePerArea", "CGS-EMU"), "unit:M3-PER-HA"),
            (("VolumePerArea", "CGS-GAUSS"), "unit:M3-PER-HA"),
            (("VolumePerArea", "SI"), "unit:M3-PER-HA"),
            (("VolumeThermalExpansion", "IMPERIAL"), "unit:FT3-PER-DEG_F"),
            (("VolumeThermalExpansion", "SI"), "unit:L-PER-K"),
            (("VolumeThermalExpansion", "USCS"), "unit:FT3-PER-DEG_F"),
            (("VolumetricFlux", "CGS"), "unit:MilliL-PER-CentiM2-MIN"),
            (("VolumetricFlux", "CGS-EMU"), "unit:MilliL-PER-CentiM2-MIN"),
            (
                ("VolumetricFlux", "CGS-GAUSS"),
                "unit:MilliL-PER-CentiM2-MIN",
            ),
            (("VolumetricFlux", "SI"), "unit:MilliL-PER-CentiM2-MIN"),
            (
                ("VolumetricHeatCapacity", "IMPERIAL"),
                "unit:LB_F-PER-IN2-DEG_F",
            ),
            (("VolumetricHeatCapacity", "SI"), "unit:J-PER-M3-K"),
            (
                ("VolumetricHeatCapacity", "USCS"),
                "unit:LB_F-PER-IN2-DEG_F",
            ),
            (("WarpingConstant", "CGS"), "unit:M6"),
            (("WarpingConstant", "CGS-EMU"), "unit:M6"),
            (("WarpingConstant", "CGS-GAUSS"), "unit:M6"),
            (("WarpingConstant", "SI"), "unit:M6"),
            (("WarpingMoment", "CGS"), "unit:N-M2"),
            (("WarpingMoment", "CGS-EMU"), "unit:N-M2"),
            (("WarpingMoment", "CGS-GAUSS"), "unit:N-M2"),
            (("WarpingMoment", "SI"), "unit:N-M2"),
        ])
    });
