/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.Observability.AkriObservabilityService
{
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Enumerates structured error types for failed metric operations.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public enum AkriMetricErrorKind
    {
        [EnumMember(Value = @"ConflictingMetricDefinition")]
        ConflictingMetricDefinition = 0,
        [EnumMember(Value = @"DuplicateOperationId")]
        DuplicateOperationId = 1,
        [EnumMember(Value = @"InternalError")]
        InternalError = 2,
        [EnumMember(Value = @"TooManyUniqueLabelSets")]
        TooManyUniqueLabelSets = 3,
    }
}
