/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace Azure.Iot.Operations.Services.Observability.AkriObservabilityService
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using Azure.Iot.Operations.Services.Observability;

    public static partial class AkriObservabilityService
    {
        /// <summary>
        /// Specializes the <c>CommandInvoker</c> class for Command 'publishMetrics'.
        /// </summary>
        public class PublishMetricsCommandInvoker : CommandInvoker<PublishMetricsRequestPayload, PublishMetricsResponsePayload>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="PublishMetricsCommandInvoker"/> class.
            /// </summary>
            public PublishMetricsCommandInvoker(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "publishMetrics", new Utf8JsonSerializer())
            {
                this.ResponseTopicPrefix = "clients/{invokerClientId}"; // default value, can be overwritten by user code

                TopicTokenMap["modelId"] = "dtmi:com:microsoft:akri:AkriObservabilityService;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["invokerClientId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "publishMetrics";
            }
        }
    }
}
