#cloud-config

package_update: true
package_upgrade: true
apt:
  preserve_sources_list: true
  sources:
    msft.list:
      source: 'deb [signed-by=$KEY_FILE] https://packages.microsoft.com/ubuntu/24.04/prod noble main'
      keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    azurecli.list:
      source: 'deb [signed-by=$KEY_FILE] https://packages.microsoft.com/repos/azure-cli noble main'
      keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    kubernetes.list:
      source: 'deb [signed-by=$KEY_FILE] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
      keyid: DE15B14486CD377B9E876E1A234654DA9A296436

packages:
  - azure-cli
  - kubectl
  - git
  - moby-cli
  - moby-engine

runcmd:
  - MYUSER=`id -un 1000`
  - MYHOME=`eval echo ~$MYUSER`
  - MYWORK=/workspaces
  - LOCATION={{{location}}}
  - RESOURCE_GROUP={{{resource_group}}}
  - RESOURCE_NAME={{{resource_name}}}
  - |
    mkdir $MYWORK
    cd $MYWORK
    git clone https://github.com/azure/iot-operations-sdks
    ./iot-operations-sdks/tools/deployment/initialize-cluster.sh
    az login --identity
    az connectedk8s connect --name $RESOURCE_NAME --location $LOCATION --resource-group $RESOURCE_GROUP --kube-config .kube/config
  - |
    install -D -o $MYUSER -g $MYUSER -m 600 $MYWORK/.kube/config $MYHOME/.kube/config
    chown -R $MYUSER:$MYUSER $MYWORK
