#cloud-config

package_update: true
package_upgrade: true
# package_reboot_if_required: true
apt:
  preserve_sources_list: true
  sources:
    msft.list:
      source: 'deb [signed-by=$KEY_FILE] https://packages.microsoft.com/ubuntu/24.04/prod noble main'
      keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    azurecli.list:
      source: 'deb [signed-by=$KEY_FILE] https://packages.microsoft.com/repos/azure-cli noble main'
      keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    kubernetes.list:
      source: 'deb [signed-by=$KEY_FILE] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /'
      keyid: DE15B14486CD377B9E876E1A234654DA9A296436
    step.list:
      source: 'deb https://packages.smallstep.com/stable/debian debs main'
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        xsBNBGCRt7MBCADkYJHHQQoL6tKrW/LbmfR9ljz7ib2aWno4JO3VKQvLwjyUMPpq
        /SXXMOnx8jXwgWizpPxQYDRJ0SQXS9ULJ1hXRL/OgMnZAYvYDeV2jBnKsAIEdiG/
        e1qm8P4W9qpWJc+hNq7FOT13RzGWRx57SdLWSXo0KeY38r9lvjjOmT/cuOcmjwlD
        T9XYf/RSO+yJ/AsyMdAr+ZbDeQUd9HYJiPdI04lGaGM02MjDMnx+monc+y54t+Z+
        ry1WtQdzoQt9dHlIPlV1tR+xV5DHHsejCZxu9TWzzSlL5wfBBeEz7R/OIzivGJpW
        QdJzd+2QDXSRg9q2XYWP5ZVtSgjVVJjNlb6ZABEBAAHNVEFydGlmYWN0IFJlZ2lz
        dHJ5IFJlcG9zaXRvcnkgU2lnbmVyIDxhcnRpZmFjdC1yZWdpc3RyeS1yZXBvc2l0
        b3J5LXNpZ25lckBnb29nbGUuY29tPsLAjgQTAQoAOBYhBDW6oLM+nrOW9ZyoOMC6
        XObcYxWjBQJgkbezAhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEMC6XObc
        YxWj+igIAMFh6DrAYMeq9sbZ1ZG6oAMrinUheGQbEqe76nIDQNsZnhDwZ2wWqgVC
        7DgOMqlhQmOmzm7M6Nzmq2dvPwq3xC2OeI9fQyzjT72deBTzLP7PJok9PJFOMdLf
        ILSsUnmMsheQt4DUO0jYAX2KUuWOIXXJaZ319QyoRNBPYa5qz7qXS7wHLOY89IDq
        fHt6Aud8ER5zhyOyhytcYMeaGC1g1IKWmgewnhEq02FantMJGlmmFi2eA0EPD02G
        C3742QGqRxLwjWsm5/TpyuU24EYKRGCRm7QdVIo3ugFSetKrn0byOxWGBvtu4fH8
        XWvZkRT+u+yzH1s5yFYBqc2JTrrJvRU=
        =QnvN
        -----END PGP PUBLIC KEY BLOCK-----

packages:
  - azure-cli
  - kubectl
  - git
  - docker.io
  - step-cli

runcmd:
  - |
    curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
    wget -q https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.deb && dpkg -i ./k9s_linux_amd64.deb

