apiVersion: namespaces.deviceregistry.microsoft.com/v1beta1
kind: Device
metadata:
  name: rest-sensor
  namespace: azure-iot-operations
spec:
  attributes:
    deviceId: rest-sensor
    deviceType: weather-sensor
  enabled: true
  endpoints:
    inbound:
      rest-sensor-endpoint:
        address: rest-server-service.azure-iot-operations.svc.cluster.local:8000 # Address of the REST server service
        additionalConfiguration: |-
          {
            "tlsEnabled": false
          }
        authentication:
          # method: Anonymous
          method: UsernamePassword
          usernamePasswordCredentials:
            passwordSecretName: testsecret/passwordKey
            usernameSecretName: testsecret/usernameKey
        endpointType: rest
  version: 1