apiVersion: connectivity.iotoperations.azure.com/v1
kind: Dataflow
metadata:
  name: rust-rest-to-event-hubs
  namespace: azure-iot-operations
spec:
  mode: Enabled
  operations:
  - name: null
    operationType: Source
    sourceSettings:
      assetRef: null
      dataSources:
      - weather/sensor
      endpointRef: default
      schemaRef: null
      serializationFormat: Json
  - builtInTransformationSettings:
      datasets: 
      - key: factory # key IMP
        inputs: []
        expression: 1 == 1
      filter: []
      map:
      - description: null
        expression: null
        inputs:
        - '*'
        output: '*'
        type: PassThrough
      - inputs:
        - $context(factory).floorNumber #  - $1 
        output: FactoryFloor
      - inputs:
        - $context(factory).factoryId #  - $1 
        output: FactoryId
      schemaRef: null
      serializationFormat: Json
    name: null
    operationType: BuiltInTransformation
  - destinationSettings:
      dataDestination: myeh2406422sec #Kafka topic
      endpointRef: dfep2406422 # DP Endpoint from DOE
    name: null
    operationType: Destination
  profileRef: default