/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

mod create_discovered_asset_endpoint_profile_command_invoker;
mod create_discovered_asset_endpoint_profile_request_payload;
mod create_discovered_asset_endpoint_profile_request_payload_serialization;
mod create_discovered_asset_endpoint_profile_response_payload;
mod create_discovered_asset_endpoint_profile_response_payload_serialization;
mod create_discovered_asset_endpoint_profile_response_schema;
mod discovered_asset_endpoint_profile;
mod discovered_asset_endpoint_profile_response_status_schema;
mod supported_authentication_methods_schema_element_schema;

pub use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;

pub use super::common_types::common_options::{CommandOptions, TelemetryOptions};

pub const MODEL_ID: &str = "dtmi:com:microsoft:akri:AepTypeService;1";
pub const REQUEST_TOPIC_PATTERN: &str =
    "akri/connector/resources/{ex:connectorClientId}/{ex:aepType}/{commandName}";

pub mod client {
    pub use super::create_discovered_asset_endpoint_profile_command_invoker::*;
    pub use super::create_discovered_asset_endpoint_profile_request_payload::*;
    pub use super::create_discovered_asset_endpoint_profile_response_payload::*;
    pub use super::create_discovered_asset_endpoint_profile_response_schema::*;
    pub use super::discovered_asset_endpoint_profile::*;
    pub use super::discovered_asset_endpoint_profile_response_status_schema::*;
    pub use super::supported_authentication_methods_schema_element_schema::*;
}
