apiVersion: akri.microsoft.com/v1  # This is spec.group/versions.name from connector_config_crd.yaml
kind: ConnectorConfig
metadata:
  name: http-connector-app-config
  namespace: azure-iot-operations
spec:
  replicas: 1
  endpointProfileType: http-dss
  image: httpconnectorworkerservice:latest
  mqTargetAddress: aio-broker-external.azure-iot-operations.svc.cluster.local  # TODO why is this the external service? Shouldn't it be internal # kubectl get services => type = clusterIp~~Loadbalancer~~ => (<name>.<namespace>.svc.cluster.local)
  mqTls:
    enabled: false
