apiVersion: v1
kind: Secret
metadata:
  name: http-credentials
  namespace: azure-iot-operations
type: Opaque
data:
  username: c29tZS11c2VybmFtZQ== # "some-username"
  password: c29tZS1wYXNzd29yZA== # "some-password"