apiVersion: deviceregistry.microsoft.com/v1beta2 # This is spec.group/versions.name from aep_crd.yaml
kind: AssetEndpointProfile
metadata:
  name: my-http-dss-aep
  namespace: azure-iot-operations
spec:
  additionalConfiguration: '{"DataSourceType": "Http", "HttpPath": "contexts/quality", "RequestIntervalInSeconds":15, "DssKey": "quality", "MqttClientId": "myHttpDssClient"}'
  authentication:
    method: UsernamePassword
    usernamePasswordCredentials:
      usernameSecretName: some-username
      passwordSecretName: some-password
  discoveredAssetEndpointProfileRef: my-http-dss-discovered-asset-endpoint-profile
  endpointProfileType: http-dss
  targetAddress: http://my-backend-api-s.default.svc.cluster.local:80 # backend-api.yaml => <Service.metadata.name>.<namespace>.svc.cluster.local:<port>)
  uuid: 1234-5678-9012-3456