apiVersion: deviceregistry.microsoft.com/v1beta2
kind: Asset
metadata:
  name: REST-sample
  namespace: azure-iot-operations
spec:
  displayName: REST Sample Asset 1
  description: A sample for an Asset modeling a device with REST endpoint
  assetEndpointProfileRef: {{ .Values.endpointProfile }}
  datasetsConfiguration: |-
   {
      "samplingInterval": 400,
    }
  topic:
    path: /mqtt/machine/status
    retain: Keep         
  datasets:
    - name: machine_status
      dataPoints:
        - dataSource: /api/machine/status
          name: status
          dataPointConfiguration: |-
           {
              "HttpRequestMethod": "GET",
           }
          observabilityMode: Log
