apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-server-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-server-dotnet
  template:
    metadata:
      labels:
        app: counter-server-dotnet
    spec:
      containers:
      - name: counter-server-dotnet
        image: k3d-registry.localhost:5500/counter-server-dotnet:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: mqtt-client-token
          mountPath: /var/run/secrets/tokens
        env:
        - name: ConnectionStrings__Default
          value: "HostName=aio-mq-dmqtt-frontend;UseTls=false;TcpPort=1883;SatAuthFile=/var/run/secrets/tokens/mqtt-client-token;CleanStart=false;ConnectionTimeout=PT5S;ClientId=CounterServer"
        - name: mqttDiag
          value: "false"
      volumes:
      - name: mqtt-client-token
        projected:
          sources:
          - serviceAccountToken:
              path: mqtt-client-token
              audience: aio-mq
              expirationSeconds: 1200