apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-server-go
  template:
    metadata:
      labels:
        app: counter-server-go
    spec:
      containers:
      - name: counter-go-server
        image: k3d-registry.localhost:5500/counter-server-go:latest
        imagePullPolicy: Always
        env:
        - name: MQTT_HOST_NAME
          value: "aio-broker"
        - name: MQTT_CLIENT_ID
          value: "CounterServer-go"
