/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using error_no_output_sample;

namespace error_no_output_sample.ErrorNoOutput
{
    /// <summary>
    /// Response to a 'deleteThing' Action.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "1.0.0.0")]
    public partial class DeleteThingResponseSchema
    {
        /// <summary>
        /// Error for the 'deleteThing' Action.
        /// </summary>
        [JsonPropertyName("_error")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public SampleError? Error { get; set; } = default;

    }
}
