/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

#nullable enable

using System;
using error_no_output_sample;

namespace error_no_output_sample.ErrorNoOutput
{
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompilerLib", "1.0.0.0")]
    public partial class SampleErrorException : Exception
    {
        public SampleErrorException(SampleError sampleError)
            : base(sampleError.Message)
        {
            SampleError = sampleError;
        }

        public SampleError SampleError { get; }
    }
}
