// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Azure.Iot.Operations.Opc2WotLib
{
    using System.Collections.Generic;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class WotDataSchemaArray : WotDataSchema
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
 // Copyright (c) Microsoft Corporation. 
 // Licensed under the MIT License 
 if (this.description != null) { 
            this.Write("\"description\": \"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.description));
            this.Write("\",\r\n");
 } 
            this.Write("\"type\": \"array\",\r\n\"items\": {\r\n");
 this.PushIndent("  "); 
            this.Write(this.ToStringHelper.ToStringWithCulture(this.itemDataSchema.TransformText()));
            this.Write("\r\n");
 this.PopIndent(); 
            this.Write("}");
            return this.GenerationEnvironment.ToString();
        }
    }
}
