name: CD-go

# Since this is a no-op on existing versions, it runs on every push to main
# to ensure releases are picked up promptly in case of failure.
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Release Go SDKs
      run: go/tools/release.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
