name: CI-dotnet

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'dotnet/**'
      - 'eng/test/test-cases/Protocol/**'
      - 'eng/test/faultablemqttbroker/**'      
      - 'tools/dsscli/**'
      - 'codegen/**'
  push:
    branches:
    - main  
  schedule:
  - cron: '0 11 * * *'  # Nightly at 4am PST

permissions:
  contents: read
  actions: read
  checks: write
  id-token: write # Require write permission to Fetch an OIDC token.

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup cluster
      run: |
        tools/deployment/initialize-cluster.sh
        tools/deployment/deploy-aio.sh nightly

    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Deploy AIO
      run: |
        tools/deployment/initialize-cluster.sh
        
        echo "Starting postCreateCommand"

        BASE_NAME=`echo ${CODESPACE_NAME//-} | head -c 12`

        # create environment variables to support deployment
        echo "export SESSION=$PWD/.session
        export CLUSTER_NAME=${BASE_NAME}
        export STORAGE_ACCOUNT=${BASE_NAME}storage
        export SCHEMA_REGISTRY=${BASE_NAME}schema
        export SCHEMA_REGISTRY_NAMESPACE=${BASE_NAME}schemans" >> ~/.bashrc

        # create a default resource group if not defined
        export RESOURCE_GROUP=aio-${BASE_NAME}" >> ~/.bashrc

        # create a default location if not defined
        export LOCATION=westus3" >> ~/.bashrc

        echo "Ending postCreateCommand"

        tools/deployment/install-aio-extension.sh

