name: CI-Dotnet

on:
  workflow_dispatch:

# only allow one run / branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
    
jobs:
  build:
    runs-on: ubuntu-22.04
    name: CI-Dotnet
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: dotnet info
      run: |
          sudo apt-get update
          sudo apt-get install nuget -y

    - name: Generate .snupkg files
      run: |
          dotnet pack --configuration Release ./dotnet/src/Azure.Iot.Operations.Mqtt/Azure.Iot.Operations.Mqtt.csproj -o ./_nupkgs/ -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet pack --configuration Release ./dotnet/src/Azure.Iot.Operations.Protocol/Azure.Iot.Operations.Protocol.csproj -o ./_nupkgs/ -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet pack --configuration Release ./dotnet/src/Azure.Iot.Operations.Services/Azure.Iot.Operations.Services.csproj -o ./_nupkgs/ -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
    
    - name: Upload .snupkg files to Nuget.org
      run: |
          nuget SetApiKey ${{ secrets.NUGET_API_KEY }}
          cd ./_nupkgs/
          ls
          nuget push *.snupkg