name: CI-Dotnet

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/**'
      - 'dotnet/**'
      - 'eng/test/test-cases/Protocol/**'
      - 'eng/test/faultablemqttbroker/**'
      - 'tools/deployment/**'
      - 'tools/dsscli/**'
      - 'codegen/**'
  push:
    branches:
    - main
  schedule:
  - cron: '0 11 * * *'  # Nightly at 4am PST

# only allow one run / branch at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: CI-dotnet
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Install AIO
      uses: ./.github/actions/configure-aio
      with:
        wait-for-broker: 'true'
        install-dotnet: 'true'
        ssh-key: ${{ secrets.ACTIONS_REPO_SSH_KEY }}

    - name: dotnet info
      run: dotnet --info

    - name: Build SDK (Debug)
      run: dotnet build -c Debug dotnet/Azure.Iot.Operations.sln


    - name: Build SDK (Release)
      run: dotnet build -c Release dotnet/Azure.Iot.Operations.sln

    - name: Build EdgeRegistry Host
      run: dotnet build eng/test/edge-registry/src/Azure.Iot.Operations.Services.EdgeRegistry.Host/Azure.Iot.Operations.Services.EdgeRegistry.Host.csproj

    - name: Setup EdgeRegistry Host
      run: RUNNER_TRACKING_ID="" && dotnet run --project eng/test/edge-registry/src/Azure.Iot.Operations.Services.EdgeRegistry.Host/Azure.Iot.Operations.Services.EdgeRegistry.Host.csproj &

    # This file is created by configure-aio.sh
    - name: Load test service account token into environment
      run: |
        if [ ! -f ".session/token.txt" ]; then
          echo "Missing 'token.txt' file"
          exit 1
        fi

        echo "TOKEN_FILE_PATH=$(pwd)/.session/token.txt" >> $GITHUB_ENV

    # This file is created by configure-aio.sh
    - name: Load CA certificate into environment
      run: |
        if [ ! -f ".session/broker-ca.crt" ]; then
          echo "Missing 'broker-ca.crt' file"
          exit 1
        fi

        echo "CA_FILE_PATH=$(pwd)/.session/broker-ca.crt" >> $GITHUB_ENV

    # These files are created by configure-aio.sh
    - name: Load client certificates into environment
      run: |
        if [ ! -f ".session/client.key" ]; then
          echo "Missing 'client.key' file"
          exit 1
        fi

        if [ ! -f ".session/client.crt" ]; then
          echo "Missing 'client.crt' file"
          exit 1
        fi

        echo "CLIENT_KEY=$(pwd)/.session/client.key" >> $GITHUB_ENV
        echo "CLIENT_CERT=$(pwd)/.session/client.crt" >> $GITHUB_ENV 
    
    - name: Test SDK (TLS + SAT)
      run: dotnet test dotnet/Azure.Iot.Operations.sln -e MQTT_TEST_BROKER_CS="HostName=127.0.0.1;TcpPort=8884;UseTls=true;ClientId=TestClient;CaFile=${{ env.CA_FILE_PATH }};SatAuthFile=${{ env.TOKEN_FILE_PATH }}" -e FAULTABLE_MQTT_TEST_BROKER_CS="HostName=localhost;TcpPort=1884;UseTls=false;ClientId=TestClient" --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=test-results.trx" -- xunit.parallelizeAssembly=true

    - name: Azure.Iot.Operations.Mqtt.UnitTests Package Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Mqtt.UnitTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Azure.Iot.Operations.Mqtt.IntegrationTests Package Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Mqtt.IntegrationTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Azure.Iot.Operations.Protocol.UnitTests Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Protocol.UnitTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        
    - name: Azure.Iot.Operations.Protocol.IntegrationTests Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Protocol.IntegrationTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Azure.Iot.Operations.Protocol.MetlTests Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Protocol.MetlTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Azure.Iot.Operations.Services.UnitTests Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Services.UnitTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Azure.Iot.Operations.Services.IntegrationTests Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Services.IntegrationTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - name: Azure.Iot.Operations.Connector.UnitTests Code Coverage
      uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
      if: always()
      with:
        filename: ./**/Azure.Iot.Operations.Connector.UnitTests/TestResults/*/coverage.cobertura.xml
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both

    - uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3
      id: test-reporter
      if: always()
      with:
        name: dotnet test report
        path: 'dotnet/**/test-results.trx,tools/**/test-results.trx'
        reporter: dotnet-trx  

    - name: Display logs from all kubernetes pods
      if: always()
      run: |
        kubectl get pods
        for pod in $(kubectl get pods -o jsonpath='{.items[*].metadata.name}'); do
          echo "Logs for pod: $pod"
          kubectl describe pod $pod
          kubectl logs $pod
          echo "-----------------------------------"
        done

    - name: Annotate Test Report
      if: always()
      run: echo Test Report ${{ steps.test-reporter.outputs.url_html }} >> $GITHUB_STEP_SUMMARY