name: CI-go

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'go/**'
      - 'eng/test/test-cases/Protocol/**'
  push:
    branches:
    - main  
  schedule:
  - cron: '0 11 * * *'  # Nightly at 4am PST
  
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup IoTMQ
        run: |
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          k3d cluster delete
          k3d registry create registry.localhost --port 5500
          k3d cluster create -p '1883:1883@loadbalancer' -p '8883:8883@loadbalancer' --registry-use k3d-registry.localhost:5500
          helm install mq --atomic oci://mqbuilds.azurecr.io/helm/mq --version 0.6.0-nightly

      - name: Setup cert-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.13 --set installCRDs=true --set extraArgs={--enable-certificate-owner-ref=true} 
          kubectl apply -f .devcontainer/ca.yaml

      - name: Create Kubernetes Token
        run: |
          kubectl create token default --duration=86400s --audience=aio-mq > .devcontainer/token.txt
          echo "TOKEN_FILE_PATH=$(pwd)/.devcontainer/token.txt" >> $GITHUB_ENV
      
      - name: Create CA certificate
        run: |
          kubectl get secret test-ca-cert -o json | jq -r '.data["tls.crt"]' | base64 -d > .devcontainer/ca.crt
          echo "CA_FILE_PATH=$(pwd)/.devcontainer/ca.crt" >> $GITHUB_ENV    

      - name: Setup Brokers
        run: |
          kubectl apply -f .devcontainer/mq/
          kubectl apply -f .devcontainer/tls-listener.yaml

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.301

      - name: CIVerify Go protocol module
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: civerify
          workdir: ./go/protocol

      - name: CIVerify Go mqtt module
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: civerify
          workdir: ./go/mqtt

      - name: CIVerify Go protocol tests
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: civerify
          workdir: ./go/test/protocol

      - name: Build codegen
        run: dotnet build codegen/src/Akri.Dtdl.Codegen/Akri.Dtdl.Codegen.csproj

      - name: Codegen Counter for Go
        working-directory: ./go/samples/counter/envoy
        run: ./gen.sh

      - name: Run counter server
        working-directory: ./go/samples/counter/server
        run: MQTT_HOST_NAME=localhost MQTT_USE_TLS=true MQTT_TCP_PORT=8883 MQTT_AUTH_METHOD=K8S-SAT MQTT_CA_FILE=${{ env.CA_FILE_PATH }} MQTT_SAT_AUTH_FILE=${{ env.TOKEN_FILE_PATH }} MQTT_CLIENT_ID=CounterServer-go go run server.go &

      - name: Run counter client
        working-directory: ./go/samples/counter/client
        run: MQTT_HOST_NAME=localhost MQTT_USE_TLS=true MQTT_TCP_PORT=8883 MQTT_AUTH_METHOD=K8S-SAT MQTT_CA_FILE=${{ env.CA_FILE_PATH }} MQTT_SAT_AUTH_FILE=${{ env.TOKEN_FILE_PATH }} COUNTER_SERVER_ID=CounterServer-go go run client.go go run client.go
