name: CI-go

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'go/**'
      - 'eng/test/test-cases/Protocol/**'
  push:
    branches:
    - main  
  schedule:
  - cron: '0 11 * * *'  # Nightly at 4am PST
  
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.301

      - name: Setup cluster
        run: |
          tools/deployment/initialize-cluster.sh
          tools/deployment/deploy-aio.sh nightly

      - name: Setup faultable MQTT broker
        run: RUNNER_TRACKING_ID="" && dotnet run --project eng/test/faultablemqttbroker/src/Azure.Iot.Operations.FaultableMqttBroker/Azure.Iot.Operations.FaultableMqttBroker.csproj &

      - name: Verify Go protocol module
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: civerify
          workdir: ./go/protocol

      - name: Verify Go mqtt module
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: civerify
          workdir: ./go/mqtt

      - name: Verify Go protocol tests
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: civerify
          workdir: ./go/test/protocol

      - name: Build codegen
        run: dotnet build codegen/src/Akri.Dtdl.Codegen/Akri.Dtdl.Codegen.csproj

      - name: Codegen counter for Go
        working-directory: ./go/samples/counter/envoy
        run: ./gen.sh

      - name: Run counter server
        working-directory: ./go/samples/counter/server
        run: MQTT_HOST_NAME=localhost MQTT_USE_TLS=true MQTT_TCP_PORT=8883 MQTT_AUTH_METHOD=K8S-SAT MQTT_CA_FILE=${{ env.CA_FILE_PATH }} MQTT_SAT_AUTH_FILE=${{ env.TOKEN_FILE_PATH }} MQTT_CLIENT_ID=CounterServer-go go run server.go &

      - name: Run counter client
        working-directory: ./go/samples/counter/client
        run: MQTT_HOST_NAME=localhost MQTT_USE_TLS=true MQTT_TCP_PORT=8883 MQTT_AUTH_METHOD=K8S-SAT MQTT_CA_FILE=${{ env.CA_FILE_PATH }} MQTT_SAT_AUTH_FILE=${{ env.TOKEN_FILE_PATH }} COUNTER_SERVER_ID=CounterServer-go go run client.go go run client.go
