name: CI-Markdown

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 8 * * *' # Nightly at 1am PST

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6      
        with:
          strict: false
          config: '.vscode/cspell.json'
          check_dot_files: "false"
          verbose: true
          #incremental_files_only: true

      - name: Link check
        run: |
          npm install -g @umbrelladocs/linkspector
          linkspector check -c ./.github/.linkspector.yml
