name: CI-Markdown

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Nightly at 1am PST  

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Link checking
        run: |
          npm install -g @umbrelladocs/linkspector
          linkspector check
