name: CI-Markdown

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 8 * * *" # Nightly at 1am PST

permissions:
  contents: read
  actions: read
  checks: write

env:
  # Check all files if scheduled, otherwise only check changes lines
  FILTER_MODE: ${{ github.event_name == 'schedule' && 'nofilter' || 'added' }}

jobs:
  spellcheck:
    name: CI-spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        continue-on-error: true
        with:
          files: "**/*"
          config: ".vscode/cspell.json"
          suggestions: true
          incremental_files_only: true

  # https://github.com/UmbrellaDocs/action-linkspector
  linkcheck:
    name: CI-links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          config_file: .github/.linkspector.yml
          fail_level: warning
          filter_mode: ${{ FILTER_MODE }}
          show_stats: true
