name: CI-Markdown

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 8 * * *" # Nightly at 1am PST

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  spellcheck:
    name: CI-spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        continue-on-error: true
        with:
          files: "**/*"
          config: ".vscode/cspell.json"
          suggestions: true
          incremental_files_only: true

  linkcheck:
    name: CI-links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Install linkspector
        run: |
          npm install -g @umbrelladocs/linkspector
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Run linkspector
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          linkspector check -c .github/.linkspector.yml -j |
            reviewdog -f=rdjson \
              -name=Linkspector \
              -reporter=github-pr-check \
              -fail-level=error \
              -filter-mode=${{ github.event_name == 'schedule' && 'nofilter' || 'added' }}
