name: CI-Markdown

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "0 8 * * *" # Nightly at 1am PST

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  spellcheck:
    name: CI-spelling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        continue-on-error: true
        with:
          files: "**/*"
          config: ".vscode/cspell.json"
          suggestions: true
          incremental_files_only: true

  # https://github.com/UmbrellaDocs/action-linkspector
  linkcheck:
    name: CI-links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linkspector
        run: |
          npm install -g @umbrelladocs/linkspector
          linkspector --version
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Run linkspector
        run: |
          linkspector check -c .github/.linkspector.yml -j
  #         |
  # reviewdog -f=rdjson \
  #   -name="${INPUT_TOOL_NAME}" \
  #   -reporter="${INPUT_REPORTER}" \
  #   -filter-mode="${INPUT_FILTER_MODE}" \
  #   -fail-level="${INPUT_FAIL_LEVEL}" \
  #   -level="${INPUT_LEVEL}" \
  #   "${INPUT_REVIEWDOG_FLAGS}"

      # - name: Run linkspector
      #   uses: umbrelladocs/action-linkspector@v1
      #   with:
      #     config_file: .github/.linkspector.yml
      #     # fail_level: error
      #     filter_mode: nofilter
      #     # filter_mode: ${{ github.event_name == 'schedule' && 'nofilter' || 'added' }}
      #     # show_stats: true
