name: CI-Markdown

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 8 * * *' # Nightly at 1am PST

jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: '**/*'
          config: '.vscode/cspell.json'
          suggestions: true
          incremental_files_only: true

  linkcheck:
    name: Check web links
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Run link checking, allow unpriveleged user namespace
      - name: Link check
        run: |
          echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns 
          npm install -g @umbrelladocs/linkspector
          linkspector check -c ./.github/.linkspector.yml
