name: Linkspector

on: 
  pull_request:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      

      - uses: umbrelladocs/action-linkspector@v1
