// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Azure.Iot.Operations.EnvoyGenerator
{
    using Azure.Iot.Operations.CodeGeneration;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class RustTelemetrySender : RustTelemetrySenderBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
 // Copyright (c) Microsoft Corporation. 
 // Licensed under the MIT License 
            this.Write("/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v");
            this.Write(this.ToStringHelper.ToStringWithCulture(System.Reflection.Assembly.GetExecutingAssembly().GetName().Version));
            this.Write(@"; DO NOT EDIT. */

use std::collections::HashMap;
use std::time::Duration;

use azure_iot_operations_mqtt::control_packet::QoS;
use azure_iot_operations_mqtt::session::SessionManagedClient;
use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;
use azure_iot_operations_protocol::common::payload_serialize::PayloadSerialize;
use azure_iot_operations_protocol::telemetry;
use azure_iot_operations_protocol::application::ApplicationContext;

");
 if (this.schemaType is CodeName) { 
            this.Write("use super::");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetFileName(TargetLanguage.Rust)));
            this.Write("::");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetTypeName(TargetLanguage.Rust)));
            this.Write(";\r\n");
 } 
 if (this.schemaType is CustomTypeName) { 
            this.Write("use super::super::");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.commonNs.GetFolderName(TargetLanguage.Rust)));
            this.Write("::custom_payload::CustomPayload;\r\n");
 } 
            this.Write("use super::super::");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.commonNs.GetFolderName(TargetLanguage.Rust)));
            this.Write("::options::TelemetrySenderOptions;\r\n\r\npub type ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write(" = telemetry::sender::Message<");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetTypeName(TargetLanguage.Rust)));
            this.Write(">;\r\npub type ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("BuilderError = telemetry::sender::MessageBuilderError;\r\n\r\n/// Builder for [`");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("`]\r\n#[derive(Default)]\r\npub struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("Builder {\r\n    inner_builder: telemetry::sender::MessageBuilder<");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetTypeName(TargetLanguage.Rust)));
            this.Write(">,\r\n    topic_tokens: HashMap<String, String>,\r\n}\r\n\r\nimpl ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("Builder {\r\n    /// Quality of Service of the telemetry message. Can only be `AtMo" +
                    "stOnce` or `AtLeastOnce`.\r\n    pub fn qos(&mut self, qos: QoS) -> &mut Self {\r\n " +
                    "       self.inner_builder.qos(qos);\r\n        self\r\n    }\r\n\r\n    /// Custom user " +
                    "data to set on the message\r\n    pub fn custom_user_data(&mut self, custom_user_d" +
                    "ata: Vec<(String, String)>) -> &mut Self {\r\n        self.inner_builder.custom_us" +
                    "er_data(custom_user_data);\r\n        self\r\n    }\r\n\r\n    /// Topic token keys/valu" +
                    "es to be replaced into the publish topic of the telemetry message.\r\n    /// A pr" +
                    "efix of \"ex:\" will be prepended to each key before scanning the topic pattern.\r\n" +
                    "    /// Thus, only tokens of the form `{ex:SOMEKEY}` will be replaced.\r\n    pub " +
                    "fn topic_tokens(&mut self, topic_tokens: HashMap<String, String>) -> &mut Self {" +
                    "\r\n        for (k, v) in topic_tokens {\r\n            self.topic_tokens.insert(for" +
                    "mat!(\"ex:{k}\"), v);\r\n        }\r\n        self\r\n    }\r\n\r\n    /// Time before messa" +
                    "ge expires\r\n    pub fn message_expiry(&mut self, message_expiry: Duration) -> &m" +
                    "ut Self {\r\n        self.inner_builder.message_expiry(message_expiry);\r\n        s" +
                    "elf\r\n    }\r\n\r\n    /// Cloud event for the message\r\n    pub fn cloud_event(&mut s" +
                    "elf, cloud_event: Option<telemetry::sender::CloudEvent>) -> &mut Self {\r\n       " +
                    " self.inner_builder.cloud_event(cloud_event);\r\n        self\r\n    }\r\n\r\n    /// Pa" +
                    "yload of the message\r\n    ///\r\n    /// # Errors\r\n    /// If the payload cannot b" +
                    "e serialized\r\n    pub fn payload(\r\n        &mut self,\r\n        payload: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetTypeName(TargetLanguage.Rust)));
            this.Write(",\r\n    ) -> Result<&mut Self, AIOProtocolError> {\r\n        self.inner_builder.pay" +
                    "load(payload)?;\r\n        Ok(self)\r\n    }\r\n\r\n    /// Builds a new `");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("`\r\n    ///\r\n    /// # Errors\r\n    /// If a required field has not been initialize" +
                    "d\r\n    pub fn build(&mut self) -> Result<");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("BuilderError> {\r\n        self.inner_builder.topic_tokens(self.topic_tokens.clone(" +
                    "));\r\n\r\n        self.inner_builder.build()\r\n    }\r\n}\r\n\r\n/// Telemetry Sender for " +
                    "`");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetTypeName(TargetLanguage.Rust)));
            this.Write("`\r\npub struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.componentName.GetTypeName(TargetLanguage.Rust)));
            this.Write("(\r\n    telemetry::Sender<");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.schemaType.GetTypeName(TargetLanguage.Rust)));
            this.Write(">,\r\n);\r\n\r\nimpl ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.componentName.GetTypeName(TargetLanguage.Rust)));
            this.Write("\r\n{\r\n    /// Creates a new [`");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.componentName.GetTypeName(TargetLanguage.Rust)));
            this.Write(@"`]
    ///
    /// # Panics
    /// If the DTDL that generated this code was invalid
    pub fn new(application_context: ApplicationContext, client: SessionManagedClient, options: &TelemetrySenderOptions) -> Self {
        let mut sender_options_builder = telemetry::sender::OptionsBuilder::default();
        if let Some(topic_namespace) = &options.topic_namespace {
            sender_options_builder.topic_namespace(topic_namespace.clone());
        }

        let mut topic_token_map: HashMap<String, String> = options
            .topic_token_map
            .clone()
            .into_iter()
            .map(|(k, v)| (format!(""ex:{k}""), v))
            .collect();

        topic_token_map.insert(""");
            this.Write(this.ToStringHelper.ToStringWithCulture(MqttTopicTokens.EventSenderId));
            this.Write("\".to_string(), client.client_id().to_string());\r\n\r\n        let sender_options = s" +
                    "ender_options_builder\r\n            .topic_pattern(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.topicPattern));
            this.Write(@""")
            .topic_token_map(topic_token_map)
            .build()
            .expect(""DTDL schema generated invalid arguments"");

        Self(
            telemetry::Sender::new(application_context, client, sender_options)
                .expect(""DTDL schema generated invalid arguments""),
        )
    }

    /// Sends a [`");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write("`]\r\n    ///\r\n    /// # Error\r\n    /// [`AIOProtocolError`] if there is a failure " +
                    "sending the message\r\n    pub async fn send(&self, message: ");
            this.Write(this.ToStringHelper.ToStringWithCulture(this.messageName.GetTypeName(TargetLanguage.Rust)));
            this.Write(") -> Result<(), AIOProtocolError> {\r\n        self.0.send(message).await\r\n    }\r\n}" +
                    "\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public class RustTelemetrySenderBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
