/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.6.0.0; DO NOT EDIT. */

mod telemetry_receiver;
mod telemetry_sender;

pub use azure_iot_operations_protocol::common::aio_protocol_error::AIOProtocolError;

pub use super::common_types::common_options::{CommandOptions, TelemetryOptions};

pub const MODEL_ID: &str = "dtmi:codegen:communicationTest:rawModel;1";
pub const TELEMETRY_TOPIC_PATTERN: &str = "test/RawModel/{senderId}/telemetry";

pub mod client {
    pub use super::telemetry_receiver::*;
}

pub mod service {
    pub use super::telemetry_sender::*;
}
