/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use super::create_version_request_payload::CreateVersionRequestPayload;

pub type CreateVersionInputArguments = CreateVersionRequestPayload;
