/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use super::create_resource_request::CreateResourceRequest;

pub type CreateResourceInputArguments = CreateResourceRequest;
