/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use super::create_resource_request_payload::CreateResourceRequestPayload;

pub type CreateResourceInputArguments = CreateResourceRequestPayload;
