/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::edge_registry_error::EdgeRegistryError;

/// TODO: Dummy output to allow Rust to compile
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct DeleteGroupResponseSchema {
    /// Error for the 'deleteGroup' Action.
    #[serde(rename = "_error")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub error: Option<EdgeRegistryError>,

    /// TODO: Temporary Output
    #[serde(rename = "dummyOutput")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub dummy_output: Option<bool>,
}
