/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use super::resource_xid_list::ResourceXidList;

pub type ListResourcesWithLabelOutputArguments = ResourceXidList;
