/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::thing_model_extension_error::ThingModelExtensionError;

/// List of Version identifiers.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ListThingModelVersionsResponseSchema {
    /// Error for the 'listThingModelVersions' Action.
    #[serde(rename = "_error")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub error: Option<ThingModelExtensionError>,

    /// List of Version identifiers.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub ids: Option<Vec<u64>>,
}
