/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::label::Label;

/// Request payload for listing xRegistry Thing Description Versions, optionally filtered by Group, Thing Description, and/or label.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ListThingDescriptionVersionsRequestPayload {
    /// Group identifier. Uses the default Group if not specified. Ignored if allGroups is true.
    #[serde(rename = "groupId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub group_id: Option<String>,

    /// If true, lists Versions across all Groups (groupId is ignored). If false or unspecified, lists within the Group specified by groupId, or the default Group if groupId is unspecified.
    #[serde(rename = "allGroups")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub all_groups: Option<bool>,

    /// Thing Description Resource identifier. If specified, only Versions of the Thing Description with this identifier are listed; when listing across all Groups, this identifier is matched across all Groups. Lists Versions across all Thing Descriptions if not specified.
    #[serde(rename = "thingDescriptionId")]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub thing_description_id: Option<String>,

    /// If specified, only Versions with this label are listed.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[builder(default = "None")]
    pub label: Option<Label>,
}
