/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use super::thing_description_version_xid_list::ThingDescriptionVersionXidList;

pub type ListThingDescriptionVersionsOutputArguments = ThingDescriptionVersionXidList;
