/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */

use super::schema_version_xid_list::SchemaVersionXidList;

pub type ListSchemaVersionsOutputArguments = SchemaVersionXidList;
