/* Code generated by Azure.Iot.Operations.ProtocolCompilerLib v1.0.0.0; DO NOT EDIT. */
#![allow(unused_imports)]

use std::collections::HashMap;

use chrono::{DateTime, Utc};
use derive_builder::Builder;
use iso8601_duration::Duration;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::super::common_types::{b64::Bytes, date_only::Date, decimal::Decimal, time_only::Time};
use super::thing_description_version_xid::ThingDescriptionVersionXid;

/// List of Thing Description Version XIDs within the provided constraints with the specified label.
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
pub struct ThingDescriptionVersionXidList {
    /// List of Thing Description Version XID components.
    #[builder(default)]
    pub versions: Vec<ThingDescriptionVersionXid>,
}
